#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#  FILE: STIX_GLOBAL
#  A MODULE TO KEEP GLOBAL VARIABLES
#
OK = True
NEXT_PACKET = 2
HEADER_FIRST_BYTE_INVALID = -1
HEADER_INVALID = -2
EOF = -3
MAX_NUM_PARAMETERS = 1024
HEADER_KEY_ERROR = -4
BAD_PACKET = -5
VARIABLE_PACKET_LENGTH_MISMATCH = -6
UNKNOWN_PACKET_TYPE = -7
HEADER_RAW_LENGTH_VALID = -8
NO_PID_INFO_IN_IDB = -9
PACKET_TOO_SHORT = -10
UNKNOWN = 0
