# Generated by Django 2.1.2 on 2019-04-30 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('verbose_name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('icon', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.Sender'),
        ),
    ]
