
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-31T12:17:56+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d9d63ad73caee70a447618b010aaf8c5488c8600",
 "version": "0.4.94"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
