# coding: utf-8

"""
    Quetzalcoatl API

    Quetzal: an API to manage data files and their associated metadata.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: support@quetz.al
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import quetzal.openapi_client
from quetzal.openapi_client.models.pagination_envelope import PaginationEnvelope  # noqa: E501
from quetzal.openapi_client.rest import ApiException


class TestPaginationEnvelope(unittest.TestCase):
    """PaginationEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginationEnvelope(self):
        """Test PaginationEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = quetzal.openapi_client.models.pagination_envelope.PaginationEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
