[tool.poetry]
name = "uvpool"
version = "0.1.0"
description = "A pool of network utilities based on uvloop"
authors = ["Yehuda Deutsch <yeh@uda.co.il>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
uvloop = "^0.13"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
