# coding: utf-8

"""
    

        # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import rebrickable.api
from rebrickable.api.models.all_part import AllPart  # noqa: E501
from rebrickable.api.rest import ApiException


class TestAllPart(unittest.TestCase):
    """AllPart unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllPart(self):
        """Test AllPart"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rebrickable.api.models.all_part.AllPart()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
