[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "wsgi_listener"
author = "Jonny Fuller"
author-email = "mr.waffles@gmail.com"
home-page = "https://github.com/JonnyWaffles/wsgi-listener"
description-file = "README.md"
requires-python=">=3.5"
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Environment :: Web Environment",
    "License :: OSI Approved :: BSD License",
    "Topic :: System :: Monitoring",
    "Topic :: System :: Logging",
    "Topic :: Internet :: WWW/HTTP :: Site Management",
    "Topic :: Internet :: WWW/HTTP :: WSGI",
    "Topic :: Internet :: WWW/HTTP :: WSGI :: Middleware",
]

[tool.flit.metadata.requires-extra]
test = [
    "pytest"
]
doc = ["sphinx"]