
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-17T19:49:33+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "49bc3f4ee0458296aae46a937e31b947ae7e50b3",
 "version": "2.4.0a5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
