# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-17 11:22
from __future__ import unicode_literals

from django.db import migrations
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprovider',
            name='urlid',
            field=djangoldp.fields.LDPUrlField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='urlid',
            field=djangoldp.fields.LDPUrlField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='urlid',
            field=djangoldp.fields.LDPUrlField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='urlid',
            field=djangoldp.fields.LDPUrlField(blank=True, null=True, unique=True),
        ),
    ]
