
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-30T17:43:23-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "98734a3ba3c9b44178c4ba0bce864533ba19b6d5",
 "version": "0.2.4rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
