[tool.poetry]
name = "lethargy"
version = "1.0.0"
description = "A minimal library to make your option-parsing easier."
license = "MIT"
repository = "https://github.com/SeparateRecords/lethargy"
readme = "README.md"
authors = [
    "SeparateRecords <me@rob.ac>"
]
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
]
keywords = [
    "CLI",
    "options",
    "arguments",
    "minimal",
]

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
pytest = "^5.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
