- project:
    templates:
      - publish-openstack-sphinx-docs
      - openstack-python-jobs
      - openstack-python35-jobs
      - check-requirements
      - release-notes-jobs
      - periodic-stable-jobs
    check:
      jobs:
        - manila-tox-genconfig
        - manila-tempest-dsvm-mysql-generic:
            voting: false
        - manila-tempest-dsvm-postgres-container:
            voting: false
        - manila-tempest-dsvm-postgres-zfsonlinux:
            voting: false
        - manila-tempest-dsvm-postgres-generic-singlebackend:
            voting: false
        - manila-tempest-dsvm-generic-no-share-servers:
            voting: false
        - manila-tempest-dsvm-scenario:
            voting: false
        - manila-tempest-minimal-dsvm-cephfs-native-centos-7:
            voting: false
        - manila-tempest-minimal-dsvm-cephfs-nfs-centos-7:
            voting: false
        - manila-tempest-minimal-dsvm-dummy
        - manila-tempest-minimal-dsvm-lvm-centos-7
        - grenade-dsvm-manila:
            voting: false
        - rally-dsvm-manila-multibackend:
            voting: false
        - rally-dsvm-manila-multibackend-no-ss:
            voting: false
        - openstack-tox-cover:
            voting: false
        - openstack-tox-pylint:
            voting: false
    gate:
      queue: manila
      jobs:
        - manila-tox-genconfig
        - manila-tempest-minimal-dsvm-dummy
        - manila-tempest-minimal-dsvm-lvm-centos-7
    experimental:
      jobs:
        - manila-tempest-dsvm-glusterfs-nfs
        - manila-tempest-dsvm-glusterfs-native
        - manila-tempest-dsvm-glusterfs-nfs-heketi
        - manila-tempest-dsvm-glusterfs-native-heketi
        - tripleo-ci-centos-7-scenario004-multinode-oooq-container

    post:
      jobs:
        - openstack-tox-cover
- job:
    name: grenade-dsvm-manila
    parent: legacy-dsvm-base
    run: playbooks/legacy/grenade-dsvm-manila/run.yaml
    post-run: playbooks/legacy/grenade-dsvm-manila/post.yaml
    timeout: 10800
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^install-guide/.*$
      - ^manila/hacking/.*$
      - ^manila/tests/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^tools/.*$
      - ^tox.ini$
    required-projects:
      - openstack/grenade
      - openstack/devstack-gate
      - openstack/manila
      - openstack/python-manilaclient

- job:
    name: legacy-manila-tempest-dsvm-base
    parent: legacy-dsvm-base
    timeout: 7200
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^install-guide/.*$
      - ^manila/hacking/.*$
      - ^manila/tests/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^tools/.*$
      - ^tox.ini$

- job:
    name: manila-tempest-dsvm-container-scenario-custom-image
    parent: legacy-manila-tempest-dsvm-base
    run: playbooks/legacy/manila-tempest-dsvm-container-scenario-custom-image/run.yaml
    post-run: playbooks/legacy/manila-tempest-dsvm-container-scenario-custom-image/post.yaml
    required-projects:
      - openstack/devstack-gate
      - openstack/manila
      - openstack/manila-image-elements
      - openstack/manila-tempest-plugin
      - openstack/python-manilaclient
      - openstack/tempest

- job:
    name: manila-tempest-dsvm-generic-no-share-servers
    parent: legacy-manila-tempest-dsvm-base
    run: playbooks/legacy/manila-tempest-dsvm-generic-no-share-servers/run.yaml
    post-run: playbooks/legacy/manila-tempest-dsvm-generic-no-share-servers/post.yaml
    required-projects:
      - openstack/devstack-gate
      - openstack/manila
      - openstack/manila-image-elements
      - openstack/manila-tempest-plugin
      - openstack/python-manilaclient
      - openstack/tempest

- job:
    name: manila-tempest-dsvm-generic-scenario-custom-image
    parent: legacy-manila-tempest-dsvm-base
    run: playbooks/legacy/manila-tempest-dsvm-generic-scenario-custom-image/run.yaml
    post-run: playbooks/legacy/manila-tempest-dsvm-generic-scenario-custom-image/post.yaml
    required-projects:
      - openstack/devstack-gate
      - openstack/manila
      - openstack/manila-image-elements
      - openstack/manila-tempest-plugin
      - openstack/python-manilaclient
      - openstack/tempest

- job:
    name: manila-tempest-dsvm-glusterfs-native
    parent: legacy-manila-tempest-dsvm-base
    run: playbooks/legacy/manila-tempest-dsvm-glusterfs-native/run.yaml
    post-run: playbooks/legacy/manila-tempest-dsvm-glusterfs-native/post.yaml
    required-projects:
      - openstack/devstack-gate
      - x/devstack-plugin-glusterfs
      - openstack/manila
      - openstack/manila-tempest-plugin
      - openstack/python-manilaclient
      - openstack/tempest

- job:
    name: manila-tempest-dsvm-glusterfs-native-heketi
    parent: legacy-manila-tempest-dsvm-base
    run: playbooks/legacy/manila-tempest-dsvm-glusterfs-native-heketi/run.yaml
    post-run: playbooks/legacy/manila-tempest-dsvm-glusterfs-native-heketi/post.yaml
    required-projects:
      - openstack/devstack-gate
      - x/devstack-plugin-glusterfs
      - openstack/manila
      - openstack/manila-tempest-plugin
      - openstack/python-manilaclient
      - openstack/tempest

- job:
    name: manila-tempest-dsvm-glusterfs-nfs
    parent: legacy-manila-tempest-dsvm-base
    run: playbooks/legacy/manila-tempest-dsvm-glusterfs-nfs/run.yaml
    post-run: playbooks/legacy/manila-tempest-dsvm-glusterfs-nfs/post.yaml
    required-projects:
      - openstack/devstack-gate
      - x/devstack-plugin-glusterfs
      - openstack/manila
      - openstack/manila-tempest-plugin
      - openstack/python-manilaclient
      - openstack/tempest

- job:
    name: manila-tempest-dsvm-glusterfs-nfs-heketi
    parent: legacy-manila-tempest-dsvm-base
    run: playbooks/legacy/manila-tempest-dsvm-glusterfs-nfs-heketi/run.yaml
    post-run: playbooks/legacy/manila-tempest-dsvm-glusterfs-nfs-heketi/post.yaml
    required-projects:
      - openstack/devstack-gate
      - x/devstack-plugin-glusterfs
      - openstack/manila
      - openstack/manila-tempest-plugin
      - openstack/python-manilaclient
      - openstack/tempest

- job:
    name: manila-tempest-dsvm-hdfs
    parent: legacy-manila-tempest-dsvm-base
    run: playbooks/legacy/manila-tempest-dsvm-hdfs/run.yaml
    post-run: playbooks/legacy/manila-tempest-dsvm-hdfs/post.yaml
    required-projects:
      - openstack/devstack-gate
      - x/devstack-plugin-hdfs
      - openstack/manila
      - openstack/manila-tempest-plugin
      - openstack/python-manilaclient
      - openstack/tempest

- job:
    name: manila-tempest-dsvm-mysql-generic
    parent: legacy-manila-tempest-dsvm-base
    run: playbooks/legacy/manila-tempest-dsvm-mysql-generic/run.yaml
    post-run: playbooks/legacy/manila-tempest-dsvm-mysql-generic/post.yaml
    required-projects:
      - openstack/devstack-gate
      - openstack/manila
      - openstack/manila-image-elements
      - openstack/manila-tempest-plugin
      - openstack/python-manilaclient
      - openstack/tempest

- job:
    name: manila-tempest-dsvm-postgres-container
    parent: legacy-manila-tempest-dsvm-base
    run: playbooks/legacy/manila-tempest-dsvm-postgres-container/run.yaml
    post-run: playbooks/legacy/manila-tempest-dsvm-postgres-container/post.yaml
    required-projects:
      - openstack/devstack-gate
      - openstack/manila
      - openstack/manila-image-elements
      - openstack/manila-tempest-plugin
      - openstack/python-manilaclient
      - openstack/tempest

- job:
    name: manila-tempest-dsvm-postgres-generic-singlebackend
    parent: legacy-manila-tempest-dsvm-base
    run: playbooks/legacy/manila-tempest-dsvm-postgres-generic-singlebackend/run.yaml
    post-run: playbooks/legacy/manila-tempest-dsvm-postgres-generic-singlebackend/post.yaml
    required-projects:
      - openstack/devstack-gate
      - openstack/manila
      - openstack/manila-image-elements
      - openstack/manila-tempest-plugin
      - openstack/python-manilaclient
      - openstack/tempest

- job:
    name: manila-tempest-dsvm-postgres-zfsonlinux
    parent: legacy-manila-tempest-dsvm-base
    run: playbooks/legacy/manila-tempest-dsvm-postgres-zfsonlinux/run.yaml
    post-run: playbooks/legacy/manila-tempest-dsvm-postgres-zfsonlinux/post.yaml
    required-projects:
      - openstack/devstack-gate
      - openstack/manila
      - openstack/manila-image-elements
      - openstack/manila-tempest-plugin
      - openstack/python-manilaclient
      - openstack/tempest

- job:
    name: manila-tempest-dsvm-scenario
    parent: legacy-manila-tempest-dsvm-base
    run: playbooks/legacy/manila-tempest-dsvm-scenario/run.yaml
    post-run: playbooks/legacy/manila-tempest-dsvm-scenario/post.yaml
    required-projects:
      - openstack/devstack-gate
      - openstack/manila
      - openstack/manila-image-elements
      - openstack/manila-tempest-plugin
      - openstack/python-manilaclient
      - openstack/tempest

- job:
    name: manila-tempest-minimal-dsvm-cephfs-native-centos-7
    parent: legacy-manila-tempest-dsvm-base
    run: playbooks/legacy/manila-tempest-minimal-dsvm-cephfs-native-centos-7/run.yaml
    post-run: playbooks/legacy/manila-tempest-minimal-dsvm-cephfs-native-centos-7/post.yaml
    nodeset: legacy-centos-7
    required-projects:
      - openstack/devstack-gate
      - openstack/devstack-plugin-ceph
      - openstack/manila
      - openstack/manila-tempest-plugin
      - openstack/python-manilaclient
      - openstack/tempest

- job:
    name: manila-tempest-minimal-dsvm-cephfs-nfs-centos-7
    parent: legacy-manila-tempest-dsvm-base
    run: playbooks/legacy/manila-tempest-minimal-dsvm-cephfs-nfs-centos-7/run.yaml
    post-run: playbooks/legacy/manila-tempest-minimal-dsvm-cephfs-nfs-centos-7/post.yaml
    nodeset: legacy-centos-7
    required-projects:
      - openstack/devstack-gate
      - openstack/devstack-plugin-ceph
      - openstack/manila
      - openstack/manila-tempest-plugin
      - openstack/python-manilaclient
      - openstack/tempest

- job:
    name: manila-tempest-minimal-dsvm-dummy
    parent: legacy-manila-tempest-dsvm-base
    run: playbooks/legacy/manila-tempest-minimal-dsvm-dummy/run.yaml
    post-run: playbooks/legacy/manila-tempest-minimal-dsvm-dummy/post.yaml
    required-projects:
      - openstack/devstack-gate
      - openstack/manila
      - openstack/manila-tempest-plugin
      - openstack/python-manilaclient
      - openstack/tempest

- job:
    name: manila-tempest-minimal-dsvm-lvm-centos-7
    parent: legacy-manila-tempest-dsvm-base
    run: playbooks/legacy/manila-tempest-minimal-dsvm-lvm-centos-7/run.yaml
    post-run: playbooks/legacy/manila-tempest-minimal-dsvm-lvm-centos-7/post.yaml
    nodeset: legacy-centos-7
    required-projects:
      - openstack/devstack-gate
      - openstack/manila
      - openstack/manila-tempest-plugin
      - openstack/neutron-dynamic-routing
      - openstack/python-manilaclient
      - openstack/tempest

- job:
    name: manila-tempest-minimal-py35-dsvm-cephfs-native-centos-7
    parent: legacy-manila-tempest-dsvm-base
    run: playbooks/legacy/manila-tempest-minimal-py35-dsvm-cephfs-native-centos-7/run.yaml
    post-run: playbooks/legacy/manila-tempest-minimal-py35-dsvm-cephfs-native-centos-7/post.yaml
    nodeset: legacy-centos-7
    required-projects:
      - openstack/devstack-gate
      - openstack/devstack-plugin-ceph
      - openstack/manila
      - openstack/manila-tempest-plugin
      - openstack/python-manilaclient
      - openstack/tempest

- job:
    name: manila-tempest-minimal-py35-dsvm-cephfs-nfs-centos-7
    parent: legacy-manila-tempest-dsvm-base
    run: playbooks/legacy/manila-tempest-minimal-py35-dsvm-cephfs-nfs-centos-7/run.yaml
    post-run: playbooks/legacy/manila-tempest-minimal-py35-dsvm-cephfs-nfs-centos-7/post.yaml
    nodeset: legacy-centos-7
    required-projects:
      - openstack/devstack-gate
      - openstack/devstack-plugin-ceph
      - openstack/manila
      - openstack/manila-tempest-plugin
      - openstack/python-manilaclient
      - openstack/tempest

- job:
    name: manila-tox-genconfig
    parent: openstack-tox
    description: |
      Run tests for manila project.

      Uses tox with the ``genconfig`` environment.
    vars:
      tox_envlist: genconfig

- job:
    name: rally-dsvm-manila-multibackend
    parent: legacy-dsvm-base
    run: playbooks/legacy/rally-dsvm-manila-multibackend/run.yaml
    post-run: playbooks/legacy/rally-dsvm-manila-multibackend/post.yaml
    timeout: 4200
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^install-guide/.*$
      - ^manila/hacking/.*$
      - ^manila/tests/.*$
      - ^releasenotes/.*$
      - ^tools/.*$
      - ^tox.ini$
    required-projects:
      - openstack/devstack-gate
      - openstack/manila
      - openstack/python-manilaclient
      - openstack/rally

- job:
    name: rally-dsvm-manila-multibackend-no-ss
    parent: legacy-dsvm-base
    run: playbooks/legacy/rally-dsvm-manila-multibackend-no-ss/run.yaml
    post-run: playbooks/legacy/rally-dsvm-manila-multibackend-no-ss/post.yaml
    timeout: 4200
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^install-guide/.*$
      - ^manila/hacking/.*$
      - ^manila/tests/.*$
      - ^releasenotes/.*$
      - ^tools/.*$
      - ^tox.ini$
    required-projects:
      - openstack/devstack-gate
      - openstack/manila
      - openstack/python-manilaclient
      - openstack/rally
