
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-29T12:33:44-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "784b9d1b0db5b30f6bf30313ff624c308e575404",
 "version": "0.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
