[tool.poetry]
name = "move-migrations"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
prompt = "^0.4.1"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.scripts]
move-migrations = 'move_migrations:move_migrations.main'
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

