- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - check-requirements
      - publish-openstack-sphinx-docs
      - release-notes-jobs
      - deploy-guide-jobs
    check:
      jobs:
        - kolla-ansible-centos-source
        - kolla-ansible-ubuntu-source
        - kolla-ansible-oraclelinux-source
        - kolla-ansible-ubuntu-source-ceph
        - kolla-ansible-centos-source-ceph
        - kolla-ansible-oraclelinux-source-ceph
        - kolla-ansible-ubuntu-source-zun:
            files: ^ansible\/roles\/zun\/.*
- nodeset:
    name: kolla-ansible-centos
    nodes:
      - name: primary
        label: centos-7

- nodeset:
    name: kolla-ansible-xenial
    nodes:
      - name: primary
        label: ubuntu-xenial

- nodeset:
    name: kolla-ansible-xenial-multi
    nodes:
      - name: primary
        label: ubuntu-xenial
      - name: secondary1
        label: ubuntu-xenial
      - name: secondary2
        label: ubuntu-xenial
    groups:
      - name: switch
        nodes:
          - primary
      - name: peers
        nodes:
          - secondary1
          - secondary2

- nodeset:
    name: kolla-ansible-centos-multi
    nodes:
      - name: primary
        label: centos-7
      - name: secondary1
        label: centos-7
      - name: secondary2
        label: centos-7
    groups:
      - name: switch
        nodes:
          - primary
      - name: peers
        nodes:
          - secondary1
          - secondary2

- job:
    name: kolla-ansible-base
    pre-run: tests/pre.yml
    run: tests/run.yml
    post-run: tests/post.yml
    attempts: 1
    timeout: 7200
    required-projects:
      - openstack/kolla
      - openstack/requirements
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*
    vars:
      scenario: aio

- job:
    name: kolla-ansible-centos-source
    parent: kolla-ansible-base
    nodeset: kolla-ansible-centos
    voting: false
    vars:
      base_distro: centos
      install_type: source

- job:
    name: kolla-ansible-ubuntu-source
    parent: kolla-ansible-base
    nodeset: kolla-ansible-xenial
    voting: false
    vars:
      base_distro: ubuntu
      install_type: source

- job:
    name: kolla-ansible-oraclelinux-source
    parent: kolla-ansible-base
    nodeset: kolla-ansible-centos
    voting: false
    vars:
      base_distro: oraclelinux
      install_type: source

- job:
    name: kolla-ansible-centos-binary
    parent: kolla-ansible-base
    nodeset: kolla-ansible-centos
    voting: false
    vars:
      base_distro: centos
      install_type: binary

- job:
    name: kolla-ansible-ubuntu-binary
    parent: kolla-ansible-base
    nodeset: kolla-ansible-xenial
    voting: false
    vars:
      base_distro: ubuntu
      install_type: binary

- job:
    name: kolla-ansible-oraclelinux-binary
    parent: kolla-ansible-base
    nodeset: kolla-ansible-centos
    voting: false
    vars:
      base_distro: oraclelinux
      install_type: binary

- job:
    name: kolla-ansible-ubuntu-source-ceph
    parent: kolla-ansible-base
    nodeset: kolla-ansible-xenial-multi
    voting: false
    vars:
      base_distro: ubuntu
      install_type: source
      scenario: ceph

- job:
    name: kolla-ansible-centos-source-ceph
    parent: kolla-ansible-base
    nodeset: kolla-ansible-centos-multi
    voting: false
    vars:
      base_distro: centos
      install_type: source
      scenario: ceph

- job:
    name: kolla-ansible-oraclelinux-source-ceph
    parent: kolla-ansible-base
    nodeset: kolla-ansible-centos-multi
    voting: false
    vars:
      base_distro: oraclelinux
      install_type: source
      scenario: ceph

- job:
    name: kolla-ansible-ubuntu-source-zun
    parent: kolla-ansible-base
    nodeset: kolla-ansible-xenial
    voting: false
    vars:
      base_distro: ubuntu
      install_type: source
      scenario: zun
