
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-30T20:17:33+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b2731658dd776a17ff519d769344f8b35aa46eaf",
 "version": "0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
