from setuptools import setup
setup(
    name='mc_klotski',
    version='0.0.6',
    author='魔扣少儿编程_Hugn',
    author_email='wang1183478375@outlook.com',
    url ='https://www.coding4fun.com.cn/',
    install_requires=['pygame>=1.9.4'
                      ],
    data_files=[('',['mc_klotski.py']),
                ('Images',['Images/1.png',
                           'Images/2.png',
                           'Images/3.png',
                           'Images/4.png',
                           'Images/5.png',
                           'Images/6.png',
                           'Images/7.png',
                           'Images/8.png',
                           'Images/9.png',
                           'Images/10.png']),
                ('Bgm',['Bgm/bgm1.mp3',
                        'Bgm/bgm2.mp3',
                        'Bgm/bgm3.mp3',
                        'Bgm/bgm4.mp3',
                        'Bgm/bgm5.mp3',
                        'Bgm/bgm6.mp3',
                        'Bgm/bgm7.mp3',
                        'Bgm/bgm8.mp3']),
                ('ogg',['ogg/1.ogg',
                        'ogg/2.ogg',
                        'ogg/3.ogg',
                        'ogg/4.ogg',
                        'ogg/5.ogg',
                        'ogg/6.ogg'])
                ],
    packages = ['Images','Bgm','ogg'],
    include_package_data = True, 
    zip_safe=False,
    )