#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='pycodestyle_magic',
      version='0.5',
      description='magic function that checks a cell for pep8 compliance, using pycodestyle',
      author='Mattijn van Hoek',
      author_email='mattijn@gmail.com',
      url='https://github.com/mattijn/pycodestyle_magic',
      py_modules=['pycodestyle_magic'],
     )
