from pangeamt_nlp.multilingual_ressource.bilingual import Bilingual
from pangeamt_nlp.multilingual_ressource.tmx.tmx import Tmx
from pangeamt_nlp.multilingual_ressource.af.af import Af
from pangeamt_nlp.multilingual_ressource.af.af_reader import AfReader
from pangeamt_nlp.multilingual_ressource.tmx.tmx_reader_bilingual import TmxReaderBilingualText