---
- name: create ingress networks
  gather_facts: False
  hosts: first_hive
  vars:
    ansible_python_interpreter: "{{ hive_home_dir }}/docker/bin/python"

  tasks:
  - name: create network
    docker_network:
      name: "{{ item }}"
      driver: "overlay"
      dirver_options: "{{ hostvars[item].hive_driver_options | default(omit) }}"
    loop: "{{ groups['networks'] }}"
    register: create_network_result
    until: not create_network_result.failed
    retries: 5

