
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-31T19:02:03+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "02ec2086e8e22e06cdb66f64267d38e931ef7579",
 "version": "0.9.8.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
