# coding: utf-8

"""
    

        # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import rebrickable.api
from rebrickable.api.models.array_of_part_lists import ArrayOfPartLists  # noqa: E501
from rebrickable.api.rest import ApiException


class TestArrayOfPartLists(unittest.TestCase):
    """ArrayOfPartLists unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArrayOfPartLists(self):
        """Test ArrayOfPartLists"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rebrickable.api.models.array_of_part_lists.ArrayOfPartLists()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
