
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-31T12:14:19+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5c317592b1ab488c98c52eb68f6eda8c627ecf16",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
