version: build-{build}-{branch}

environment:
  matrix:
    # https://www.appveyor.com/docs/installed-software#python lists available
    # versions
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python38"

init:
  - "echo %PYTHON%"

install:
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python --version
  - pip install tox
  - choco install bzr
  - "set PATH=C:\\Program Files (x86)\\Bazaar;%PATH%"
  - bzr --version
  - git --version
  - svn --version
  - hg --version

build: off

test_script:
  - tox -e py
