# THIS FILE IS GENERATED BY DALIUGE'S SETUP.PY
# DO NOT MODIFY BY HAND
version = '0.6.3'
git_version = '1685bd4941c2264af0520e5a6915dc3a9967bb6a'
full_version = '0.6.3'
is_release = True

if not is_release:
    version = full_version