[tool.black]
line-length = 88
target-version = ["py36"]

[tool.poetry]
name = "nnql"
version = "0.1.0"
description = "graph instrumentation"

license = "Apache-2.0"

authors = [
    "uchuhimo <uchuhimo@outlook.com>"
]

readme = "README.md"

repository = "https://github.com/uchuhimo/nnql"
homepage = "https://github.com/uchuhimo/nnql"

keywords = []

[tool.poetry.dependencies]
python = ">= 3.6"
six = "*"
click = "*"
typing-extensions = "*"
dataclasses = { version = "*", python = "< 3.7" }
typing = { version = "*", python = "< 3.7" }
contextvars = { version = "*", python = "< 3.7" }
tensorflow = { version = "1.14.0", optional = true }
torch = { version = "1.3.0", optional = true }
torchvision = { version = "0.4.1", optional = true }

[tool.poetry.dev-dependencies]
flake8 = "*"
black = { version = "*", allows-prereleases = true }
isort = "*"
mypy = "*"
pre-commit = "*"
pytest = "*"
ipython = "*"

[tool.poetry.extras]
tensorflow = ["tensorflow"]
pytorch = ["torch", "torchvision"]
all = ["tensorflow", "torch", "torchvision"]

[tool.poetry.scripts]
nnql = "nnql.cli:nnql"
