# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

try:
    from .alert_configuration_py3 import AlertConfiguration
    from .data_drift_dto_py3 import DataDriftDto
    from .data_drift_query_dto_py3 import DataDriftQueryDto
    from .paginated_result_data_drift_dto_py3 import PaginatedResultDataDriftDto
    from .data_drift_run_dto_py3 import DataDriftRunDto
    from .paginated_result_data_drift_run_dto_py3 import PaginatedResultDataDriftRunDto
    from .telemetry_metrics_dto_py3 import TelemetryMetricsDto
    from .feature_profiles_py3 import FeatureProfiles
    from .data_profile_dto_py3 import DataProfileDto
    from .meta_api_version_response_py3 import MetaApiVersionResponse
    from .inner_error_response_py3 import InnerErrorResponse
    from .debug_info_response_py3 import DebugInfoResponse
    from .root_error_py3 import RootError
    from .error_response_py3 import ErrorResponse
except (SyntaxError, ImportError):
    from .alert_configuration import AlertConfiguration
    from .data_drift_dto import DataDriftDto
    from .data_drift_query_dto import DataDriftQueryDto
    from .paginated_result_data_drift_dto import PaginatedResultDataDriftDto
    from .data_drift_run_dto import DataDriftRunDto
    from .paginated_result_data_drift_run_dto import PaginatedResultDataDriftRunDto
    from .telemetry_metrics_dto import TelemetryMetricsDto
    from .feature_profiles import FeatureProfiles
    from .data_profile_dto import DataProfileDto
    from .meta_api_version_response import MetaApiVersionResponse
    from .inner_error_response import InnerErrorResponse
    from .debug_info_response import DebugInfoResponse
    from .root_error import RootError
    from .error_response import ErrorResponse

__all__ = [
    'AlertConfiguration',
    'DataDriftDto',
    'DataDriftQueryDto',
    'PaginatedResultDataDriftDto',
    'DataDriftRunDto',
    'PaginatedResultDataDriftRunDto',
    'TelemetryMetricsDto',
    'FeatureProfiles',
    'DataProfileDto',
    'MetaApiVersionResponse',
    'InnerErrorResponse',
    'DebugInfoResponse',
    'RootError',
    'ErrorResponse',
]
