repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: trailing-whitespace
    exclude: src/exoplanet/theano_ops/lib/vendor
  - id: end-of-file-fixer
    exclude: src/exoplanet/theano_ops/lib/vendor
  - id: debug-statements
    exclude: src/exoplanet/theano_ops/lib/vendor

- repo: https://github.com/asottile/seed-isort-config
  rev: v1.9.2
  hooks:
  - id: seed-isort-config
    args: [--application-directories=src]

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.20
  hooks:
  - id: isort
    args: []

- repo: https://github.com/psf/black
  rev: 19.3b0
  hooks:
  - id: black
    language_version: python3.6

- repo: https://github.com/dfm/black_nbconvert
  rev: stable
  hooks:
  - id: black_nbconvert
