# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from vda.grpc import agent_pb2 as vda_dot_grpc_dot_agent__pb2


class AgentStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Configure = channel.unary_unary(
        '/Agent/Configure',
        request_serializer=vda_dot_grpc_dot_agent__pb2.ConfRequest.SerializeToString,
        response_deserializer=vda_dot_grpc_dot_agent__pb2.ConfReply.FromString,
        )


class AgentServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Configure(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AgentServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Configure': grpc.unary_unary_rpc_method_handler(
          servicer.Configure,
          request_deserializer=vda_dot_grpc_dot_agent__pb2.ConfRequest.FromString,
          response_serializer=vda_dot_grpc_dot_agent__pb2.ConfReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Agent', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
