sudo: false

language: python


python:
    - 3.6
    - 3.7


env:
    - version=minimum  
    - version=latest



before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"


install:
  - if [[ $version == minimum ]]; then pip install matplotlib==3.0.3 numpy==1.16.2 scipy==1.3.0 pandas==0.24.2 lmfit==0.9.13 PyQt5==5.13.0 codecov ;fi
  - if [[ $version == latest ]]; then pip install -r requirements.txt codecov ; fi
  - python setup.py install
  - pip list


script:
  - cd pysprint/tests
  - python test_loading.py
  - python test_edit.py
  - python test_evaluate.py
  - python test_generator.py
  - python test_evaluate_nolmfit.py
  - coverage run -a test_loading.py
  - coverage run -a test_edit.py
  - coverage run -a test_evaluate.py
  - coverage run -a test_generator.py
  - coverage run -a test_evaluate_nolmfit.py

after_success:
  - codecov