stages:
  - test
  - coverage
  - package
  - deploy

.tests:
    stage: test
    before_script:
      - pip install --ignore-installed -U -q -e .[complete]
      - pip freeze
    script:
      - pyflakes src/
      - pytest
      - if [[ -x $(command -v black) ]]; then black --check --diff --verbose src tests setup.py; fi

.security_checks:
    stage: test
    before_script:
      - pip install --ignore-installed -U -q -e .[complete]
      - pip freeze
    script:
      - bandit -r itkdb

tests_python2:
  image: python:2
  extends: .tests

tests_python3:
  image: python:3
  extends: .tests

security_python2:
  image: python:2
  extends: .security_checks

security_python3:
  image: python:3
  extends: .security_checks

package:
  image: python:3.7-alpine
  stage: package
  before_script:
    - apk --no-cache add git
    - python -m pip install pep517 --user
  script:
    - python -m pep517.build --source --binary --out-dir dist/ .
  artifacts:
    paths:
      - dist/

.deploy:
  image: python:3.7-alpine
  stage: deploy
  dependencies: [package]
  only:
    refs:
      - master
  variables:
    TWINE_USERNAME: __token__
  before_script:
    - pip install twine
  script:
    - twine upload dist/*whl dist/*gz

deploy_staging:
  extends: .deploy
  except:
    - tags
  variables:
    TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
    TWINE_PASSWORD: $TESTPYPI_TOKEN

deploy_production:
  extends: .deploy
  only:
    - tags
  variables:
    TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
    TWINE_PASSWORD: $PYPI_TOKEN
