[tool.poetry]
name = "mannequin"
version = "0.0.1"
description = "Neural network implementation in pure python"
authors = ["Kracekumar <me@kracekumar>"]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.17"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
