# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-15 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_circle', '0002_circle_urlid'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='creationDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
