
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-19T22:07:09+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c2701533c90c6a6a555c63f5aa0591ba3e367e8",
 "version": "0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
