__uname__ = 'sqjobstf'
__long_name__ = 'Simple Queue Jobs TF Fork'
__version__ = '0.8.5'
__author__ = 'Saul Diez-Guerra'
__email__ = 'saul@thinkful.com'
__url__ = 'http://github.com/Thinkful/sqjobs'
__license__ = 'BSD'
