DATABASE_VERSION = "1.0.7"

NODE_MODULE_TYPE = 1
NODE_FUNCDEF_TYPE = 2
NODE_CLASSDEF_TYPE = 3
NODE_CLASS_PROPERTY = 4
NODE_RETURN_TYPE = 5
NODE_IMPORT_TYPE = 6
NODE_FROMIMPORT_TYPE = 7
NODE_ASSIGN_TYPE = 8
NODE_ARG_TYPE = 9
NODE_BUILTIN_IMPORT_TYPE = 10
NODE_MAIN_FUNCTION_TYPE = 11
NODE_UNKNOWN_TYPE = 1001


ASSIGN_TYPE_UNKNOWN = -1
ASSIGN_TYPE_INT = 0
ASSIGN_TYPE_STR = 1
ASSIGN_TYPE_MODULE = 2
ASSIGN_TYPE_LIST =3
ASSIGN_TYPE_TUPLE = 4
ASSIGN_TYPE_DICT = 5
ASSIGN_TYPE_OBJECT = 6
ASSIGN_TYPE_FLOAT = 7
ASSIGN_TYPE_LONG = 8
ASSIGN_TYPE_BOOL = 9
ASSIGN_TYPE_SET = 10
ASSIGN_TYPE_OBJECT = 11
ASSIGN_FILE_OBJECT = 12



DATABASE_FILE = "version"
UPDATE_FILE = 'update_time'

ISO_8601_DATE_FORMAT = "%Y-%m-%d"
ISO_8601_TIME_FORMAT = "%H:%M:%S"
ISO_8601_DATETIME_FORMAT = "%s %s" %(ISO_8601_DATE_FORMAT,
                                     ISO_8601_TIME_FORMAT)
                                     

MEMBERS_FILE_EXTENSION = ".$members"
MEMBERLIST_FILE_EXTENSION = ".$memberlist"