# Autogenerated by Astropy-affiliated package hoki's setup.py on 2019-10-29 23:32:12 UTC
from __future__ import unicode_literals
import datetime

version = "1.2.0-beta"
githash = "392e7519ae24e8c0db2fdb491501a89df8534590"


major = 1
minor = 2
bugfix = 0

version_info = (major, minor, bugfix)

release = True
timestamp = datetime.datetime(2019, 10, 29, 23, 32, 12)
debug = False

astropy_helpers_version = "3.2.1"
