[tool.poetry]
name = "attrs-marshmallow"
version = "0.2.1"
description = ""
authors = ["Igor Stuzhuk (KoHcoJlb) <fujitsuigor@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
marshmallow = ">=3.0"
typing_inspect = "^0.4.0"
attrs = "^19.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
