# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'galacteek/ui/files.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FileManagerForm(object):
    def setupUi(self, FileManagerForm):
        FileManagerForm.setObjectName("FileManagerForm")
        FileManagerForm.resize(817, 349)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(FileManagerForm)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fsControlLayout = QtWidgets.QHBoxLayout()
        self.fsControlLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.fsControlLayout.setObjectName("fsControlLayout")
        self.helpButton = QtWidgets.QPushButton(FileManagerForm)
        self.helpButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/share/icons/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpButton.setIcon(icon)
        self.helpButton.setObjectName("helpButton")
        self.fsControlLayout.addWidget(self.helpButton)
        self.fsOptionsButton = QtWidgets.QToolButton(FileManagerForm)
        self.fsOptionsButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/share/icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fsOptionsButton.setIcon(icon1)
        self.fsOptionsButton.setObjectName("fsOptionsButton")
        self.fsControlLayout.addWidget(self.fsOptionsButton)
        self.pathSelector = QtWidgets.QComboBox(FileManagerForm)
        self.pathSelector.setObjectName("pathSelector")
        self.fsControlLayout.addWidget(self.pathSelector)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.fsControlLayout.addItem(spacerItem)
        self.addFileButton = QtWidgets.QToolButton(FileManagerForm)
        self.addFileButton.setMaximumSize(QtCore.QSize(28, 28))
        self.addFileButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/share/icons/add-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addFileButton.setIcon(icon2)
        self.addFileButton.setIconSize(QtCore.QSize(24, 24))
        self.addFileButton.setObjectName("addFileButton")
        self.fsControlLayout.addWidget(self.addFileButton)
        self.addDirectoryButton = QtWidgets.QToolButton(FileManagerForm)
        self.addDirectoryButton.setMaximumSize(QtCore.QSize(28, 28))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/share/icons/add-folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addDirectoryButton.setIcon(icon3)
        self.addDirectoryButton.setIconSize(QtCore.QSize(24, 24))
        self.addDirectoryButton.setObjectName("addDirectoryButton")
        self.fsControlLayout.addWidget(self.addDirectoryButton)
        self.refreshButton = QtWidgets.QToolButton(FileManagerForm)
        self.refreshButton.setMaximumSize(QtCore.QSize(28, 28))
        self.refreshButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/share/icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshButton.setIcon(icon4)
        self.refreshButton.setIconSize(QtCore.QSize(24, 24))
        self.refreshButton.setObjectName("refreshButton")
        self.fsControlLayout.addWidget(self.refreshButton)
        self.horizontalLayout.addLayout(self.fsControlLayout)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.fileManagerButton = QtWidgets.QToolButton(FileManagerForm)
        self.fileManagerButton.setMaximumSize(QtCore.QSize(28, 28))
        self.fileManagerButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/share/icons/file-manager.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileManagerButton.setIcon(icon5)
        self.fileManagerButton.setIconSize(QtCore.QSize(24, 24))
        self.fileManagerButton.setObjectName("fileManagerButton")
        self.horizontalLayout.addWidget(self.fileManagerButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.offlineButton = QtWidgets.QToolButton(FileManagerForm)
        self.offlineButton.setText("")
        self.offlineButton.setObjectName("offlineButton")
        self.horizontalLayout.addWidget(self.offlineButton)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.collapseAll = QtWidgets.QPushButton(FileManagerForm)
        self.collapseAll.setObjectName("collapseAll")
        self.horizontalLayout_3.addWidget(self.collapseAll)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.label_2 = QtWidgets.QLabel(FileManagerForm)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.comboIconSize = QtWidgets.QComboBox(FileManagerForm)
        self.comboIconSize.setObjectName("comboIconSize")
        self.horizontalLayout_3.addWidget(self.comboIconSize)
        self.label = QtWidgets.QLabel(FileManagerForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.searchFiles = QtWidgets.QLineEdit(FileManagerForm)
        self.searchFiles.setMaximumSize(QtCore.QSize(200, 16777215))
        self.searchFiles.setObjectName("searchFiles")
        self.horizontalLayout_3.addWidget(self.searchFiles)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.hLayoutFilesView = QtWidgets.QHBoxLayout()
        self.hLayoutFilesView.setObjectName("hLayoutFilesView")
        self.treeFiles = QtWidgets.QTreeView(FileManagerForm)
        self.treeFiles.setObjectName("treeFiles")
        self.treeFiles.header().setCascadingSectionResizes(False)
        self.treeFiles.header().setDefaultSectionSize(200)
        self.treeFiles.header().setStretchLastSection(True)
        self.hLayoutFilesView.addWidget(self.treeFiles)
        self.hLayoutBrowser = QtWidgets.QHBoxLayout()
        self.hLayoutBrowser.setObjectName("hLayoutBrowser")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.localFileManagerSwitch = QtWidgets.QToolButton(FileManagerForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localFileManagerSwitch.sizePolicy().hasHeightForWidth())
        self.localFileManagerSwitch.setSizePolicy(sizePolicy)
        self.localFileManagerSwitch.setMaximumSize(QtCore.QSize(128, 16777215))
        self.localFileManagerSwitch.setText("")
        self.localFileManagerSwitch.setIcon(icon5)
        self.localFileManagerSwitch.setIconSize(QtCore.QSize(24, 24))
        self.localFileManagerSwitch.setObjectName("localFileManagerSwitch")
        self.verticalLayout_4.addWidget(self.localFileManagerSwitch)
        self.hLayoutBrowser.addLayout(self.verticalLayout_4)
        self.hLayoutFilesView.addLayout(self.hLayoutBrowser)
        self.verticalLayout.addLayout(self.hLayoutFilesView)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.statusLabel = QtWidgets.QLabel(FileManagerForm)
        self.statusLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout_2.addWidget(self.statusLabel)

        self.retranslateUi(FileManagerForm)

    def retranslateUi(self, FileManagerForm):
        _translate = QtCore.QCoreApplication.translate
        FileManagerForm.setWindowTitle(_translate("FileManagerForm", "Form"))
        self.addFileButton.setToolTip(_translate("FileManagerForm", "<html><head/><body><p>Add Files</p></body></html>"))
        self.addDirectoryButton.setToolTip(_translate("FileManagerForm", "<html><head/><body><p>Add directory</p></body></html>"))
        self.addDirectoryButton.setText(_translate("FileManagerForm", "Add directory"))
        self.refreshButton.setToolTip(_translate("FileManagerForm", "<html><head/><body><p>Refresh</p></body></html>"))
        self.fileManagerButton.setToolTip(_translate("FileManagerForm", "<html><head/><body><p>Open local file manager</p></body></html>"))
        self.collapseAll.setText(_translate("FileManagerForm", "Collapse all"))
        self.label_2.setText(_translate("FileManagerForm", "Icon size"))
        self.label.setText(_translate("FileManagerForm", "Search"))
        self.localFileManagerSwitch.setToolTip(_translate("FileManagerForm", "<html><head/><body><p>Open local file manager</p></body></html>"))

from . import galacteek_rc
