[tool.poetry]
name = "urlspy"
version = "0.0.1"
description = "[WIP] Get information about URLs"
authors = ["Keshab Paudel"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "^3.6"
aiodns = "^2.0"
ruia = "^0.6.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-asyncio = "^0.10.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
