metadata: {}
implementation_config:
  reader_config:
    read_data:
      class: CsvReader
      destinations:
      - encode_and_split
      filename: data/tennis.csv  
  pipeline_config:
    encode_and_split:
      class: EncodeTrainTestSplit
      destinations:
      - decision_tree_model
      - write_encoder
      is_training: true
      seed: 42
      target_variable: play
      training_fraction: 0.65
  model_config:
    decision_tree_model:
      class: SklearnClassifierModel
      cv_folds: 3
      destinations:
      - write_output
      - write_model
      grid_search_scoring: roc_auc
      mode: train
      model_parameters:
        min_samples_leaf:
        - 1
        - 3
        - 5
        min_samples_split:
        - 2
        - 5
        - 10
        random_state:
        - 42
      sklearn_classifier_name: tree.DecisionTreeClassifier
  writer_config:
    write_encoder:
      class: DillWriter
      dir: cache
      filename: hello_world_encoder.dill
      key: transformer_sequence
    write_model:
      class: DillWriter
      dir: cache
      filename: hello_world_model.dill
      key: model
    write_output:
      class: CsvWriter
      dir: cache
      filename: hello_world_predictions.csv
      key: predictions
