
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-31T17:09:08+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "6000c54ab2a839a97cdf2548ef86750a10e00bbf",
 "version": "0.9.8.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
