
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-28T14:27:24-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c5c102df69048f5bfb26022684265fe5ea25672b",
 "version": "0.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
