
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-29T17:15:44-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ce2348b533d8e9c6671c1f9869170e9014b6042b",
 "version": "0.0.33"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
