[tool.poetry]
name = "autoscreenshot"
version = "0.1.1"
description = ""
authors = ["Zija <zija1504@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pyscreenshot = "^0.5.1"
pillow = "^6.2.1"
requests = "^2.22.0"
pyperclip = "^1.7.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
flake8 = "^3.7.8"
setuptools = "^41.5.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
