
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-29T12:41:36+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2b4e780bd4323d6c150483bef253e3e0e7b7025e",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
