
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "943f4934317f7fade786e91bf48417f431b4d79e",
 "version": "2195"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
