[tool.poetry]
name = "mako-render"
version = "0.1.0"
description = ""
authors = ["gfreezy <gfreezy@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
mako = "^1.1"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
black = {version = "^18.3-alpha.0", allows-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
mako_render = 'mako_render:main'
