INSERT INTO `order_event_types` (`id`, `text`, `description`) 
VALUES 
('1','Fill request received','When a fill request is recieved by our backend'),
('2','Order created','When an API Request gets converted into an order'),
('3','Request filled','When a fill request is processed by our pharmacy'),
('4','Shipping label created','When a shipping label is created'),
('5','Outbound scanned','When a shipment is scanned leaving our facility'),
('6','Order cancelled','When an order is cancelled by the Pharmacy'),
('7','Order updated','When an order is updated'),
('8','Shipping price calculated','When an order\'s shipment price is calculated'),
('9','Prescription matched','When an order is matched to a prescription'),
('10','Order reset','When an order has its status reset'),
('11','Order completed','When an order is cleared/completed'),
('12','Rx number updated','When an order\'s linked Rx number is manually changed'),
('13','Unverified Rx','When an Rx hasn\'t been verified by a pharmacist'),
('15','Order too old','When an order is too old'),
('16','Can\'t ship to state','When a shipping address is out of range'),
('17','No shipment found','When an order does not have an associated shipping URL'),
('18','Shipping label printed','When a shipping label is successfully printed'),
('19','Order viewed','When an order is viewed on the dashboard'),
('20','Patient check-in completed','When a patient check-in for an order is completed by a Pharmacist'),
('21','Patient check-in requested','When an order requiring a patient check-in is created'),
('23','Prescription filled','When an order\'s prescription is filled'),
('24','Force used','When an order\'s label is force printed'),
('25','Survey approved','When an order\'s DUR review is completed'),
('26','Medication Rejected','A medication in the batch order was rejected'),
('27','Survey viewed','When a user views a URAC survey'),
('28','Prescription verified','When a pharmacist verifies/completes a prescription')
