--- 
addons: 
  apt: 
    packages: 
      - libbz2-dev
      - libcurl4-openssl-dev
      - libssl-dev
compiler: 
  - gcc
  - clang
dist: xenial
language: python
matrix: 
  include: 
    - 
      os: linux
      python: 2.7
      install: 
        - pip install . -r requirements.txt
    - 
      os: linux
      python: 3.5
      install: 
        - pip install . -r requirements.txt
    - 
      os: linux
      python: 3.6.5
      install: 
        - pip install . -r requirements.txt
    - 
      os: linux
      python: 3.7.3
      install: 
        - pip install . -r requirements.txt
    - 
      language: generic
      os: osx
      python: 2.7
      before_install:
        - sudo pip install setuptools
      install: 
        - sudo pip install . -r requirements.txt
    - 
      language: generic
      os: osx
      python: 3.5
      before_install:
        - sudo pip install setuptools
      install: 
        - sudo pip install . -r requirements.txt
    - 
      language: generic
      os: osx
      python: 3.6.5
      before_install:
        - sudo pip install setuptools
      install: 
        - sudo pip install . -r requirements.txt
    - 
      language: generic
      os: osx
      python: 3.7.3
      before_install:
        - sudo pip install setuptools
      install: 
        - sudo pip install . -r requirements.txt 
os: linux
script: 
  - flake8 --config .flake8
  - pytest --cov=.
  - codecov
