[tool.poetry]
name = "sc-stream"
version = "0.1.1"
description = ""
authors = ["仇昌栋 <qiuchangdong@cmhi.chinamobile.com>"]

[tool.poetry.dependencies]
python = "^3.6"
kafka-python = "^1.4"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
