
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-23T18:41:00-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "bb17e4dff616587bd6864c7b0bdc15db38ee4b0c",
 "version": "0.8.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
