
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-20T17:40:15-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "dcee8cc5f542ea1ca433b9d69f3a5cd2eac96fea",
 "version": "v0.0.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
