
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-24T11:05:14-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "be1b2e7400ae6a597c4b51aae36a7fb467f309bb",
 "version": "v0.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
