# Autogenerated by Astropy-affiliated package glowing_waffles's setup.py on 2019-10-19 12:44:58 UTC
from __future__ import unicode_literals
import datetime

version = "0.0.18"
githash = "f9ba80f631fac9ac991126e02ba872f52c747adc"


major = 0
minor = 0
bugfix = 18

version_info = (major, minor, bugfix)

release = True
timestamp = datetime.datetime(2019, 10, 19, 12, 44, 58)
debug = False

astropy_helpers_version = "1.1.1"
