# Version file autogenerated by the build process
version = '0.7.7rc5'
build = '454'
vcs_info = 'Git SHA1 6e0df79d committed on 2019-10-16'

if __name__ == '__main__':
    print('KSCONF_VERSION="0.7.7rc5"\nKSCONF_BUILD="454"\nKSCONF_VCS_INFO="Git SHA1 6e0df79d committed on 2019-10-16"')
