#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['cleverdiff']

package_data = \
{'': ['*'], 'cleverdiff': ['test_data/*']}

entry_points = \
{'console_scripts': ['cleverdiff = cleverdiff.cleverdiff:main']}

setup(name='cleverdiff',
      version='0.3',
      description='A tool for describing multiple differences in files.',
      author='Andrew Bennett',
      author_email='chudleigh.rivet@gmail.com',
      url='https://github.com/andrewcbennett/cleverdiff',
      packages=packages,
      package_data=package_data,
      entry_points=entry_points,
      python_requires='>=3.6',
     )
