[tool.poetry]
name = "supersql"
version = "2019.0.2"
description = "Thin wrapper on top of SQL that enables you write SQL code in python easily"
authors = ["Raymond Ortserga <codesage@live.com>"]
license = "MIT"

packages = [
    {include = "src"}
]

readme = 'README.md'

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
supersql = 'supersql:main'
