
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-19T12:38:22+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "a4bd9564f7ce921e689c7e8953511e1419dcf905",
 "version": "0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
