from ..codenames import (
    account_manager,
    administration,
    auditor,
    celery_manager,
    clinic,
    data_manager,
    data_query,
    everyone,
    export,
    lab,
    lab_view,
    pharmacy,
    pii,
    pii_view,
    site_data_manager,
)
from .group_names import (
    ACCOUNT_MANAGER,
    ADMINISTRATION,
    PII_VIEW,
    EVERYONE,
    AUDITOR,
    CELERY_MANAGER,
    CLINIC,
    LAB,
    LAB_VIEW,
    PHARMACY,
    PII,
    EXPORT,
    DATA_MANAGER,
    DATA_QUERY,
    SITE_DATA_MANAGER,
)

DEFAULT_CODENAMES = {
    ACCOUNT_MANAGER: account_manager,
    ADMINISTRATION: administration,
    AUDITOR: auditor,
    CELERY_MANAGER: celery_manager,
    CLINIC: clinic,
    DATA_MANAGER: data_manager,
    SITE_DATA_MANAGER: site_data_manager,
    DATA_QUERY: data_query,
    EVERYONE: everyone,
    EXPORT: export,
    LAB: lab,
    LAB_VIEW: lab_view,
    PHARMACY: pharmacy,
    PII: pii,
    PII_VIEW: pii_view,
}
