
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-29T10:57:03-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "7299c650596a3c283dc5b743baca34e82fe0687e",
 "version": "0.0.30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
