- hosts: all
  roles:
    - role: bindep
    - role: install-kubernetes
      docker_version: 18.06.1~ce~3-0~ubuntu

  tasks:
    - name: Ensure nodepool services directories
      file:
        path: '{{ ansible_user_dir }}/work/{{ item }}'
        state: directory
      with_items:
        - logs/nodepool
        - etc
        - images
