# Generated by Django 2.2.6 on 2019-10-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyaudit', '0002_auto_20191010_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='crudevent',
            name='change_reason',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
