# coding: utf-8

"""
    GeoAPI

    Geospatial API for TAPIS  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import geoapi_client
from geoapi_client.models.feature import Feature  # noqa: E501
from geoapi_client.rest import ApiException


class TestFeature(unittest.TestCase):
    """Feature unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFeature(self):
        """Test Feature"""
        # FIXME: construct object with mandatory attributes with example values
        # model = geoapi_client.models.feature.Feature()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
