# coding: utf-8

"""
    GeoAPI

    Geospatial API for TAPIS  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import geoapi_client
from geoapi_client.models.point_cloud import PointCloud  # noqa: E501
from geoapi_client.rest import ApiException


class TestPointCloud(unittest.TestCase):
    """PointCloud unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPointCloud(self):
        """Test PointCloud"""
        # FIXME: construct object with mandatory attributes with example values
        # model = geoapi_client.models.point_cloud.PointCloud()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
