"""
This file is automatically generated by the autosetup package.
Please edit the marked area only. Other areas will be
overwritten when autosetup is reruns.
"""

from setuptools import setup

params = dict(
    name='pipemaker',
    description='pipemaker',
    version='0.0.4',
    url='https://gitlab.com/simonm3/pipemaker',
    install_requires=['PyYAML', 'dill', 'fs', 'graphviz', 'ipython', 'ipywidgets', 'matplotlib', 'multiprocess', 'numpy', 'pandas',
                      'pika', 'pipreqs', 'pydal', 'pyfs', 'pyftpdlib', 'pytest', 'python_json_logger', "pywin32;platform_system=='Windows'", 'requests'],
    packages=['pipemaker', 'pipemaker.filesystem', 'pipemaker.master', 'pipemaker.queues', 'pipemaker.utils',
              'pipemaker.worker', 'pipemaker.filesystem.filedrivers', 'pipemaker.master.flask', '_archive.celery'],
    data_files=[],
    py_modules=['Untitled'],
    include_package_data=True,
    scripts=[])

########## EDIT BELOW THIS LINE ONLY ##########

# where is this?
params["install_requires"].append("fs1-s3fs")
params["packages"] = [x for x in params["packages"]
                      if not x.startswith("_archive")]
# not needed
params["data_files"] = []
########## EDIT ABOVE THIS LINE ONLY ##########

setup(**params)
