# coding: utf-8

"""
    Key Manager API

    API Responsible for management the tools' keys   # noqa: E501

    OpenAPI spec version: v1
    Contact: paulossjunior@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import key_management_client
from key_management_client.api.entities_api import EntitiesApi  # noqa: E501
from key_management_client.rest import ApiException


class TestEntitiesApi(unittest.TestCase):
    """EntitiesApi unit test stubs"""

    def setUp(self):
        self.api = key_management_client.api.entities_api.EntitiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_entities_create(self):
        """Test case for entities_create

        """
        pass

    def test_entities_delete(self):
        """Test case for entities_delete

        """
        pass

    def test_entities_list(self):
        """Test case for entities_list

        """
        pass

    def test_entities_partial_update(self):
        """Test case for entities_partial_update

        """
        pass

    def test_entities_read(self):
        """Test case for entities_read

        """
        pass

    def test_entities_read_0(self):
        """Test case for entities_read_0

        """
        pass

    def test_entities_tool_id_list(self):
        """Test case for entities_tool_id_list

        """
        pass

    def test_entities_update(self):
        """Test case for entities_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
