# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import importlib
gopkg_dot_in_dot_bblfsh_dot_sdk_dot_v2_dot_protocol_dot_generated__pb2 = importlib.import_module("bblfsh.gopkg.in.bblfsh.sdk.v2.protocol.generated_pb2")


class DriverStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Parse = channel.unary_unary(
        '/gopkg.in.bblfsh.sdk.v2.protocol.Driver/Parse',
        request_serializer=gopkg_dot_in_dot_bblfsh_dot_sdk_dot_v2_dot_protocol_dot_generated__pb2.ParseRequest.SerializeToString,
        response_deserializer=gopkg_dot_in_dot_bblfsh_dot_sdk_dot_v2_dot_protocol_dot_generated__pb2.ParseResponse.FromString,
        )


class DriverServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Parse(self, request, context):
    """Parse returns an UAST for a given source file.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DriverServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Parse': grpc.unary_unary_rpc_method_handler(
          servicer.Parse,
          request_deserializer=gopkg_dot_in_dot_bblfsh_dot_sdk_dot_v2_dot_protocol_dot_generated__pb2.ParseRequest.FromString,
          response_serializer=gopkg_dot_in_dot_bblfsh_dot_sdk_dot_v2_dot_protocol_dot_generated__pb2.ParseResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gopkg.in.bblfsh.sdk.v2.protocol.Driver', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class DriverHostStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ServerVersion = channel.unary_unary(
        '/gopkg.in.bblfsh.sdk.v2.protocol.DriverHost/ServerVersion',
        request_serializer=gopkg_dot_in_dot_bblfsh_dot_sdk_dot_v2_dot_protocol_dot_generated__pb2.VersionRequest.SerializeToString,
        response_deserializer=gopkg_dot_in_dot_bblfsh_dot_sdk_dot_v2_dot_protocol_dot_generated__pb2.VersionResponse.FromString,
        )
    self.SupportedLanguages = channel.unary_unary(
        '/gopkg.in.bblfsh.sdk.v2.protocol.DriverHost/SupportedLanguages',
        request_serializer=gopkg_dot_in_dot_bblfsh_dot_sdk_dot_v2_dot_protocol_dot_generated__pb2.SupportedLanguagesRequest.SerializeToString,
        response_deserializer=gopkg_dot_in_dot_bblfsh_dot_sdk_dot_v2_dot_protocol_dot_generated__pb2.SupportedLanguagesResponse.FromString,
        )


class DriverHostServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ServerVersion(self, request, context):
    """ServerVersion returns version information of this server.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SupportedLanguages(self, request, context):
    """SupportedLanguages returns a list of languages supported by the server.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DriverHostServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ServerVersion': grpc.unary_unary_rpc_method_handler(
          servicer.ServerVersion,
          request_deserializer=gopkg_dot_in_dot_bblfsh_dot_sdk_dot_v2_dot_protocol_dot_generated__pb2.VersionRequest.FromString,
          response_serializer=gopkg_dot_in_dot_bblfsh_dot_sdk_dot_v2_dot_protocol_dot_generated__pb2.VersionResponse.SerializeToString,
      ),
      'SupportedLanguages': grpc.unary_unary_rpc_method_handler(
          servicer.SupportedLanguages,
          request_deserializer=gopkg_dot_in_dot_bblfsh_dot_sdk_dot_v2_dot_protocol_dot_generated__pb2.SupportedLanguagesRequest.FromString,
          response_serializer=gopkg_dot_in_dot_bblfsh_dot_sdk_dot_v2_dot_protocol_dot_generated__pb2.SupportedLanguagesResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gopkg.in.bblfsh.sdk.v2.protocol.DriverHost', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
