language: python
sudo: false

matrix:
    include:
        # pyXX-plone_sunburst,pyXX-plone_barceloneta
        - python: "2.7"
          env: TOXENV=py27-plone_org_4
        - python: "2.7"
          env: TOXENV=py27-plone_org_5
        - python: "2.7"
          env: TOXENV=py27-plone_classic
        - python: "3.4"
          env: TOXENV=py34-plone_org_4
        - python: "3.4"
          env: TOXENV=py34-plone_org_5
        - python: "3.4"
          env: TOXENV=py34-plone_classic
        - python: "3.5"
          env: TOXENV=py35-plone_org_4
        - python: "3.5"
          env: TOXENV=py35-plone_org_5
        - python: "3.5"
          env: TOXENV=py35-plone_classic
        - python: "3.6"
          env: TOXENV=py36-plone_org_4
        - python: "3.6"
          env: TOXENV=py36-plone_org_5
        - python: "3.6"
          env: TOXENV=py36-plone_classic
        - python: "pypy"
          env: TOXENV=pypy-plone_org_4
        - python: "pypy"
          env: TOXENV=pypy-plone_org_5
        - python: "pypy"
          env: TOXENV=pypy-plone_classic
        - python: "3.7"
          env: TOXENV=py36-plone_org_4
        - python: "3.7"
          env: TOXENV=py36-plone_org_5
        - python: "3.7"
          env: TOXENV=py36-plone_classic
        - python: "3.8"
          env: TOXENV=py36-plone_org_4
        - python: "3.8"
          env: TOXENV=py36-plone_org_5
        - python: "3.8"
          env: TOXENV=py36-plone_classic
        - python: "3.6"
          env: TOXENV=isort
        - python: "3.6"
          env: TOXENV=flake8

install:
    - travis_retry pip install tox

script:
    - travis_retry tox

cache:
    directory:
        - $HOME/.cache/pip

notifications:
    email: false
