
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-16T16:55:47+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f8a8d7fe70e7b2b0659a34b0b2120ac6ba68417e",
 "version": "0.10.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
