strictness: medium
autodetect: yes

ignore-paths:
  - utils/
  - tools/
  - samples/
  - tests/
  - thug/ThugAPI/IThugAPI.py
  - thug/ThugAPI/__init__.py
  - thug/Plugins/IPlugin.py
  - thug/ActiveX/modules/MSXML2DOMDocument.py
  - thug/ActiveX/modules/XMLDOMParseError.py

pylint:
  disable:
    - too-many-arguments
    - too-many-locals
    - too-many-statements
    - too-many-branches
    - unused-argument
    - protected-access
    - unnecessary-lambda
    - line-too-long
    - cyclic-import

pyflakes:
  disable:
    - F841

pep8:
  disable:
    # E116 - Unexpected indent for comment
    - E116
    # E501 - Line too long
    - E501

mccabe:
  disable:
    - MC0001
