[tool.poetry]
name = "dbx-deploy"
version = "0.6.2"
description = "Databrics Deployment Tool"
readme = "README.md"
repository = "https://github.com/DataSentics/dbx-deploy"

license = "MIT"

authors = [
    "Jiri Koutny <jiri.koutny@datasentics.com>"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

include = ["*.yaml", "*.tpl"]

packages = [
    { include = "DbxDeploy", from = "src" },
]

[tool.poetry.scripts]
"dbx-deploy" = "DbxDeploy.DeployerCommand:DeployerCommand.run"
"dbx-deploy-submit-job" = "DbxDeploy.DeployerJobSubmitterCommand:DeployerJobSubmitterCommand.run"
"dbx-deploy-with-cleanup" = "DbxDeploy.DeployWithCleanupCommand:DeployWithCleanupCommand.run"
"dbx-delete-all-jobs" = "DbxDeploy.JobsDeleterCommand:JobsDeleterCommand.run"

[tool.poetry.dependencies]
colorlog = "~4"
databricks-api = "^0.3"
dbx-notebook-exporter = "^0.2"
injecta = "^0.4"
nbconvert = "~5"
pygit2 = "0.*"
python = "~3.5.6"
python-box = "~3"
PyYAML = "~5"

[tool.poetry.dev-dependencies]
pylint = "~2"
pytest = "~5"
