
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-27T16:18:36+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ca6cb2b41f0016f592f1a4345e1f018d0d6db194",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
