
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-14T16:48:18-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "bbfb79b2f9e89453edd10c722a5e294b0372e099",
 "version": "0.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
