
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-25T18:13:35+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "35216fe8f07c9b9c7913f30b5c9dc391d1cbf80a",
 "version": "1.2.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
