- name: Tobiko Tests Main
  hosts: undercloud
  gather_facts: yes
  any_errors_fatal: yes
  vars:
    python_ver: python{{ansible_python.version.major}}
  tasks:

        - name: Install Tobiko
          include_tasks: tasks/install.yml

        - name: Set up environment configurations
          include_tasks: tasks/configure.yml

        - name: Run Tobiko
          include_tasks: tasks/run.yml
          when:
              - test.tests is defined

        - name: Collect Tobiko logs and reports
          include_tasks: tasks/report.yml
