sudo: false
language: python
stages:
- test
- name: deploy
  if: repo = gabrielcnr/pytest-datadir AND tag IS present

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install --upgrade setuptools pip
  - pip install tox-travis
script: tox

jobs:
  include:
    - stage: deploy
      python: '3.7'
      env:
      install: pip install -U setuptools setuptools_scm
      script: skip
      deploy:
        provider: pypi
        user: nicoddemus
        distributions: sdist bdist_wheel
        skip_upload_docs: true
        password:
          secure: JS4D2aJ2WsihjWbkm1/Y1BFEDWO+G+1Zba//jGROkRpO/gBaTC+f9pNUw8J6EhH5313D0cewIwQ20LF98630h7WlfYtQtqyXFqsCt5kXkvfaLel7K3qAzCwBuNIOYhR2tH4OuNyn8ORwmi1yJWSYfxv4Lf8VVatuw8PO3RKKAtv2u8kcWI2+J2dkJ/uDHWIcXxjoKFMgEcI49BxXhfVJa6jLG0E4ayegbALNWfoDS2zi8/pF5FKdMGAZYS9bsqxINAPezWpaRYu7gwrXPbOvY8vsUGBQ5CRXFUL7J+3bbCcLnYoJamiO7OhjGQDCrr0F5UIrdmgNXlTw2YaIT3h0mBjRWwXi07Ujq7MFOGJD+AqNUPFDI0FG0H1yEAofz0nTchjXPhALJj4hFnYnY3er7IlD5nVvArm+iX5cKv9IO1SqJ7nZnSKAhKgG9bF7GDXBWOPcqujv38+e3plhO2bdeoQvqW+5CZTIxJQI0WaZsb6xv6zvdzFDIdEFEbe228Zf+5sQdCj979p54Amu5YIXLE7SFBLqY7p6iUqj6bGNhXjxIvxU0d6fGNEmVY7mIL+/BqFUkCbGAFOkUux/LWSw6bFjh0VjxwV0GwTTlETgXF3Gwz+MqzrREQTm8yGZQ/x7XamhNu9eg00IaCERlGm+Mw3KMPcVYKORJ238eRmHDQw=
        on:
          tags: true
          repo: gabrielcnr/pytest-datadir
