
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-25T14:05:02-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "dfa44b4f18ce63e53919f98f0e3b73687ad51155",
 "version": "4.14.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
