[tool.poetry]
name = "sanic-to-json"
version = "0.1.9"
description = "Create Postman JSON API documentation files from Sanic."
homepage = "https://github.com/caheredia/sanic-to-json"
repository = "https://github.com/caheredia/sanic-to-json"
authors = ["Cristian Heredia <cheredia@kountable.com>"]
license = "MIT"
readme = "README.md"



[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
black = {version = "^18.3-alpha.0",allows-prereleases = true}
pytest = "^5.0"
tox = "^3.13"
sanic = "19.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
