- job:
    name: swiftclient-swift-functional
    parent: swift-dsvm-functional
    description: |
      Run swift's functional tests with python-swiftclient
      installed from source instead as package from PyPI.
    # Ensure that we install python-swiftclient from git and
    # do not install from pypi. This is needed since the parent
    # job sets zuul_work_dir to the swift directory and uses tox
    # for installation.
    required-projects:
      - opendev.org/openstack/python-swiftclient

- job:
    name: swiftclient-functional
    parent: swift-dsvm-functional
    description: |
      Run functional tests of python-swiftclient with
      python-swiftclient installed from source instead as package from
      PyPI.
    required-projects:
      - opendev.org/openstack/python-swiftclient
    vars:
      # Override value from parent job to use swiftclient tests
      zuul_work_dir: "{{ zuul.projects['opendev.org/openstack/python-swiftclient'].src_dir }}"

- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-sphinx-docs
      - check-requirements
      - openstack-pypy-jobs-nonvoting
      - lib-forward-testing
      - release-notes-jobs
    check:
      jobs:
        - swiftclient-swift-functional
        - swiftclient-functional
        - openstack-tox-lower-constraints
        - openstack-tox-py36:
            voting: false
    gate:
      jobs:
        - swiftclient-swift-functional
        - swiftclient-functional
        - openstack-tox-lower-constraints
    post:
      jobs:
        - openstack-tox-cover
