# Generated by Django 2.2.1 on 2019-05-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("django_vox", "0007_from_address")]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="last updated"),
        )
    ]
