
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-15T13:06:55+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "03fd44cbc9ef2cdb3776c9ad880a512801560246",
 "version": "0.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
