[tool.poetry]
name = "nightcore"
version = "1.1.0"
description = "Intuitive CLI and API for modifying the speed/pitch of audio"
authors = ["SeparateRecords <me@rob.ac>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/SeparateRecords/nightcore"
keywords = [
    "nightcore",
    "cli",
    "audio",
    "pitch",
    "speed"
]
classifiers = [
    "Topic :: Multimedia :: Sound/Audio",
    "Topic :: Multimedia :: Sound/Audio :: Conversion",
    "Environment :: Console",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: 3.7",
    "License :: OSI Approved :: MIT License",
    "Development Status :: 5 - Production/Stable"
]

[tool.poetry.dependencies]
python = "^3.7"
pydub = "^0.23.1"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
nightcore = "nightcore.cli:cli"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

