[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "logsensei"
author = "Aditya Kelvianto Sidharta"
author-email = "aditya.sdrt@gmail.com"
home-page = "https://github.com/AdityaSidharta/logsensei"
classifiers = ["License :: OSI Approved :: MIT License"]
requires = ['loguru', 'scikit-learn', 'numpy']
