# Generated by Django 2.0.5 on 2018-06-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_rating', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ToxicityRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('name', models.TextField()),
                ('chat_id', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('rating', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
