# Generated by Django 2.0.5 on 2018-06-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebaka_toxic', '0003_toxicityrating_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toxicityrating',
            name='username',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
