# coding: utf-8

"""
    

        # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import rebrickable.api
from rebrickable.api.models.build import Build  # noqa: E501
from rebrickable.api.rest import ApiException


class TestBuild(unittest.TestCase):
    """Build unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBuild(self):
        """Test Build"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rebrickable.api.models.build.Build()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
