dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: ZYXYfbnZVRM9GYuK/I019rIZ2ah2ABamN2GH5ID/F2gyC0r7iFejotxYTc8YlgkVyfxuFMIXaCbc3BUhWOY4gk1S7u1ZSHhUE34YvmToImaS3/OvALKHxUSrDjZDoZoF4f780fJLhJR5Hjj6Nr5UcYLjzwTLF+kk649BjMfAyzXsT65FcX8dhoQkZBMCfqHIUyedFHmryeF1cq81xWhly8Q1mj4KT2dy6Xvf1sDkzCP74PPHPxjy0edTaW5QK7aDaVofzfLQb+oGiCo5IWRHWUHXHoBGK7aa+8axpaucrNu8zRs+XsPAnPem4ZioMSNds0yrzVWqv8npNV3SWLtWhdnrjOwHagTxOTJtyoIDnsvHKqgFIhqRlEluzFan0IDcz0GiwV9/rmgwNS4WtaLIhb8pRp6RmRdmJtwBhl+3z9FwbIlupOoMWtdSZfLjuWGXIrtud7zZVA1zS1DQn8c8SYFr7gMR1doFfP7Ex8HdAXw49omtbHWLCLyWUbtoBNzTz5bQbXfhiDyj8EFeYmp6UaAU4XKZ3Qu1+2A6eheVCkEft9ViuhpRw8Lfr95/oO0MnX10b6KkXwhi16RLQwJTqGwxhuKgHiQgSW2cprbltv/cjQGO9TAX7Ic/UIPR0/0YxqyrmOt+3ss9hk7Pz9kkX291pl7GVA1M4SgbMCNlUos=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_lsm303_accel.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace
  examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-lsm303-accel --library_location
  .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
