[tool.poetry]
name = "pytus"
version = "0.1.0"
description = "yet another tus (resumable file upload protocol) client in python"
authors = ["yatmanov <yatmanov@megaputer.ru>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.5"
requests = "^2.22"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
