# Generated by Django 2.0.5 on 2018-06-29 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_auto_20180515_1544'),
        ('telebaka_toxic', '0002_auto_20180628_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='toxicityrating',
            name='bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.TelegramBot'),
        ),
    ]
