[tool.poetry]
name = "flask-eventdispatcher"
version = "0.2.0"
description = ""
authors = ["Anton Ruhlov <antonruhlov@gmail.com>"]
packages = [
    { include = "flask_eventdispatcher.py", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.6"
blinker = "^1.4"
flask = "^1.1"

[tool.poetry.dev-dependencies]
pytest = "^5.1"

[tool.isort]
combine_as_imports = true
default_section = "THIRDPARTY"
include_trailing_comma = true
known_first_party = "flask_eventdispatcher"
known_standard_library = "typing,dataclasses,contextvars"
line_length = 88
multi_line_output = 3
not_skip = "__init__.py"
force_grid_wrap = 0
use_parentheses = true


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
