
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-21T15:13:27+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f61abd2804ee681c5a5b2e845f05dc8c1bdec7e3",
 "version": "0.3.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
