language: python
dist: xenial
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy
  - pypy3
install:
  - pip install pytest coverage coverage-python-version coveralls flake8
  - pip install -e .
script:
  - coverage run -m pytest
  - flake8 *.py
  - coverage report -m $([[ $TRAVIS_PYTHON_VERSION != pypy3 ]] && echo --fail-under=100)
after_success:
  - coveralls
notifications:
  email: false
cache: pip
