- project:
    templates:
      - build-openstack-docs-pti
      - docs-on-readthedocs
      - openstack-cover-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - publish-to-pypi
      - build-release-notes-jobs-python3
    vars:
        rtd_webhook_id: '84947'
    check:
      jobs:
        - openstack-tox-pylint
        - tobiko-devstack-functional
        - tobiko-devstack-scenario
        - tobiko-devstack-scenario-centos-7
        - tobiko-devstack-scenario-centos-7-queens
        - tobiko-devstack-scenario-centos-7-rocky
        - tobiko-devstack-scenario-centos-7-stein
        - tobiko-devstack-scenario-fedora-latest
        - tobiko-devstack-scenario-ubuntu-bionic
        - tobiko-devstack-octavia-functional
        - tobiko-devstack-octavia-scenario
        - tobiko-devstack-octavia-scenario-ubuntu-bionic
    gate:
      jobs:
        - openstack-tox-pylint
