
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-16T12:46:04+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d4e7a28cd7cf083dc420f2b8106b2dfa4e30bd88",
 "version": "5.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
