# coding: utf-8

"""
    Known Pose API

    Define and retrieve (accurate) semantic poses in a 2D environment.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: Kai.Waelti@dfki.de
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import known_pose_client
from known_pose_client.models.accurate_pose import AccuratePose  # noqa: E501
from known_pose_client.rest import ApiException


class TestAccuratePose(unittest.TestCase):
    """AccuratePose unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccuratePose(self):
        """Test AccuratePose"""
        # FIXME: construct object with mandatory attributes with example values
        # model = known_pose_client.models.accurate_pose.AccuratePose()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
