
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-15T14:24:31+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "fd03e8d65341f15f27b3d40de1bcb1bd030ba4ab",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
