language: python
dist: xenial
sudo: false
python:
  - "3.6"
  - "3.7"
  - "pypy3"
install:
  - pip install -e .[testing]
script:
  - pylint --rcfile=.pylintrc slash_step tests setup.py
  - pytest tests
jobs:
  include:
    - stage: deploy
      python: 3.7
      install: pip install twine
      script:
        - python setup.py sdist bdist_wheel
        - twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
      if: tag IS present
