#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['rfi']

package_data = \
{'': ['*']}

entry_points = \
{'console_scripts': ['rfi = rfi:main']}

setup(name='roll-for-initiative',
      version='0.0.7',
      description='A CLI initiative tracker in the works [NOT USABLE YET].',
      author='William Quelho Ferreira',
      author_email='wqferr@gmail.com',
      url='https://github.com/wqferr/rfi',
      packages=packages,
      package_data=package_data,
      entry_points=entry_points,
     )
