# Generated by Django 2.2.6 on 2019-10-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ambition_ae", "0041_auto_20191017_0204")]

    operations = [
        migrations.AlterField(
            model_name="aeinitial",
            name="sae_reason_old",
            field=models.CharField(
                default="QUESTION_RETIRED",
                help_text="If subject deceased, submit a Death Report",
                max_length=50,
                verbose_name='If "Yes", reason for SAE:',
            ),
        ),
        migrations.AlterField(
            model_name="historicalaeinitial",
            name="sae_reason_old",
            field=models.CharField(
                default="QUESTION_RETIRED",
                help_text="If subject deceased, submit a Death Report",
                max_length=50,
                verbose_name='If "Yes", reason for SAE:',
            ),
        ),
    ]
