
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-18T15:15:03+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0befa91eb4ece2023e7aa889bc2b11d8330d2197",
 "version": "0.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
