
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-14T12:26:11-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "5016b6b73d9e5adc8e1d51daca21d91cec52fbf2",
 "version": "0.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
