version: 1
formatters:
  simple:
    format: '%(asctime)s:%(name)s:%(funcName)s:%(lineno)d - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  # file:
  #   class: logging.FileHandler
  #   filename: beadpull.log
  #   mode: 'w'
  #   level: WARN
  #   formatter: simple
loggers:
  pyvisa:
    level: ERROR
    handlers: [console]
    propagate: no
  serial:
    level: ERROR
    handlers: [console]
    propagate: no
  uirobot:
    level: WARN
    handlers: [console]
    propagate: no
  gpib:
    level: ERROR
    handlers: [console]
    propagate: no
  agilent8753et:
    level: WARN
    handlers: [console]
    propagate: no
  QtPy:
    level: WARN
    handlers: [console]
    propagate: no

root:
  level: WARN
  handlers: [console]
