
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-25T15:31:07+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5473f56e654595aacfa2e4a2ae35c9b4f45fb076",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
