[tool.poetry]
name = "siva-poetry"
version = "0.1.1"
description = ""
authors = ["siva <sivakon@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pendulum = "^2.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
