# Generated by Django 2.0.7 on 2019-07-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=255, null=True)),
                ('client_service_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('main_user', models.CharField(blank=True, default='main_name', max_length=255, null=True)),
                ('user_id', models.IntegerField()),
                ('platform_id', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=500)),
                ('refresh_token', models.CharField(max_length=500)),
                ('expires', models.IntegerField(default=0)),
                ('expires_in', models.IntegerField(default=0)),
                ('token_type', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
    ]
