
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-22T16:31:08-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "17aa9806049626980a8fc6206085920c81bb02b7",
 "version": "0+untagged.592.g17aa980"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
