
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-25T12:37:52-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "132c98facba25f66e71238fe9860117bdcc18e52",
 "version": "0.15.1rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
