- project:
    templates:
      - neutron-tempest-plugin-jobs-queens
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-sphinx-docs
      - periodic-stable-jobs
      - check-requirements
      - integrated-gate
      - integrated-gate-py35
      - release-notes-jobs
    check:
      jobs:
        - neutron-functional
        - neutron-fullstack
        - neutron-rally-neutron
        - neutron-tempest-dvr
        - neutron-tempest-linuxbridge
        - neutron-grenade-multinode
        - neutron-grenade-dvr-multinode
        - neutron-tempest-multinode-full
        - neutron-tempest-dvr-ha-multinode-full
        - neutron-tempest-ovsfw
        - neutron-grenade
        - openstack-tox-cover
        - tempest-full:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^neutron/locale/.*$
              - ^neutron/tests/unit/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tools/.*$
              - ^tox.ini$
    gate:
      jobs:
        - neutron-functional
        - neutron-tempest-dvr
        - neutron-tempest-linuxbridge
        - neutron-grenade-multinode
        - neutron-grenade-dvr-multinode
        - neutron-grenade

        - openstack-tox-cover
    post:
      jobs:
        - openstack-tox-cover
    experimental:
      jobs:
        - legacy-grenade-dsvm-neutron-linuxbridge-multinode:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^neutron/locale/.*$
              - ^neutron/tests/unit/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tools/.*$
              - ^tox.ini$
        - legacy-grenade-dsvm-neutron-forward:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^neutron/locale/.*$
              - ^neutron/tests/unit/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tools/.*$
              - ^tox.ini$
        - legacy-neutron-dsvm-api-pecan
        - legacy-tempest-dsvm-neutron-pg-full:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^neutron/locale/.*$
              - ^neutron/tests/unit/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tools/.*$
              - ^tox.ini$
        - legacy-tempest-dsvm-neutron-pecan:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^neutron/locale/.*$
              - ^neutron/tests/unit/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tools/.*$
              - ^tox.ini$
        - legacy-tempest-dsvm-neutron-full-centos-7:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^neutron/locale/.*$
              - ^neutron/tests/unit/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tools/.*$
              - ^tox.ini$
        - legacy-tempest-dsvm-neutron-dvr-multinode-full:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^neutron/locale/.*$
              - ^neutron/tests/unit/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tools/.*$
              - ^tox.ini$
        - legacy-tempest-dsvm-neutron-with-ryu-master:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^neutron/locale/.*$
              - ^neutron/tests/unit/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tools/.*$
              - ^tox.ini$

- job:
    name: neutron-functional
    parent: legacy-dsvm-base
    run: playbooks/legacy/neutron-functional/run.yaml
    post-run: playbooks/legacy/neutron-functional/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/neutron
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^neutron/locale/.*$
      - ^releasenotes/.*$

- job:
    name: neutron-fullstack
    parent: legacy-dsvm-base
    run: playbooks/legacy/neutron-fullstack/run.yaml
    post-run: playbooks/legacy/neutron-fullstack/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/neutron
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^neutron/locale/.*$
      - ^releasenotes/.*$
    voting: false

- job:
    name: neutron-rally-neutron
    parent: legacy-dsvm-base
    run: playbooks/legacy/neutron-rally-neutron/run.yaml
    post-run: playbooks/legacy/neutron-rally-neutron/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/aodh
      - openstack/ceilometer
      - openstack/diskimage-builder
      - openstack/ironic
      - openstack/magnum
      - openstack/networking-bgpvpn
      - openstack/neutron
      - openstack/neutron-fwaas
      - openstack/neutron-lbaas
      - openstack/neutron-vpnaas
      - openstack/octavia
      - openstack/panko
      - openstack/python-magnumclient
      - openstack/python-senlinclient
      - openstack/python-watcherclient
      - openstack/python-zaqarclient
      - {name: openstack/rally, override-checkout: 0.12.1}
      - openstack/senlin
      - openstack/tripleo-image-elements
      - openstack/watcher
      - openstack/zaqar-ui
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^neutron/locale/.*$
      - ^neutron/tests/unit/.*$
      - ^releasenotes/.*$
      - ^tools/.*$
      - ^tox.ini$

- job:
    name: neutron-tempest-dvr
    parent: legacy-dsvm-base
    run: playbooks/legacy/neutron-tempest-dvr/run.yaml
    post-run: playbooks/legacy/neutron-tempest-dvr/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/neutron
      - openstack/tempest
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^doc/.*$
      - ^neutron/locale/.*$
      - ^neutron/tests/unit/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^tools/.*$
      - ^tox.ini$

- job:
    name: neutron-tempest-linuxbridge
    parent: legacy-dsvm-base
    run: playbooks/legacy/neutron-tempest-linuxbridge/run.yaml
    post-run: playbooks/legacy/neutron-tempest-linuxbridge/post.yaml
    timeout: 8400
    required-projects:
      - openstack/devstack-gate
      - openstack/neutron
      - openstack/tempest
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^doc/.*$
      - ^neutron/locale/.*$
      - ^neutron/tests/.*$
      - ^neutron/tests/unit/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^tools/.*$
      - ^tox.ini$

- job:
    name: neutron-grenade-multinode
    parent: legacy-dsvm-base-multinode
    run: playbooks/legacy/neutron-grenade-multinode/run.yaml
    post-run: playbooks/legacy/neutron-grenade-multinode/post.yaml
    timeout: 10800
    required-projects:
      - openstack/grenade
      - openstack/devstack-gate
      - openstack/neutron
    nodeset: ubuntu-xenial-2-node
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^doc/.*$
      - ^neutron/locale/.*$
      - ^neutron/tests/unit/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^tools/.*$
      - ^tox.ini$

- job:
    name: neutron-grenade-dvr-multinode
    parent: legacy-dsvm-base-multinode
    run: playbooks/legacy/neutron-grenade-dvr-multinode/run.yaml
    post-run: playbooks/legacy/neutron-grenade-dvr-multinode/post.yaml
    timeout: 7500
    required-projects:
      - openstack/grenade
      - openstack/devstack-gate
      - openstack/neutron
    nodeset: ubuntu-xenial-2-node
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^doc/.*$
      - ^neutron/locale/.*$
      - ^neutron/tests/unit/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^tools/.*$
      - ^tox.ini$

- job:
    name: neutron-tempest-multinode-full
    parent: legacy-dsvm-base-multinode
    run: playbooks/legacy/neutron-tempest-multinode-full/run.yaml
    post-run: playbooks/legacy/neutron-tempest-multinode-full/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/neutron
      - openstack/tempest
    nodeset: ubuntu-xenial-2-node
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^doc/.*$
      - ^neutron/locale/.*$
      - ^neutron/tests/unit/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^tools/.*$
      - ^tox.ini$
    voting: false

- job:
    name: neutron-tempest-dvr-ha-multinode-full
    parent: legacy-dsvm-base-multinode
    run: playbooks/legacy/neutron-tempest-dvr-ha-multinode-full/run.yaml
    post-run: playbooks/legacy/neutron-tempest-dvr-ha-multinode-full/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/neutron
      - openstack/tempest
    nodeset: ubuntu-xenial-3-node
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^doc/.*$
      - ^neutron/locale/.*$
      - ^neutron/tests/unit/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^tools/.*$
      - ^tox.ini$
    voting: false

- job:
    name: neutron-tempest-ovsfw
    parent: legacy-dsvm-base
    run: playbooks/legacy/neutron-tempest-ovsfw/run.yaml
    post-run: playbooks/legacy/neutron-tempest-ovsfw/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/neutron
      - openstack/tempest
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^doc/.*$
      - ^neutron/locale/.*$
      - ^neutron/tests/unit/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^tools/.*$
      - ^tox.ini$
    voting: false

- job:
    name: neutron-grenade
    parent: legacy-dsvm-base
    run: playbooks/legacy/neutron-grenade/run.yaml
    post-run: playbooks/legacy/neutron-grenade/post.yaml
    timeout: 10800
    required-projects:
      - openstack/grenade
      - openstack/devstack-gate
      - openstack/neutron
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^doc/.*$
      - ^neutron/locale/.*$
      - ^neutron/tests/unit/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^tools/.*$
      - ^tox.ini$
