# coding: utf-8

"""
    

        # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class SetListSetItem(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'include_spares': 'bool',
        'quantity': 'int',
        'set_num': 'str'
    }

    attribute_map = {
        'include_spares': 'include_spares',
        'quantity': 'quantity',
        'set_num': 'set_num'
    }

    def __init__(self, include_spares=None, quantity=None, set_num=None):  # noqa: E501
        """SetListSetItem - a model defined in OpenAPI"""  # noqa: E501

        self._include_spares = None
        self._quantity = None
        self._set_num = None
        self.discriminator = None

        if include_spares is not None:
            self.include_spares = include_spares
        if quantity is not None:
            self.quantity = quantity
        if set_num is not None:
            self.set_num = set_num

    @property
    def include_spares(self):
        """Gets the include_spares of this SetListSetItem.  # noqa: E501


        :return: The include_spares of this SetListSetItem.  # noqa: E501
        :rtype: bool
        """
        return self._include_spares

    @include_spares.setter
    def include_spares(self, include_spares):
        """Sets the include_spares of this SetListSetItem.


        :param include_spares: The include_spares of this SetListSetItem.  # noqa: E501
        :type: bool
        """

        self._include_spares = include_spares

    @property
    def quantity(self):
        """Gets the quantity of this SetListSetItem.  # noqa: E501


        :return: The quantity of this SetListSetItem.  # noqa: E501
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this SetListSetItem.


        :param quantity: The quantity of this SetListSetItem.  # noqa: E501
        :type: int
        """

        self._quantity = quantity

    @property
    def set_num(self):
        """Gets the set_num of this SetListSetItem.  # noqa: E501


        :return: The set_num of this SetListSetItem.  # noqa: E501
        :rtype: str
        """
        return self._set_num

    @set_num.setter
    def set_num(self, set_num):
        """Sets the set_num of this SetListSetItem.


        :param set_num: The set_num of this SetListSetItem.  # noqa: E501
        :type: str
        """

        self._set_num = set_num

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SetListSetItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
