# coding: utf-8

# flake8: noqa

"""
    Quetzal API

    Quetzal: an API to manage data files and their associated metadata.  # noqa: E501

    OpenAPI spec version: 0.5.0
    Contact: support@quetz.al
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "0.5.0"

# import apis into sdk package
from quetzal.openapi_client.api.authentication_api import AuthenticationApi
from quetzal.openapi_client.api.data_api import DataApi
from quetzal.openapi_client.api.public_api import PublicApi
from quetzal.openapi_client.api.query_api import QueryApi
from quetzal.openapi_client.api.workspace_api import WorkspaceApi

# import ApiClient
from quetzal.openapi_client.api_client import ApiClient
from quetzal.openapi_client.configuration import Configuration
# import models into sdk package
from quetzal.openapi_client.models.base_metadata import BaseMetadata
from quetzal.openapi_client.models.error import Error
from quetzal.openapi_client.models.file_contents import FileContents
from quetzal.openapi_client.models.metadata_by_family import MetadataByFamily
from quetzal.openapi_client.models.paginated_files import PaginatedFiles
from quetzal.openapi_client.models.paginated_queries import PaginatedQueries
from quetzal.openapi_client.models.paginated_workspaces import PaginatedWorkspaces
from quetzal.openapi_client.models.pagination_envelope import PaginationEnvelope
from quetzal.openapi_client.models.query import Query
from quetzal.openapi_client.models.query_no_results import QueryNoResults
from quetzal.openapi_client.models.token import Token
from quetzal.openapi_client.models.workspace import Workspace

# Added by generate.sh:
# Add a complete reference to the generator version:
# a git commit or Docker image ID used to generate this code with openapi-generator-cli
__openapi_generator_cli_version__ = "git-a979fd8e13"
