- project:
    templates:
      - openstack-python-jobs
      - check-requirements
      - publish-openstack-sphinx-docs
      - release-notes-jobs
    check:
      jobs:
        - bifrost-integration-tinyipa-ubuntu-xenial
        # Non-voting jobs
        - bifrost-integration-dhcp-ubuntu-xenial:
            voting: false
        - bifrost-integration-dhcp-centos-7:
            voting: false
        - bifrost-integration-dibipa-debian-centos-7:
            voting: false
        - bifrost-integration-dibipa-debian-ubuntu-xenial:
            voting: false
        - bifrost-integration-tinyipa-centos-7:
            voting: false
    gate:
      jobs:
        - bifrost-integration-tinyipa-ubuntu-xenial
