# coding: utf-8

"""
    GeoAPI

    Geospatial API for TAPIS  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import geoapi_client
from geoapi_client.models.tapis_file import TapisFile  # noqa: E501
from geoapi_client.rest import ApiException


class TestTapisFile(unittest.TestCase):
    """TapisFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTapisFile(self):
        """Test TapisFile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = geoapi_client.models.tapis_file.TapisFile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
