
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-23T11:05:20+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "86d6434cf40e334ef81ad9e548d754b0b0dd680f",
 "version": "5.7.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
