# Generated by Django 2.2.6 on 2019-10-10 15:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyaudit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudevent',
            name='changed_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
