
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "a2fcbc1156d3c193b5e66d213cefd5bf009c16c1",
 "version": "1.10.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
