
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-25T09:48:54-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "e7b198d3530badfc76e2084ccf2bbe4d12f2342d",
 "version": "v2.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
