[tool.poetry]
name = "uvpool-web"
version = "0.1.1"
description = "A sanic based web framework"
authors = ["Yehuda Deutsch <yeh@uda.co.il>"]
license = "MIT"

readme = "README.md"
repository = "https://gitlab.com/uda/uvpool.git"
homepage = "https://gitlab.com/uda/uvpool"

packages = [
    { include = "uvpool" }
]

[tool.poetry.dependencies]
python = "^3.7"
sanic = "^19.9.0"
rollbar = {version = "^0.14.7", optional = true}
raven = {version = "^6.10.0", optional = true}

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
rollbar = ["rollbar"]
sentry = ["raven"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
