[tool.poetry]
name = "openlaw"
version = "0.1.1"
description = "A metapackage for OpenLaw Israel projects"
authors = ["Yehuda Deutsch <yeh@uda.co.il>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
