[tool.poetry]
name = "django-model-subscription"
version = "0.0.2"
description = "Subscription model for a django model instance."
authors = ["Tonye Jack <tonyejck@gmail.com>"]
license = "MIT"
homepage = "https://github.com/jackton1/django-model-subscription"
repository = "https://github.com/jackton1/django-model-subscription"
documentation = "https://github.com/jackton1/django-model-subscription/blob/master/README.md"

keywords = [
    "django model subscription",
    "model observer",
    "model change subscriber",
    "model subscriptions",
    "model instance subscription",
]

classifiers = [
    'Environment :: Web Environment',
    'Framework :: Django',
    'Framework :: Django :: 1.11',
    'Framework :: Django :: 2.0',
    'Framework :: Django :: 2.1',
    'Framework :: Django :: 2.2',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
    'Programming Language :: Python',
    'Programming Language :: Python :: 2.6',
    'Programming Language :: Python :: 2.7',
    'Programming Language :: Python :: 3.0',
    'Programming Language :: Python :: 3.2',
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Topic :: Internet :: WWW/HTTP',
    'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
]

include = ["CHANGELOG.md", "manage.py", "django_model_subscription", "model_subscription"]

exclude = [
    "__pycache__",
    "*.pyc", "*.pyo",
    "*.orig", "tests*",
    "*tests", "demo*",
]
readme = "README.md"


[tool.poetry.dependencies]
python = "~2.7 || ^3.5 || ^3.6 || ^3.7 || ~3.8"
# The typing module is not in the stdlib in Python 2.7 and 3.4
typing = { version = "^3.6", python = "~2.7 || ~3.4" }
django-lifecycle = "^0.3.0"

[tool.poetry.dev-dependencies]
Django = {version = "^1.11", extras = ["development"]}
check-manifest = {version = "^0.40.0", extras = ["development"]}
bump2version = {version = "^0.5.11", extras = ["deploy"]}
git-changelog = {version = "^0.1.0", extras = ["deploy"], python = "^3.6"}
poetry-setup = {version = "^0.3.6", extras = ["development"]}

[tool.poetry.extras]
deploy = ["bump2version", "git-changelog", "poetry-setup"]
development = ["Django", "check-manifest"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
