
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-21T16:31:02-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a8da53f130b6937ecdd7c020bc55d7695d46db61",
 "version": "1.6.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
