from noval.constants import *

DEFAULT_KEY_BINDS = {
    ID_NEW              :   "Ctrl+N",
    ID_OPEN             :   "Ctrl+O",
    ID_CLOSE            :   "Ctrl+W",
    ID_SAVE             :   "Ctrl+S",
    ID_SAVEALL          :   "Ctrl+Shift+A",
    ID_GOTO_LINE        :   'Ctrl+G',
    ID_FIND             :   'Ctrl+F',
    ID_REPLACE          :   'Ctrl+H',
    ID_FINDFILE         :   'Ctrl+Shift+F',
    ID_FINDALL          :   'Ctrl+Shift+P',
    ID_FINDDIR          :   'Ctrl+Shift+D',
    ID_UNCOMMENT_LINES  :   'Ctrl+Shift+K',
    ID_COMMENT_LINES    :   'Ctrl+K',
    ID_RUN              :   'F5',
    ID_DEBUG            :   'Ctrl+F5',
    ID_EXIT             :   'Ctrl+Q',
    ID_UNDO             :   "Ctrl+Z",
    ID_REDO             :   "Ctrl+Y",
    ID_CUT              :   "Ctrl+X",
    ID_COPY             :   "Ctrl+C",
    ID_PASTE            :   "Ctrl+V",
    ID_CLEAR            :   "Ctrl+D",
    ID_SELECTALL        :   "Ctrl+A",
    ID_GOTO_DEFINITION  :   'F12',
    ID_STEP_INTO        :   'F11',
    ID_STEP_NEXT        :   'F10',
    ID_CHECK_SYNTAX     :   'Ctrl+F3',
    ID_RUN_LAST         :   'Ctrl+R',
   # ID_DEBUG_LAST       :   'Ctrl+R+D',
    ID_PRINT            :   'Ctrl+P',
    ID_UPPERCASE        :   'Ctrl+Shift+U',
    ID_LOWERCASE        :   'Ctrl+U',
    ID_CUT_LINE         :   'Ctrl+L',
    ID_AUTO_COMPLETE    :   'Ctrl+space',
    ID_TOGGLE_BREAKPOINT:   'Ctrl+B'
}