
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "b6a54f530d1154c29491c8077709f2dbafdeda5d",
 "version": "1.1.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
