# coding: utf-8

"""
    OOXML Automation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0-no-tags
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ChildObjectsDTO(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'entity_id': 'str',
        'object_type_name': 'str',
        'parent_entity_id': 'str',
        'parent_object_type_name': 'str'
    }

    attribute_map = {
        'entity_id': 'entityId',
        'object_type_name': 'objectTypeName',
        'parent_entity_id': 'parentEntityId',
        'parent_object_type_name': 'parentObjectTypeName'
    }

    def __init__(self, entity_id=None, object_type_name=None, parent_entity_id=None, parent_object_type_name=None):  # noqa: E501
        """ChildObjectsDTO - a model defined in OpenAPI"""  # noqa: E501

        self._entity_id = None
        self._object_type_name = None
        self._parent_entity_id = None
        self._parent_object_type_name = None
        self.discriminator = None

        self.entity_id = entity_id
        self.object_type_name = object_type_name
        self.parent_entity_id = parent_entity_id
        self.parent_object_type_name = parent_object_type_name

    @property
    def entity_id(self):
        """Gets the entity_id of this ChildObjectsDTO.  # noqa: E501


        :return: The entity_id of this ChildObjectsDTO.  # noqa: E501
        :rtype: str
        """
        return self._entity_id

    @entity_id.setter
    def entity_id(self, entity_id):
        """Sets the entity_id of this ChildObjectsDTO.


        :param entity_id: The entity_id of this ChildObjectsDTO.  # noqa: E501
        :type: str
        """

        self._entity_id = entity_id

    @property
    def object_type_name(self):
        """Gets the object_type_name of this ChildObjectsDTO.  # noqa: E501


        :return: The object_type_name of this ChildObjectsDTO.  # noqa: E501
        :rtype: str
        """
        return self._object_type_name

    @object_type_name.setter
    def object_type_name(self, object_type_name):
        """Sets the object_type_name of this ChildObjectsDTO.


        :param object_type_name: The object_type_name of this ChildObjectsDTO.  # noqa: E501
        :type: str
        """

        self._object_type_name = object_type_name

    @property
    def parent_entity_id(self):
        """Gets the parent_entity_id of this ChildObjectsDTO.  # noqa: E501


        :return: The parent_entity_id of this ChildObjectsDTO.  # noqa: E501
        :rtype: str
        """
        return self._parent_entity_id

    @parent_entity_id.setter
    def parent_entity_id(self, parent_entity_id):
        """Sets the parent_entity_id of this ChildObjectsDTO.


        :param parent_entity_id: The parent_entity_id of this ChildObjectsDTO.  # noqa: E501
        :type: str
        """

        self._parent_entity_id = parent_entity_id

    @property
    def parent_object_type_name(self):
        """Gets the parent_object_type_name of this ChildObjectsDTO.  # noqa: E501


        :return: The parent_object_type_name of this ChildObjectsDTO.  # noqa: E501
        :rtype: str
        """
        return self._parent_object_type_name

    @parent_object_type_name.setter
    def parent_object_type_name(self, parent_object_type_name):
        """Sets the parent_object_type_name of this ChildObjectsDTO.


        :param parent_object_type_name: The parent_object_type_name of this ChildObjectsDTO.  # noqa: E501
        :type: str
        """

        self._parent_object_type_name = parent_object_type_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChildObjectsDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
