# coding: utf-8

"""
    Quetzalcoatl API

    Quetzal: an API to manage data files and their associated metadata.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: support@quetz.al
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import quetzal.openapi_client
from quetzal.openapi_client.models.paginated_workspaces import PaginatedWorkspaces  # noqa: E501
from quetzal.openapi_client.rest import ApiException


class TestPaginatedWorkspaces(unittest.TestCase):
    """PaginatedWorkspaces unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedWorkspaces(self):
        """Test PaginatedWorkspaces"""
        # FIXME: construct object with mandatory attributes with example values
        # model = quetzal.openapi_client.models.paginated_workspaces.PaginatedWorkspaces()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
