[tool.poetry]
name = "sindy"
version = "0.1.0"
description = ""
license = "MIT"
authors = ["Markus Quade <info@markusqua.de>"]

[tool.poetry.dependencies]
python = "^3.7"
sparsereg = "^0.10.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
