# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-21 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_project', '0005_auto_20191017_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'control')},
        ),
    ]
