# Generated by Django 2.2.6 on 2019-10-23 07:57

import dj_pony.ulidfield.models
from django.db import migrations
import jsonfield.fields
import ulid.api


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='ulid',
            field=dj_pony.ulidfield.models.ULIDField(db_index=True, default=ulid.api.new, unique=True),
        ),
    ]
