# coding: utf-8

"""
    Limestone Networks API

    LSN API Documentation  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@limestonenetworks.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import limestone
from limestone.models.ssh_key import SSHKey  # noqa: E501
from limestone.rest import ApiException


class TestSSHKey(unittest.TestCase):
    """SSHKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSSHKey(self):
        """Test SSHKey"""
        # FIXME: construct object with mandatory attributes with example values
        # model = limestone.models.ssh_key.SSHKey()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
