# coding: utf-8

"""
    Limestone Networks API

    LSN API Documentation  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@limestonenetworks.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import limestone
from limestone.api.job_api import JobApi  # noqa: E501
from limestone.rest import ApiException


class TestJobApi(unittest.TestCase):
    """JobApi unit test stubs"""

    def setUp(self):
        self.api = limestone.api.job_api.JobApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_job_status(self):
        """Test case for get_job_status

        Get a job status  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
