# coding: utf-8

"""
    Limestone Networks API

    LSN API Documentation  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@limestonenetworks.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import limestone
from limestone.models.instance import Instance  # noqa: E501
from limestone.rest import ApiException


class TestInstance(unittest.TestCase):
    """Instance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstance(self):
        """Test Instance"""
        # FIXME: construct object with mandatory attributes with example values
        # model = limestone.models.instance.Instance()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
