# coding: utf-8

"""
    Limestone Networks API

    LSN API Documentation  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@limestonenetworks.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import limestone
from limestone.models.project_quotas import ProjectQuotas  # noqa: E501
from limestone.rest import ApiException


class TestProjectQuotas(unittest.TestCase):
    """ProjectQuotas unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectQuotas(self):
        """Test ProjectQuotas"""
        # FIXME: construct object with mandatory attributes with example values
        # model = limestone.models.project_quotas.ProjectQuotas()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
