# coding: utf-8

"""
    Limestone Networks API

    LSN API Documentation  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@limestonenetworks.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import limestone
from limestone.models.raid_disk_all_of_raid import RaidDiskAllOfRaid  # noqa: E501
from limestone.rest import ApiException


class TestRaidDiskAllOfRaid(unittest.TestCase):
    """RaidDiskAllOfRaid unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRaidDiskAllOfRaid(self):
        """Test RaidDiskAllOfRaid"""
        # FIXME: construct object with mandatory attributes with example values
        # model = limestone.models.raid_disk_all_of_raid.RaidDiskAllOfRaid()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
