# coding: utf-8

"""
    Limestone Networks API

    LSN API Documentation  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@limestonenetworks.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import limestone
from limestone.models.server_create_parameters_with_os_disk_all_of import ServerCreateParametersWithOSDiskAllOf  # noqa: E501
from limestone.rest import ApiException


class TestServerCreateParametersWithOSDiskAllOf(unittest.TestCase):
    """ServerCreateParametersWithOSDiskAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServerCreateParametersWithOSDiskAllOf(self):
        """Test ServerCreateParametersWithOSDiskAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = limestone.models.server_create_parameters_with_os_disk_all_of.ServerCreateParametersWithOSDiskAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
