# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 11:44
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabotapp', '0007_statuscheckresult_consecutive_failures'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluxdbStatusCheck',
            fields=[
                ('statuscheck_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cabotapp.StatusCheck')),
                ('host', models.TextField(help_text=b'Host influxdb.', null=True)),
                ('port', models.PositiveIntegerField(help_text=b'Port influxdb.', null=True)),
                ('database', models.TextField(help_text=b'Database to check.', null=True)),
                ('query', models.TextField(help_text=b'Query to execute.', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cabotapp.statuscheck',),
        ),
    ]
