# coding: utf-8

"""
    Key Manager API

    API Responsible for management the tools' keys   # noqa: E501

    OpenAPI spec version: v1
    Contact: paulossjunior@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Entity_(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'ontology_id': 'str',
        'ontology_name': 'str',
        'ontology_type': 'str',
        'organization': 'int'
    }

    attribute_map = {
        'id': 'id',
        'ontology_id': 'ontology_id',
        'ontology_name': 'ontology_name',
        'ontology_type': 'ontology_type',
        'organization': 'organization'
    }

    def __init__(self, id=None, ontology_id=None, ontology_name=None, ontology_type=None, organization=None):  # noqa: E501
        """Entity_ - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._ontology_id = None
        self._ontology_name = None
        self._ontology_type = None
        self._organization = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.ontology_id = ontology_id
        self.ontology_name = ontology_name
        self.ontology_type = ontology_type
        self.organization = organization

    @property
    def id(self):
        """Gets the id of this Entity_.  # noqa: E501


        :return: The id of this Entity_.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Entity_.


        :param id: The id of this Entity_.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def ontology_id(self):
        """Gets the ontology_id of this Entity_.  # noqa: E501


        :return: The ontology_id of this Entity_.  # noqa: E501
        :rtype: str
        """
        return self._ontology_id

    @ontology_id.setter
    def ontology_id(self, ontology_id):
        """Sets the ontology_id of this Entity_.


        :param ontology_id: The ontology_id of this Entity_.  # noqa: E501
        :type: str
        """
        if ontology_id is None:
            raise ValueError("Invalid value for `ontology_id`, must not be `None`")  # noqa: E501
        if ontology_id is not None and len(ontology_id) > 200:
            raise ValueError("Invalid value for `ontology_id`, length must be less than or equal to `200`")  # noqa: E501
        if ontology_id is not None and len(ontology_id) < 1:
            raise ValueError("Invalid value for `ontology_id`, length must be greater than or equal to `1`")  # noqa: E501

        self._ontology_id = ontology_id

    @property
    def ontology_name(self):
        """Gets the ontology_name of this Entity_.  # noqa: E501


        :return: The ontology_name of this Entity_.  # noqa: E501
        :rtype: str
        """
        return self._ontology_name

    @ontology_name.setter
    def ontology_name(self, ontology_name):
        """Sets the ontology_name of this Entity_.


        :param ontology_name: The ontology_name of this Entity_.  # noqa: E501
        :type: str
        """
        if ontology_name is None:
            raise ValueError("Invalid value for `ontology_name`, must not be `None`")  # noqa: E501
        if ontology_name is not None and len(ontology_name) > 200:
            raise ValueError("Invalid value for `ontology_name`, length must be less than or equal to `200`")  # noqa: E501
        if ontology_name is not None and len(ontology_name) < 1:
            raise ValueError("Invalid value for `ontology_name`, length must be greater than or equal to `1`")  # noqa: E501

        self._ontology_name = ontology_name

    @property
    def ontology_type(self):
        """Gets the ontology_type of this Entity_.  # noqa: E501


        :return: The ontology_type of this Entity_.  # noqa: E501
        :rtype: str
        """
        return self._ontology_type

    @ontology_type.setter
    def ontology_type(self, ontology_type):
        """Sets the ontology_type of this Entity_.


        :param ontology_type: The ontology_type of this Entity_.  # noqa: E501
        :type: str
        """
        if ontology_type is None:
            raise ValueError("Invalid value for `ontology_type`, must not be `None`")  # noqa: E501
        if ontology_type is not None and len(ontology_type) > 200:
            raise ValueError("Invalid value for `ontology_type`, length must be less than or equal to `200`")  # noqa: E501
        if ontology_type is not None and len(ontology_type) < 1:
            raise ValueError("Invalid value for `ontology_type`, length must be greater than or equal to `1`")  # noqa: E501

        self._ontology_type = ontology_type

    @property
    def organization(self):
        """Gets the organization of this Entity_.  # noqa: E501


        :return: The organization of this Entity_.  # noqa: E501
        :rtype: int
        """
        return self._organization

    @organization.setter
    def organization(self, organization):
        """Sets the organization of this Entity_.


        :param organization: The organization of this Entity_.  # noqa: E501
        :type: int
        """
        if organization is None:
            raise ValueError("Invalid value for `organization`, must not be `None`")  # noqa: E501

        self._organization = organization

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Entity_, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Entity_):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
