[tool.poetry]
name = "slowmo"
version = "0.1.0"
description = ""
authors = ["Pedro Cattori <pcattori@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
blessed = "^1.15"
spinners = "^0.0.23"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
