name: intake-esm-dev
channels:
  - conda-forge
dependencies:
  - intake-xarray>=0.3.1
  - xarray=>0.13
  - nbsphinx
  - numpydoc=0.8.0
  - python=3.7
  - pyyaml
  - sphinx_rtd_theme=0.4.2
  - sphinx=1.8.2
  - sphinx-copybutton=0.2.5
  - tqdm
  - git
  - make
  - ipython
  - s3fs
  - fsspec
