trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

jobs:
- job: RunTests
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
#        Python38:
#          python.version: '3.8'
  steps:
  - template: ci/run-tests.yml

- job: CheckRelease
  dependsOn: RunTests
  steps:
    - template: ci/check-release.yml

- job: Release
  dependsOn: CheckRelease
  condition: eq(dependencies.CheckRelease.outputs['DetermineRelease.isRelease'], 'YES')
  steps:
  - template: ci/release.yml
