# This is a common .travis.yml for generating library release zip files for
# CircuitPython library releases using circuitpython-build-tools.
# See https://github.com/adafruit/circuitpython-build-tools for detailed setup
# instructions.

dist: xenial
language: python
python:
  - "3.6"

cache:
  pip: true

env:
  - DEPLOY_PYPI="true"

deploy:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file: "$TRAVIS_BUILD_DIR/bundles/*"
    skip_cleanup: true
    overwrite: true
    on:
      tags: true

  - provider: pypi
    user: adafruit-travis
    password:
      secure: Gn6iXRZcCRbyC8tw1ok3LhRkRPA4cQY1mF8YEzagXzclwDA752MWoIZrOVlfdeiawvC/IS5y2RSUMcYUF6aoY6FlodQZ3nZlbKfn64iwasl7iqq21hNkByhfqnPrvDZdwqqt7LaXvacGvfHUuZ4cEqItJ+zGwCUXeRra3s8UbGzzhKZp51INv4xzJ2tP1T1nfpwpvVUHfxied52XBoEwmJ9/sV4BCmkIhB2OnR/jANPLUjPkLIHJjl9jc35Z7TciODtxnx9oWVtviztMOTJNT4U+mlbnAR82HiYhKxzpavq6NTqumUQJIGp57wTT7b9cKGzmAgZy7WMJzFhcMmGsTuqoYUyHNAEHFcri18Vot1RFvd8+HZR/aeG5bJcK5WkHveiFUn96O4Gd8GaNDMjAZS+ay0ZOepEDSBidLlmo1067Qkkc50idGdvnAop9yg16iSw3TU421b4jzXDCNE7+UJS65xSdvnLgyCFSpX6O2viCArOW4b99MKLdS2VJhAYRabAeBd+aCwMPnjHEz9fpkoohJzYT9pUa612lOvcBdFTeKBQfBBc4lb3RT6D3NvKpdpo1Hzdi4XI1clPzXA9F1AnQPxVaJCPCgAQqk8sn72PSDxuOJ+XyFr+rWBA/flVffNMJ49QAqFlN/wQgqBnevxJagWtFdoG1tIwAHB9cRvU=
    on:
      tags: true
      condition: $DEPLOY_PYPI = "true"

install:
  - pip install -r requirements.txt
  - pip install circuitpython-build-tools Sphinx sphinx-rtd-theme
  - pip install --force-reinstall pylint==1.9.2

script:
  - pylint adafruit_mpu6050.py
  - ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace examples/*.py)
  - circuitpython-build-bundles --filename_prefix adafruit-circuitpython-mpu6050 --library_location .
  - cd docs && sphinx-build -E -W -b html . _build/html && cd ..
