setcodes = {
    "gn2": "Game Night 2019",
    "ptg": "Ponies: The Galloping",
    "peld": "Throne of Eldraine Promos",
    "eld": "Throne of Eldraine",
    "teld": "Throne of Eldraine Tokens",
    "oc19": "Commander 2019 Oversized",
    "c19": "Commander 2019",
    "tc19": "Commander 2019 Tokens",
    "ps19": "San Diego Comic-Con 2019",
    "ppp1": "M20 Promo Packs",
    "pm20": "Core Set 2020 Promos",
    "tm20": "Core Set 2020 Tokens",
    "m20": "Core Set 2020",
    "ss2": "Signature Spellbook: Gideon",
    "pmh1": "Modern Horizons Promos",
    "mh1": "Modern Horizons",
    "amh1": "Modern Horizons Art Series",
    "tmh1": "Modern Horizons Tokens",
    "pwar": "War of the Spark Promos",
    "twar": "War of the Spark Tokens",
    "war": "War of the Spark",
    "j19": "Judge Gift Cards 2019",
    "prw2": "RNA Ravnica Weekend",
    "gk2": "RNA Guild Kit",
    "tgk2": "RNA Guild Kit Tokens",
    "prna": "Ravnica Allegiance Promos",
    "rna": "Ravnica Allegiance",
    "trna": "Ravnica Allegiance Tokens",
    "pf19": "MagicFest 2019",
    "opca": "Planechase Anthology Planes",
    "puma": "Ultimate Box Topper",
    "uma": "Ultimate Masters",
    "tuma": "Ultimate Masters Tokens",
    "g18": "M19 Gift Pack",
    "gnt": "Game Night",
    "gk1": "GRN Guild Kit",
    "tgk1": "GRN Guild Kit Tokens",
    "pgrn": "Guilds of Ravnica Promos",
    "tgrn": "Guilds of Ravnica Tokens",
    "prwk": "GRN Ravnica Weekend",
    "grn": "Guilds of Ravnica",
    "tmed": "Mythic Edition Tokens",
    "med": "Mythic Edition",
    "oc18": "Commander 2018 Oversized",
    "c18": "Commander 2018",
    "tc18": "Commander 2018 Tokens",
    "htr17": "2017 Heroes of the Realm",
    "ps18": "San Diego Comic-Con 2018",
    "ana": "Arena New Player Experience",
    "pana": "MTG Arena Promos",
    "pm19": "Core Set 2019 Promos",
    "tm19": "Core Set 2019 Tokens",
    "pss3": "M19 Standard Showdown",
    "m19": "Core Set 2019",
    "gs1": "Global Series Jiang Yanggu & Mu Yanling",
    "ss1": "Signature Spellbook: Jace",
    "pbbd": "Battlebond Promos",
    "bbd": "Battlebond",
    "tbbd": "Battlebond Tokens",
    "tcm2": "Commander Anthology Volume II Tokens",
    "cm2": "Commander Anthology Volume II",
    "pdom": "Dominaria Promos",
    "tdom": "Dominaria Tokens",
    "dom": "Dominaria",
    "tddu": "Duel Decks: Elves vs. Inventors Tokens",
    "ddu": "Duel Decks: Elves vs. Inventors",
    "a25": "Masters 25",
    "ta25": "Masters 25 Tokens",
    "plny": "2018 Lunar New Year",
    "pnat": "Nationals Promos",
    "trix": "Rivals of Ixalan Tokens",
    "prix": "Rivals of Ixalan Promos",
    "rix": "Rivals of Ixalan",
    "j18": "Judge Gift Cards 2018",
    "f18": "Friday Night Magic 2018",
    "ust": "Unstable",
    "tima": "Iconic Masters Tokens",
    "e02": "Explorers of Ixalan",
    "pxtc": "XLN Treasure Chest",
    "v17": "From the Vault: Transform",
    "ima": "Iconic Masters",
    "tust": "Unstable Tokens",
    "pust": "Unstable Promos",
    "ddt": "Duel Decks: Merfolk vs. Goblins",
    "tddt": "Duel Decks: Merfolk vs. Goblins Tokens",
    "g17": "2017 Gift Pack",
    "pxln": "Ixalan Promos",
    "xln": "Ixalan",
    "txln": "Ixalan Tokens",
    "pss2": "XLN Standard Showdown",
    "h17": "HasCon 2017",
    "htr": "2016 Heroes of the Realm",
    "te01": "Archenemy: Nicol Bolas Tokens",
    "oc17": "Commander 2017 Oversized",
    "tc17": "Commander 2017 Tokens",
    "c17": "Commander 2017",
    "ps17": "San Diego Comic-Con 2017",
    "phou": "Hour of Devastation Promos",
    "hou": "Hour of Devastation",
    "thou": "Hour of Devastation Tokens",
    "oe01": "Archenemy: Nicol Bolas Schemes",
    "e01": "Archenemy: Nicol Bolas",
    "tcma": "Commander Anthology Tokens",
    "cma": "Commander Anthology",
    "pakh": "Amonkhet Promos",
    "akh": "Amonkhet",
    "takh": "Amonkhet Tokens",
    "mp2": "Amonkhet Invocations",
    "w17": "Welcome Deck 2017",
    "dds": "Duel Decks: Mind vs. Might",
    "tdds": "Duel Decks: Mind vs. Might Tokens",
    "tmm3": "Modern Masters 2017 Tokens",
    "mm3": "Modern Masters 2017",
    "paer": "Aether Revolt Promos",
    "taer": "Aether Revolt Tokens",
    "aer": "Aether Revolt",
    "l17": "League Tokens 2017",
    "j17": "Judge Gift Cards 2017",
    "f17": "Friday Night Magic 2017",
    "tpca": "Planechase Anthology Tokens",
    "pca": "Planechase Anthology",
    "pz2": "Treasure Chest",
    "oc16": "Commander 2016 Oversized",
    "c16": "Commander 2016",
    "tc16": "Commander 2016 Tokens",
    "ps16": "San Diego Comic-Con 2016",
    "pkld": "Kaladesh Promos",
    "kld": "Kaladesh",
    "tkld": "Kaladesh Tokens",
    "mps": "Kaladesh Inventions",
    "ddr": "Duel Decks: Nissa vs. Ob Nixilis",
    "tcn2": "Conspiracy: Take the Crown Tokens",
    "cn2": "Conspiracy: Take the Crown",
    "v16": "From the Vault: Lore",
    "pemn": "Eldritch Moon Promos",
    "temn": "Eldritch Moon Tokens",
    "emn": "Eldritch Moon",
    "tema": "Eternal Masters Tokens",
    "ema": "Eternal Masters",
    "psoi": "Shadows over Innistrad Promos",
    "tsoi": "Shadows over Innistrad Tokens",
    "soi": "Shadows over Innistrad",
    "w16": "Welcome Deck 2016",
    "ddq": "Duel Decks: Blessed vs. Cursed",
    "pogw": "Oath of the Gatewatch Promos",
    "ogw": "Oath of the Gatewatch",
    "togw": "Oath of the Gatewatch Tokens",
    "l16": "League Tokens 2016",
    "f16": "Friday Night Magic 2016",
    "j16": "Judge Gift Cards 2016",
    "pz1": "Legendary Cube Prize Pack",
    "c15": "Commander 2015",
    "tc15": "Commander 2015 Tokens",
    "oc15": "Commander 2015 Oversized",
    "pbfz": "Battle for Zendikar Promos",
    "bfz": "Battle for Zendikar",
    "tbfz": "Battle for Zendikar Tokens",
    "pss1": "BFZ Standard Series",
    "exp": "Zendikar Expeditions",
    "ddp": "Duel Decks: Zendikar vs. Eldrazi",
    "v15": "From the Vault: Angels",
    "cp3": "Magic Origins Clash Pack",
    "pori": "Magic Origins Promos",
    "ori": "Magic Origins",
    "tori": "Magic Origins Tokens",
    "ps15": "San Diego Comic-Con 2015",
    "mm2": "Modern Masters 2015",
    "tmm2": "Modern Masters 2015 Tokens",
    "tpr": "Tempest Remastered",
    "ptkdf": "Tarkir Dragonfury",
    "pdtk": "Dragons of Tarkir Promos",
    "dtk": "Dragons of Tarkir",
    "tdtk": "Dragons of Tarkir Tokens",
    "ddo": "Duel Decks: Elspeth vs. Kiora",
    "pfrf": "Fate Reforged Promos",
    "cp2": "Fate Reforged Clash Pack",
    "frf": "Fate Reforged",
    "tfrf": "Fate Reforged Tokens",
    "ugin": "Ugin's Fate",
    "l15": "League Tokens 2015",
    "j15": "Judge Gift Cards 2015",
    "f15": "Friday Night Magic 2015",
    "tjvc": "Duel Decks Anthology: Jace vs. Chandra Tokens",
    "tdvd": "Duel Decks Anthology: Divine vs. Demonic Tokens",
    "tgvl": "Duel Decks Anthology: Garruk vs. Liliana Tokens",
    "jvc": "Duel Decks Anthology: Jace vs. Chandra",
    "dvd": "Duel Decks Anthology: Divine vs. Demonic",
    "evg": "Duel Decks Anthology: Elves vs. Goblins",
    "gvl": "Duel Decks Anthology: Garruk vs. Liliana",
    "tevg": "Duel Decks Anthology: Elves vs. Goblins Tokens",
    "oc14": "Commander 2014 Oversized",
    "c14": "Commander 2014",
    "tc14": "Commander 2014 Tokens",
    "pktk": "Khans of Tarkir Promos",
    "tktk": "Khans of Tarkir Tokens",
    "ktk": "Khans of Tarkir",
    "ddn": "Duel Decks: Speed vs. Cunning",
    "v14": "From the Vault: Annihilation",
    "cp1": "Magic 2015 Clash Pack",
    "tm15": "Magic 2015 Tokens",
    "m15": "Magic 2015",
    "pm15": "Magic 2015 Promos",
    "ppc1": "M15 Prerelease Challenge",
    "ps14": "San Diego Comic-Con 2014",
    "vma": "Vintage Masters",
    "cns": "Conspiracy",
    "tcns": "Conspiracy Tokens",
    "tmd1": "Modern Event Deck 2014 Tokens",
    "md1": "Modern Event Deck 2014",
    "tdag": "Defeat a God",
    "jou": "Journey into Nyx",
    "thp3": "Journey into Nyx Hero's Path",
    "tjou": "Journey into Nyx Tokens",
    "pjou": "Journey into Nyx Promos",
    "ddm": "Duel Decks: Jace vs. Vraska",
    "tddm": "Duel Decks: Jace vs. Vraska Tokens",
    "tbth": "Battle the Horde",
    "thp2": "Born of the Gods Hero's Path",
    "tbng": "Born of the Gods Tokens",
    "bng": "Born of the Gods",
    "pbng": "Born of the Gods Promos",
    "pdp14": "Duels of the Planeswalkers Promos 2014",
    "pi14": "IDW Comics 2014",
    "l14": "League Tokens 2014",
    "f14": "Friday Night Magic 2014",
    "j14": "Judge Gift Cards 2014",
    "oc13": "Commander 2013 Oversized",
    "c13": "Commander 2013",
    "tfth": "Face the Hydra",
    "thp1": "Theros Hero's Path",
    "tths": "Theros Tokens",
    "ths": "Theros",
    "pths": "Theros Promos",
    "ddl": "Duel Decks: Heroes vs. Monsters",
    "tddl": "Duel Decks: Heroes vs. Monsters Tokens",
    "v13": "From the Vault: Twenty",
    "tm14": "Magic 2014 Tokens",
    "m14": "Magic 2014",
    "pm14": "Magic 2014 Promos",
    "psdc": "San Diego Comic-Con 2013",
    "mma": "Modern Masters",
    "tmma": "Modern Masters Tokens",
    "dgm": "Dragon's Maze",
    "tdgm": "Dragon's Maze Tokens",
    "pdgm": "Dragon's Maze Promos",
    "pwcq": "World Magic Cup Qualifiers",
    "tddk": "Duel Decks: Sorin vs. Tibalt Tokens",
    "ddk": "Duel Decks: Sorin vs. Tibalt",
    "gtc": "Gatecrash",
    "tgtc": "Gatecrash Tokens",
    "pgtc": "Gatecrash Promos",
    "pdp13": "Duels of the Planeswalkers Promos 2013",
    "pi13": "IDW Comics 2013",
    "l13": "League Tokens 2013",
    "f13": "Friday Night Magic 2013",
    "j13": "Judge Gift Cards 2013",
    "ocm1": "Commander's Arsenal Oversized",
    "cm1": "Commander's Arsenal",
    "rtr": "Return to Ravnica",
    "prtr": "Return to Ravnica Promos",
    "trtr": "Return to Ravnica Tokens",
    "ddj": "Duel Decks: Izzet vs. Golgari",
    "tddj": "Duel Decks: Izzet vs. Golgari Tokens",
    "v12": "From the Vault: Realms",
    "tm13": "Magic 2013 Tokens",
    "m13": "Magic 2013",
    "pm13": "Magic 2013 Promos",
    "opc2": "Planechase 2012 Planes",
    "pc2": "Planechase 2012",
    "tavr": "Avacyn Restored Tokens",
    "avr": "Avacyn Restored",
    "phel": "Open the Helvault",
    "pavr": "Avacyn Restored Promos",
    "tddi": "Duel Decks: Venser vs. Koth Tokens",
    "ddi": "Duel Decks: Venser vs. Koth",
    "tdka": "Dark Ascension Tokens",
    "dka": "Dark Ascension",
    "pdka": "Dark Ascension Promos",
    "pidw": "IDW Comics 2012",
    "pwp12": "Wizards Play Network 2012",
    "pdp12": "Duels of the Planeswalkers Promos 2012",
    "l12": "League Tokens 2012",
    "j12": "Judge Gift Cards 2012",
    "f12": "Friday Night Magic 2012",
    "pd3": "Premium Deck Series: Graveborn",
    "tisd": "Innistrad Tokens",
    "isd": "Innistrad",
    "pisd": "Innistrad Promos",
    "tddh": "Duel Decks: Ajani vs. Nicol Bolas Tokens",
    "ddh": "Duel Decks: Ajani vs. Nicol Bolas",
    "v11": "From the Vault: Legends",
    "tm12": "Magic 2012 Tokens",
    "m12": "Magic 2012",
    "pm12": "Magic 2012 Promos",
    "ocmd": "Commander 2011 Oversized",
    "pcmd": "Commander 2011 Launch Party",
    "cmd": "Commander 2011",
    "td2": "Duel Decks: Mirrodin Pure vs. New Phyrexia",
    "nph": "New Phyrexia",
    "tnph": "New Phyrexia Tokens",
    "pnph": "New Phyrexia Promos",
    "tddg": "Duel Decks: Knights vs. Dragons Tokens",
    "ddg": "Duel Decks: Knights vs. Dragons",
    "mbs": "Mirrodin Besieged",
    "tmbs": "Mirrodin Besieged Tokens",
    "pmbs": "Mirrodin Besieged Promos",
    "me4": "Masters Edition IV",
    "pmps11": "Magic Premiere Shop 2011",
    "pdp11": "Duels of the Planeswalkers Promos 2011",
    "pwp11": "Wizards Play Network 2011",
    "f11": "Friday Night Magic 2011",
    "olgc": "Legacy Championship",
    "g11": "Judge Gift Cards 2011",
    "ps11": "Salvat 2011",
    "p11": "Magic Player Rewards 2011",
    "pd2": "Premium Deck Series: Fire and Lightning",
    "td0": "Magic Online Theme Decks",
    "tsom": "Scars of Mirrodin Tokens",
    "som": "Scars of Mirrodin",
    "psom": "Scars of Mirrodin Promos",
    "tddf": "Duel Decks: Elspeth vs. Tezzeret Tokens",
    "ddf": "Duel Decks: Elspeth vs. Tezzeret",
    "v10": "From the Vault: Relics",
    "m11": "Magic 2011",
    "tm11": "Magic 2011 Tokens",
    "pm11": "Magic 2011 Promos",
    "oarc": "Archenemy Schemes",
    "arc": "Archenemy",
    "parc": "Promotional Schemes",
    "dpa": "Duels of the Planeswalkers",
    "proe": "Rise of the Eldrazi Promos",
    "roe": "Rise of the Eldrazi",
    "troe": "Rise of the Eldrazi Tokens",
    "dde": "Duel Decks: Phyrexia vs. the Coalition",
    "tdde": "Duel Decks: Phyrexia vs. the Coalition Tokens",
    "pwwk": "Worldwake Promos",
    "wwk": "Worldwake",
    "twwk": "Worldwake Tokens",
    "pdp10": "Duels of the Planeswalkers Promos 2010",
    "pwp10": "Wizards Play Network 2010",
    "pmps10": "Magic Premiere Shop 2010",
    "p10": "Magic Player Rewards 2010",
    "g10": "Judge Gift Cards 2010",
    "f10": "Friday Night Magic 2010",
    "h09": "Premium Deck Series: Slivers",
    "ddd": "Duel Decks: Garruk vs. Liliana",
    "tddd": "Duel Decks: Garruk vs. Liliana Tokens",
    "pzen": "Zendikar Promos",
    "tzen": "Zendikar Tokens",
    "zen": "Zendikar",
    "me3": "Masters Edition III",
    "ohop": "Planechase Planes",
    "hop": "Planechase",
    "phop": "Promotional Planes",
    "v09": "From the Vault: Exiled",
    "m10": "Magic 2010",
    "tm10": "Magic 2010 Tokens",
    "pm10": "Magic 2010 Promos",
    "tarb": "Alara Reborn Tokens",
    "arb": "Alara Reborn",
    "ddc": "Duel Decks: Divine vs. Demonic",
    "tddc": "Duel Decks: Divine vs. Demonic Tokens",
    "purl": "URL/Convention Promos",
    "con": "Conflux",
    "tcon": "Conflux Tokens",
    "pbok": "Miscellaneous Book Promos",
    "pwp09": "Wizards Play Network 2009",
    "pdtp": "Duels of the Planeswalkers Promos 2009",
    "pmps09": "Magic Premiere Shop 2009",
    "f09": "Friday Night Magic 2009",
    "g09": "Judge Gift Cards 2009",
    "p09": "Magic Player Rewards 2009",
    "tdd2": "Duel Decks: Jace vs. Chandra Tokens",
    "dd2": "Duel Decks: Jace vs. Chandra",
    "ala": "Shards of Alara",
    "tala": "Shards of Alara Tokens",
    "pwpn": "Wizards Play Network 2008",
    "me2": "Masters Edition II",
    "drb": "From the Vault: Dragons",
    "eve": "Eventide",
    "teve": "Eventide Tokens",
    "tshm": "Shadowmoor Tokens",
    "shm": "Shadowmoor",
    "p15a": "15th Anniversary Cards",
    "tmor": "Morningtide Tokens",
    "mor": "Morningtide",
    "plpa": "Launch Parties",
    "pmps08": "Magic Premiere Shop 2008",
    "pg08": "Gateway 2008",
    "p08": "Magic Player Rewards 2008",
    "f08": "Friday Night Magic 2008",
    "g08": "Judge Gift Cards 2008",
    "tdd1": "Duel Decks: Elves vs. Goblins Tokens",
    "dd1": "Duel Decks: Elves vs. Goblins",
    "tlrw": "Lorwyn Tokens",
    "lrw": "Lorwyn",
    "me1": "Masters Edition",
    "psum": "Summer of Magic",
    "10e": "Tenth Edition",
    "p10e": "Tenth Edition Promos",
    "t10e": "Tenth Edition Tokens",
    "fut": "Future Sight",
    "pgpx": "Grand Prix Promos",
    "ppro": "Pro Tour Promos",
    "plc": "Planar Chaos",
    "pres": "Resale Promos",
    "pg07": "Gateway 2007",
    "pmps07": "Magic Premiere Shop 2007",
    "p07": "Magic Player Rewards 2007",
    "g07": "Judge Gift Cards 2007",
    "f07": "Friday Night Magic 2007",
    "hho": "Happy Holidays",
    "tsp": "Time Spiral",
    "tsb": "Time Spiral Timeshifted",
    "tcsp": "Coldsnap Tokens",
    "cst": "Coldsnap Theme Decks",
    "csp": "Coldsnap",
    "dis": "Dissension",
    "pcmp": "Champs and States",
    "gpt": "Guildpact",
    "pal06": "Arena League 2006",
    "pmps06": "Magic Premiere Shop 2006",
    "pjas": "Junior APAC Series",
    "pgtw": "Gateway 2006",
    "p06": "Magic Player Rewards 2006",
    "g06": "Judge Gift Cards 2006",
    "phuk": "Hachette UK",
    "f06": "Friday Night Magic 2006",
    "p2hg": "Two-Headed Giant Tournament",
    "rav": "Ravnica: City of Guilds",
    "psal": "Salvat 2005",
    "9ed": "Ninth Edition",
    "sok": "Saviors of Kamigawa",
    "bok": "Betrayers of Kamigawa",
    "pal05": "Arena League 2005",
    "pmps": "Magic Premiere Shop 2005",
    "pjse": "Junior Series Europe",
    "f05": "Friday Night Magic 2005",
    "g05": "Judge Gift Cards 2005",
    "p05": "Magic Player Rewards 2005",
    "unh": "Unhinged",
    "chk": "Champions of Kamigawa",
    "wc04": "World Championship Decks 2004",
    "5dn": "Fifth Dawn",
    "dst": "Darksteel",
    "pal04": "Arena League 2004",
    "p04": "Magic Player Rewards 2004",
    "g04": "Judge Gift Cards 2004",
    "f04": "Friday Night Magic 2004",
    "mrd": "Mirrodin",
    "wc03": "World Championship Decks 2003",
    "8ed": "Eighth Edition",
    "prel": "Release Events",
    "scg": "Scourge",
    "lgn": "Legions",
    "pmoa": "Magic Online Avatars",
    "pjjt": "Japan Junior Tournament",
    "pal03": "Arena League 2003",
    "ovnt": "Vintage Championship",
    "p03": "Magic Player Rewards 2003",
    "g03": "Judge Gift Cards 2003",
    "f03": "Friday Night Magic 2003",
    "ons": "Onslaught",
    "wc02": "World Championship Decks 2002",
    "phj": "Hobby Japan Promos",
    "prm": "Magic Online Promos",
    "jud": "Judgment",
    "tor": "Torment",
    "pal02": "Arena League 2002",
    "f02": "Friday Night Magic 2002",
    "g02": "Judge Gift Cards 2002",
    "pr2": "Magic Player Rewards 2002",
    "dkm": "Deckmasters",
    "ody": "Odyssey",
    "wc01": "World Championship Decks 2001",
    "apc": "Apocalypse",
    "7ed": "Seventh Edition",
    "pls": "Planeshift",
    "pal01": "Arena League 2001",
    "f01": "Friday Night Magic 2001",
    "g01": "Judge Gift Cards 2001",
    "mpr": "Magic Player Rewards 2001",
    "inv": "Invasion",
    "btd": "Beatdown Box Set",
    "wc00": "World Championship Decks 2000",
    "pcy": "Prophecy",
    "s00": "Starter 2000",
    "nem": "Nemesis",
    "pelp": "European Land Program",
    "pal00": "Arena League 2000",
    "g00": "Judge Gift Cards 2000",
    "fnm": "Friday Night Magic 2000",
    "psus": "Junior Super Series",
    "brb": "Battle Royale Box Set",
    "mmq": "Mercadian Masques",
    "pwos": "Wizards of the Coast Online Store",
    "pwor": "Worlds",
    "wc99": "World Championship Decks 1999",
    "pgru": "Guru",
    "s99": "Starter 1999",
    "uds": "Urza's Destiny",
    "ptk": "Portal Three Kingdoms",
    "6ed": "Classic Sixth Edition",
    "ulg": "Urza's Legacy",
    "pal99": "Arena League 1999",
    "g99": "Judge Gift Cards 1999",
    "ath": "Anthologies",
    "usg": "Urza's Saga",
    "palp": "Asia Pacific Land Program",
    "wc98": "World Championship Decks 1998",
    "tugl": "Unglued Tokens",
    "ugl": "Unglued",
    "exo": "Exodus",
    "p02": "Portal Second Age",
    "sth": "Stronghold",
    "jgp": "Judge Gift Cards 1998",
    "tmp": "Tempest",
    "ppre": "Prerelease Events",
    "wc97": "World Championship Decks 1997",
    "wth": "Weatherlight",
    "pvan": "Vanguard Series",
    "ppod": "Portal Demo Game",
    "por": "Portal",
    "5ed": "Fifth Edition",
    "vis": "Visions",
    "itp": "Introductory Two-Player Set",
    "mgb": "Multiverse Gift Box",
    "mir": "Mirage",
    "pred": "Redemption Program",
    "pcel": "Celebration Cards",
    "parl": "Arena League 1996",
    "rqs": "Rivals Quick Start Set",
    "all": "Alliances",
    "ptc": "Pro Tour Collector Set",
    "hml": "Homelands",
    "ren": "Renaissance",
    "rin": "Rinascimento",
    "chr": "Chronicles",
    "ice": "Ice Age",
    "4bb": "Fourth Edition Foreign Black Border",
    "4ed": "Fourth Edition",
    "pmei": "Magazine Inserts",
    "plgm": "DCI Legend Membership",
    "fem": "Fallen Empires",
    "phpr": "HarperPrism Book Promos",
    "drk": "The Dark",
    "pdrc": "Dragon Con",
    "sum": "Summer Magic / Edgar",
    "leg": "Legends",
    "fbb": "Foreign Black Border",
    "3ed": "Revised Edition",
    "atq": "Antiquities",
    "arn": "Arabian Nights",
    "cei": "Intl. Collectors’ Edition",
    "ced": "Collectors’ Edition",
    "2ed": "Unlimited Edition",
    "leb": "Limited Edition Beta",
    "lea": "Limited Edition Alpha",
}