#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['tormor']

package_data = \
{'': ['*'],
 'tormor': ['tests/*',
            'tests/Schema/*',
            'tests/Schema/customer/*',
            'tests/Schema/employee/*',
            'tests/Schema/product/*',
            'tests/Schema2/*',
            'tests/Schema2/customer/*',
            'tests/Schema2/department/*']}

install_requires = \
['asyncpg==0.18.3', 'click==7.0']

extras_require = \
{'test': ['coverage==4.5.1', 'pytest==3.6.3']}

entry_points = \
{'console_scripts': ['tormor = tormor.main_script:script']}

setup(name='tormor',
      version='2.4',
      description='Database migration helper',
      author='Tle Ekkul',
      author_email='e.aryuth@gmail.com',
      url='https://github.com/Proteus-tech/tormor',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='~=3.6',
     )
