- hosts: all
  name: Autoconverted job legacy-networking-generic-switch-dsvm-tempest from old job
    gate-networking-generic-switch-dsvm-tempest
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              https://opendev.org \
              openstack/devstack-gate
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          cat << 'EOF' >>"/tmp/dg-local.conf"
          [[local|localrc]]
          enable_plugin networking-generic-switch https://opendev.org/openstack/networking-generic-switch
          OVS_PHYSICAL_BRIDGE=brbm
          PHYSICAL_NETWORK=mynetwork
          Q_PLUGIN=ml2
          ENABLE_TENANT_VLANS=True
          Q_ML2_TENANT_NETWORK_TYPE=vlan
          TENANT_VLAN_RANGE=100:150
          # test with DLM support enabled
          GENERIC_SWITCH_USER_MAX_SESSIONS=2

          EOF
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_NEUTRON=1
          export DEVSTACK_GATE_TEMPEST_ALL_PLUGINS=1
          export DEVSTACK_GATE_TEMPEST_REGEX='ngs'
          export BRANCH_OVERRIDE=default
          export OVERRIDE_ENABLED_SERVICES=key,mysql,rabbit,q-svc,q-agt,q-dhcp,q-l3,tempest,etcd3
          export DEVSTACK_GATE_REMOVE_STACK_SUDO=0
          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi

          export PROJECTS="openstack/networking-generic-switch $PROJECTS"

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
