part_one_fields = (
    "screening_consent",
    "report_datetime",
    "hospital_identifier",
    "initials",
    "gender",
    "age_in_years",
    "ethnicity",
    "hiv_pos",
    "art_six_months",
    "on_rx_stable",
    "lives_nearby",
    "staying_nearby",
    "pregnant",
    "consent_ability",
)

part_two_fields = (
    "part_two_report_datetime",
    "urine_bhcg_performed",
    "urine_bhcg",
    "urine_bhcg_date",
    "congestive_heart_failure",
    "liver_disease",
    "alcoholism",
    "acute_metabolic_acidosis",
    "renal_function_condition",
    "tissue_hypoxia_condition",
    "acute_condition",
    "metformin_sensitivity",
    "advised_to_fast",
    "appt_datetime",
)

part_three_fields = (
    "weight",
    "height",
    "sys_blood_pressure",
    "dia_blood_pressure",
    "hba1c_performed",
    "hba1c",
    "creatinine_performed",
    "creatinine",
    "creatinine_units",
    "fasted",
    "fasted_duration_str",
    "fasting_glucose",
    "fasting_glucose_datetime",
    "ogtt_base_datetime",
    "ogtt_two_hr",
    "ogtt_two_hr_units",
    "ogtt_two_hr_datetime",
)
