
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-21T16:34:11-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "54f03cce030896d2effb395517b5caacafa88060",
 "version": "1.4.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
