language: python
python:
- '3.6'
- '3.7'
install:
- pip install pre-commit
script:
- pre-commit run --all-files
after_failure:
- git diff
deploy:
  provider: pypi
  skip_existing: true
  distributions: sdist bdist_wheel
  user: digitronik
  password:
    secure: Npfvf9zWWnU0hT7HOcjTD4Dl9JoMZeYVhkx+mWCNrxgLVBDSYmBK5nR91OmGSoBmEVi/PMeBHc6WgpLfPmBxFNNuwHpvPPZTC1xkRzR5uTnYoJ0NmGtVtLVWM6si0zYw/wgFDto2qFGowCU0Ps4fX3ZnsygcaF5yl6gV4PT4zwRPNU2dLQBSa6ydmofvDQ9gWHBi4FzjwcCYtthx0X4zzBVKTTITNnkjnFEIkRFN+cDqdD+rwBLHrAfUnxJ2wifmXHUvV1MNj61xQl/eMLOqmlJClG5CcP7cyaIEtlRpBQfFUlaXxHU8ouMuq+1NLcr+Be1jZ/LQo6k3D5Ae4D0flcLYsUk+wGC43zXYpqQ+E7ilWwu3QJQ+07XqURUr1s+h7BWlL02zBczxV4V9W8+RfdmKIt/OvMHEt8dndgFywqd2tLe4wbXl3m+s98MxVZuXKpJdWoX8bjbgNzDiqdvbgexOlrkMf4772N9yUsh4GvY+5oEa+SQss7mJlvdgloWWTCCUPN5Ln9vIlVCMNEGtcdA1YmJYvbiSP7JvjoGNcJICe7LoG1y0ZdG1OQtkesRmytjDOe1v08/YUfyyfYUD/iYdfjD+rlfJLhfYd8WB8SiooCazkV+GXN10Nl+ii9xW6oRtSa99kACptFrJDeK6Cr57cVWzW1jE/p+eWKq6nmk=
  on:
    tags: true
    repo: digitronik/linkstatus
