
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-16T11:50:12-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "2a2ccb931942e73f4fd7fc6db09b60604a5ef621",
 "version": "v0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
