# Autogenerated by Astropy-affiliated package ligo.skymap's setup.py on 2019-10-30 18:58:14 UTC
from __future__ import unicode_literals
import datetime

version = "0.1.13"
githash = "df269985454463e9ffad59712494dbe3f2712807"


major = 0
minor = 1
bugfix = 13

version_info = (major, minor, bugfix)

release = True
timestamp = datetime.datetime(2019, 10, 30, 18, 58, 14)
debug = False

astropy_helpers_version = "3.1"
