'''Package Metadata'''

__title__ = 'funcgen'
__description__ = 'Function and function signature generation tools.'
__url__ = ''
__version__ = '0.0.0'
__author__ = 'Conrad Bailey'
__author_email__ = 'conrad@cbailey.tech'
__license__ = 'MIT'
__copyright__ = 'Copyright 2019 Conrad Bailey'
