language: python
#python:
#  #  - "2.6"
#  - "2.7"
#  # - "3.2"
#  # - "3.3"
#  - "2.7"
python:
  - 3.6

matrix:
  include:
#  - os: linux
#    name: PEP8 MyPy Coverage
#    python: 3.7
#    install: pip install -e .[tests,cov]
#    script:
#    - flake8
#    - mypy .
#    - pytest --cov
  - os: osx
    language: minimal
    name: osx python36
    env:
      - CONDA_PYTHON_VERSION=3.6
  - os: osx
    language: minimal
    name: osx python37
    env:
      - CONDA_PYTHON_VERSION=3.7
    #    services:
    #      - xvfb
#    before_install:
#      - wget http://home.zcu.cz/~mjirik/lisa/install/install_conda.sh && source install_conda.sh
#      - "export DISPLAY=:99.0"
#    install: pip3 install -e .[tests]
  - os: windows
    language: minimal
#    env:
#      - CONDA_PYTHON_VERSION=3.6
    before_install:
#    - choco install miniconda3
      - choco install miniconda3 --params="'/AddToPath:1'"
      - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"

#matrix:
  allow_failures:
    - env: CONDA_PYTHON_VERSION=2.7
#    - env: CONDA_PYTHON_VERSION=3.7
    - os: windows
  fast_finish: true

os:
  - linux
#  - osx:
#      - language: minimal

#  - windows
services:
  - xvfb
before_install:
  - wget http://home.zcu.cz/~mjirik/lisa/install/install_conda.sh && source install_conda.sh
  - "export DISPLAY=:99.0"

env:
  - CONDA_PYTHON_VERSION=3.6
  - CONDA_PYTHON_VERSION=3.7
#  - CONDA_PYTHON_VERSION=2.7
install:
    - conda update --yes conda
    - conda create --yes -n travis python=$CONDA_PYTHON_VERSION
#    - conda install --yes -n travis pip nose coverage
    - conda install --yes -n travis --file requirements_conda.txt python=$CONDA_PYTHON_VERSION
    - source activate travis
    - conda install -y -c conda-forge pytest coveralls pytest-cov python=$CONDA_PYTHON_VERSION
#    - conda install --yes -n travis -c SimpleITK -c luispedro -c mjirik --file requirements_conda.txt
#    - pip install -r requirements_pip.txt
    - conda info -a
    - conda list
# command to run tests
script:
  - source activate travis
  - python -m pytest --cov=sed3/
#after_success:
#  - coveralls

after_success:
  - coveralls
