
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-21T14:19:47+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7e8b7f63b3a9323c84931f63755a56361a6394c4",
 "version": "0.3.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
