# -*- coding: utf-8 -*-
import setuptools

setuptools.setup(
 name="generatorLibCommonsPython3",
 version="1.0.3",
 author="Low Latency",
 author_email="lowlatency-architecture-support@bbva.com",
 description="Common utilities for autogenerated projects using APIRestGenerator and Python 3",
 long_description="Common utilities for autogenerated projects using APIRestGenerator and Python 3",
 url="https://sites.google.com/a/bbva.com/low-latency/architecture-utilities/apirestgenerator",
 packages=setuptools.find_packages(),
 include_package_data=True,
 license="MIT License",
 classifiers=[
    'Development Status :: 3 - Alpha',
    'License :: OSI Approved :: MIT License',
    'Intended Audience :: Developers',
    'Natural Language :: English',
    'Operating System :: OS Independent',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.7',
    'Topic :: Software Development :: Libraries',
    'Topic :: Software Development :: Libraries :: Python Modules',
 ]
)