# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changepwd.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_changepwdDialog(object):
    def setupUi(self, changepwdDialog):
        changepwdDialog.setObjectName("changepwdDialog")
        changepwdDialog.resize(485, 344)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/edit-user.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        changepwdDialog.setWindowIcon(icon)
        self.changepwdButtonBox = QtWidgets.QDialogButtonBox(changepwdDialog)
        self.changepwdButtonBox.setGeometry(QtCore.QRect(260, 290, 191, 32))
        self.changepwdButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.changepwdButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.changepwdButtonBox.setObjectName("changepwdButtonBox")
        self.label = QtWidgets.QLabel(changepwdDialog)
        self.label.setGeometry(QtCore.QRect(220, 20, 221, 31))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/bristo_logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.changepwdTabWidget = QtWidgets.QTabWidget(changepwdDialog)
        self.changepwdTabWidget.setGeometry(QtCore.QRect(50, 70, 401, 191))
        self.changepwdTabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.changepwdTabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.changepwdTabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.changepwdTabWidget.setMovable(False)
        self.changepwdTabWidget.setObjectName("changepwdTabWidget")
        self.userTab = QtWidgets.QWidget()
        self.userTab.setAutoFillBackground(False)
        self.userTab.setObjectName("userTab")
        self.layoutWidget = QtWidgets.QWidget(self.userTab)
        self.layoutWidget.setGeometry(QtCore.QRect(18, 49, 361, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.userNameLabel = QtWidgets.QLabel(self.layoutWidget)
        self.userNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.userNameLabel.setObjectName("userNameLabel")
        self.horizontalLayout.addWidget(self.userNameLabel)
        self.userNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.userNameLineEdit.setStyleSheet("background-color: rgb(255, 252, 213);")
        self.userNameLineEdit.setObjectName("userNameLineEdit")
        self.horizontalLayout.addWidget(self.userNameLineEdit)
        self.changepwdTabWidget.addTab(self.userTab, icon, "")
        self.passwordTab = QtWidgets.QWidget()
        self.passwordTab.setObjectName("passwordTab")
        self.layoutWidget1 = QtWidgets.QWidget(self.passwordTab)
        self.layoutWidget1.setGeometry(QtCore.QRect(1, 7, 391, 151))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.oldPasswordLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.oldPasswordLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.oldPasswordLabel.setObjectName("oldPasswordLabel")
        self.gridLayout.addWidget(self.oldPasswordLabel, 0, 0, 1, 1)
        self.oldPasswordLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.oldPasswordLineEdit.setStyleSheet("background-color: rgb(126, 154, 255);")
        self.oldPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.oldPasswordLineEdit.setObjectName("oldPasswordLineEdit")
        self.gridLayout.addWidget(self.oldPasswordLineEdit, 0, 1, 1, 1)
        self.newPasswordLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.newPasswordLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.newPasswordLabel.setObjectName("newPasswordLabel")
        self.gridLayout.addWidget(self.newPasswordLabel, 1, 0, 1, 1)
        self.newPasswordLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.newPasswordLineEdit.setStyleSheet("background-color: rgb(126, 154, 255);")
        self.newPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.newPasswordLineEdit.setObjectName("newPasswordLineEdit")
        self.gridLayout.addWidget(self.newPasswordLineEdit, 1, 1, 1, 1)
        self.reenterPasswordLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.reenterPasswordLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.reenterPasswordLabel.setObjectName("reenterPasswordLabel")
        self.gridLayout.addWidget(self.reenterPasswordLabel, 2, 0, 1, 1)
        self.reenterPasswordLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.reenterPasswordLineEdit.setStyleSheet("background-color: rgb(126, 154, 255);")
        self.reenterPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.reenterPasswordLineEdit.setObjectName("reenterPasswordLineEdit")
        self.gridLayout.addWidget(self.reenterPasswordLineEdit, 2, 1, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/lock.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.changepwdTabWidget.addTab(self.passwordTab, icon1, "")
        self.changePasswordLabel = QtWidgets.QLabel(changepwdDialog)
        self.changePasswordLabel.setGeometry(QtCore.QRect(20, 30, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.changePasswordLabel.setFont(font)
        self.changePasswordLabel.setObjectName("changePasswordLabel")
        self.userNameLabel.setBuddy(self.userNameLineEdit)
        self.oldPasswordLabel.setBuddy(self.oldPasswordLineEdit)
        self.newPasswordLabel.setBuddy(self.newPasswordLineEdit)
        self.reenterPasswordLabel.setBuddy(self.reenterPasswordLineEdit)

        self.retranslateUi(changepwdDialog)
        self.changepwdTabWidget.setCurrentIndex(0)
        self.changepwdButtonBox.accepted.connect(changepwdDialog.accept)
        self.changepwdButtonBox.rejected.connect(changepwdDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(changepwdDialog)

    def retranslateUi(self, changepwdDialog):
        _translate = QtCore.QCoreApplication.translate
        changepwdDialog.setWindowTitle(_translate("changepwdDialog", "bristoSOFT-Change Password"))
        self.userNameLabel.setText(_translate("changepwdDialog", "Username:"))
        self.changepwdTabWidget.setTabText(self.changepwdTabWidget.indexOf(self.userTab), _translate("changepwdDialog", "User"))
        self.oldPasswordLabel.setText(_translate("changepwdDialog", "Old Password:"))
        self.newPasswordLabel.setText(_translate("changepwdDialog", "New Password:"))
        self.reenterPasswordLabel.setText(_translate("changepwdDialog", "Re-Enter New:"))
        self.changepwdTabWidget.setTabText(self.changepwdTabWidget.indexOf(self.passwordTab), _translate("changepwdDialog", "Password"))
        self.changePasswordLabel.setText(_translate("changepwdDialog", "Change Password:"))

from . import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    changepwdDialog = QtWidgets.QDialog()
    ui = Ui_changepwdDialog()
    ui.setupUi(changepwdDialog)
    changepwdDialog.show()
    sys.exit(app.exec_())

