# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contacts.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_contactsDialog(object):
    def setupUi(self, contactsDialog):
        contactsDialog.setObjectName("contactsDialog")
        contactsDialog.resize(633, 631)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/edit-user.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        contactsDialog.setWindowIcon(icon)
        contactsDialog.setWindowOpacity(1.0)
        contactsDialog.setStyleSheet("")
        self.nameFrame = QtWidgets.QFrame(contactsDialog)
        self.nameFrame.setGeometry(QtCore.QRect(10, 10, 611, 141))
        self.nameFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nameFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nameFrame.setObjectName("nameFrame")
        self.layoutWidget = QtWidgets.QWidget(self.nameFrame)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 91, 591, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.credLabel = QtWidgets.QLabel(self.layoutWidget)
        self.credLabel.setObjectName("credLabel")
        self.horizontalLayout_3.addWidget(self.credLabel)
        self.credLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.credLineEdit.setStyleSheet("background-color: rgb(211, 213, 244);")
        self.credLineEdit.setObjectName("credLineEdit")
        self.horizontalLayout_3.addWidget(self.credLineEdit)
        self.layoutWidget1 = QtWidgets.QWidget(self.nameFrame)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 50, 591, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mrmrsLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.mrmrsLabel.setMaximumSize(QtCore.QSize(55, 16777215))
        self.mrmrsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mrmrsLabel.setObjectName("mrmrsLabel")
        self.horizontalLayout_2.addWidget(self.mrmrsLabel)
        self.mrmrsLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.mrmrsLineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.mrmrsLineEdit.setStyleSheet("background-color: rgb(211, 213, 244);")
        self.mrmrsLineEdit.setObjectName("mrmrsLineEdit")
        self.horizontalLayout_2.addWidget(self.mrmrsLineEdit)
        self.firstnameLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.firstnameLabel.setMaximumSize(QtCore.QSize(40, 16777215))
        self.firstnameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.firstnameLabel.setObjectName("firstnameLabel")
        self.horizontalLayout_2.addWidget(self.firstnameLabel)
        self.firstNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.firstNameLineEdit.setMaximumSize(QtCore.QSize(160, 16777215))
        self.firstNameLineEdit.setStyleSheet("background-color: rgb(211, 213, 244);")
        self.firstNameLineEdit.setObjectName("firstNameLineEdit")
        self.horizontalLayout_2.addWidget(self.firstNameLineEdit)
        self.middleNameLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.middleNameLabel.setMaximumSize(QtCore.QSize(30, 16777215))
        self.middleNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.middleNameLabel.setObjectName("middleNameLabel")
        self.horizontalLayout_2.addWidget(self.middleNameLabel)
        self.middleNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.middleNameLineEdit.sizePolicy().hasHeightForWidth())
        self.middleNameLineEdit.setSizePolicy(sizePolicy)
        self.middleNameLineEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.middleNameLineEdit.setStyleSheet("background-color: rgb(211, 213, 244);")
        self.middleNameLineEdit.setObjectName("middleNameLineEdit")
        self.horizontalLayout_2.addWidget(self.middleNameLineEdit)
        self.lastNameLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.lastNameLabel.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lastNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lastNameLabel.setObjectName("lastNameLabel")
        self.horizontalLayout_2.addWidget(self.lastNameLabel)
        self.lastNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lastNameLineEdit.setMaximumSize(QtCore.QSize(160, 16777215))
        self.lastNameLineEdit.setStyleSheet("background-color: rgb(211, 213, 244);")
        self.lastNameLineEdit.setObjectName("lastNameLineEdit")
        self.horizontalLayout_2.addWidget(self.lastNameLineEdit)
        self.layoutWidget2 = QtWidgets.QWidget(self.nameFrame)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 591, 41))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.companyLabel = QtWidgets.QLabel(self.layoutWidget2)
        self.companyLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.companyLabel.setObjectName("companyLabel")
        self.horizontalLayout.addWidget(self.companyLabel)
        self.companyLineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.companyLineEdit.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.companyLineEdit.setObjectName("companyLineEdit")
        self.horizontalLayout.addWidget(self.companyLineEdit)
        self.contactTabWidget = QtWidgets.QTabWidget(contactsDialog)
        self.contactTabWidget.setGeometry(QtCore.QRect(10, 170, 611, 411))
        self.contactTabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.contactTabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.contactTabWidget.setTabsClosable(False)
        self.contactTabWidget.setMovable(True)
        self.contactTabWidget.setObjectName("contactTabWidget")
        self.contactTab = QtWidgets.QWidget()
        self.contactTab.setObjectName("contactTab")
        self.line_2 = QtWidgets.QFrame(self.contactTab)
        self.line_2.setGeometry(QtCore.QRect(310, 20, 20, 151))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.contactTab)
        self.line_3.setGeometry(QtCore.QRect(20, 170, 571, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.layoutWidget3 = QtWidgets.QWidget(self.contactTab)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 190, 591, 179))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.officeEmailLabel = QtWidgets.QLabel(self.layoutWidget3)
        self.officeEmailLabel.setObjectName("officeEmailLabel")
        self.gridLayout_3.addWidget(self.officeEmailLabel, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.officeEmailLineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.officeEmailLineEdit.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.officeEmailLineEdit.setObjectName("officeEmailLineEdit")
        self.gridLayout_3.addWidget(self.officeEmailLineEdit, 0, 1, 1, 1)
        self.personalEmailLabel = QtWidgets.QLabel(self.layoutWidget3)
        self.personalEmailLabel.setObjectName("personalEmailLabel")
        self.gridLayout_3.addWidget(self.personalEmailLabel, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.personalEmailLineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.personalEmailLineEdit.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.personalEmailLineEdit.setObjectName("personalEmailLineEdit")
        self.gridLayout_3.addWidget(self.personalEmailLineEdit, 1, 1, 1, 1)
        self.officeWebLabel = QtWidgets.QLabel(self.layoutWidget3)
        self.officeWebLabel.setObjectName("officeWebLabel")
        self.gridLayout_3.addWidget(self.officeWebLabel, 2, 0, 1, 1, QtCore.Qt.AlignRight)
        self.officeWebLineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.officeWebLineEdit.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.officeWebLineEdit.setObjectName("officeWebLineEdit")
        self.gridLayout_3.addWidget(self.officeWebLineEdit, 2, 1, 1, 1)
        self.personalWebLabel = QtWidgets.QLabel(self.layoutWidget3)
        self.personalWebLabel.setObjectName("personalWebLabel")
        self.gridLayout_3.addWidget(self.personalWebLabel, 3, 0, 1, 1, QtCore.Qt.AlignRight)
        self.personalWebLineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.personalWebLineEdit.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.personalWebLineEdit.setObjectName("personalWebLineEdit")
        self.gridLayout_3.addWidget(self.personalWebLineEdit, 3, 1, 1, 1)
        self.picFrame = QtWidgets.QFrame(self.contactTab)
        self.picFrame.setGeometry(QtCore.QRect(370, 20, 161, 151))
        self.picFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.picFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.picFrame.setObjectName("picFrame")
        self.picLabel = QtWidgets.QLabel(self.picFrame)
        self.picLabel.setGeometry(QtCore.QRect(10, 10, 141, 131))
        self.picLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.picLabel.setText("")
        self.picLabel.setPixmap(QtGui.QPixmap("default.jpg"))
        self.picLabel.setScaledContents(True)
        self.picLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.picLabel.setObjectName("picLabel")
        self.layoutWidget4 = QtWidgets.QWidget(self.contactTab)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 20, 301, 151))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cellPhoneLabel = QtWidgets.QLabel(self.layoutWidget4)
        self.cellPhoneLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cellPhoneLabel.setObjectName("cellPhoneLabel")
        self.gridLayout_2.addWidget(self.cellPhoneLabel, 0, 0, 1, 1)
        self.cellPhoneLineEdit = QtWidgets.QLineEdit(self.layoutWidget4)
        self.cellPhoneLineEdit.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.cellPhoneLineEdit.setObjectName("cellPhoneLineEdit")
        self.gridLayout_2.addWidget(self.cellPhoneLineEdit, 0, 1, 1, 1)
        self.homePhoneLabel = QtWidgets.QLabel(self.layoutWidget4)
        self.homePhoneLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.homePhoneLabel.setObjectName("homePhoneLabel")
        self.gridLayout_2.addWidget(self.homePhoneLabel, 1, 0, 1, 1)
        self.homePhoneLineEdit = QtWidgets.QLineEdit(self.layoutWidget4)
        self.homePhoneLineEdit.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.homePhoneLineEdit.setObjectName("homePhoneLineEdit")
        self.gridLayout_2.addWidget(self.homePhoneLineEdit, 1, 1, 1, 1)
        self.officePhoneLabel = QtWidgets.QLabel(self.layoutWidget4)
        self.officePhoneLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.officePhoneLabel.setObjectName("officePhoneLabel")
        self.gridLayout_2.addWidget(self.officePhoneLabel, 2, 0, 1, 1)
        self.officePhoneLineEdit = QtWidgets.QLineEdit(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.officePhoneLineEdit.sizePolicy().hasHeightForWidth())
        self.officePhoneLineEdit.setSizePolicy(sizePolicy)
        self.officePhoneLineEdit.setStyleSheet("background-color: rgb(211, 213, 244);")
        self.officePhoneLineEdit.setObjectName("officePhoneLineEdit")
        self.gridLayout_2.addWidget(self.officePhoneLineEdit, 2, 1, 1, 1)
        self.officeFaxLabel = QtWidgets.QLabel(self.layoutWidget4)
        self.officeFaxLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.officeFaxLabel.setObjectName("officeFaxLabel")
        self.gridLayout_2.addWidget(self.officeFaxLabel, 3, 0, 1, 1)
        self.officeFaxLineEdit = QtWidgets.QLineEdit(self.layoutWidget4)
        self.officeFaxLineEdit.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.officeFaxLineEdit.setObjectName("officeFaxLineEdit")
        self.gridLayout_2.addWidget(self.officeFaxLineEdit, 3, 1, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/contact-new-2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contactTabWidget.addTab(self.contactTab, icon1, "")
        self.addressTab = QtWidgets.QWidget()
        self.addressTab.setObjectName("addressTab")
        self.frame = QtWidgets.QFrame(self.addressTab)
        self.frame.setGeometry(QtCore.QRect(10, 10, 581, 271))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.layoutWidget5 = QtWidgets.QWidget(self.frame)
        self.layoutWidget5.setGeometry(QtCore.QRect(20, 30, 541, 221))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.addressLlabel = QtWidgets.QLabel(self.layoutWidget5)
        self.addressLlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.addressLlabel.setObjectName("addressLlabel")
        self.gridLayout.addWidget(self.addressLlabel, 0, 0, 1, 1)
        self.addressLineEdit = QtWidgets.QLineEdit(self.layoutWidget5)
        self.addressLineEdit.setStyleSheet("background-color: rgb(215, 255, 208);")
        self.addressLineEdit.setObjectName("addressLineEdit")
        self.gridLayout.addWidget(self.addressLineEdit, 0, 1, 1, 1)
        self.suiteLabel = QtWidgets.QLabel(self.layoutWidget5)
        self.suiteLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.suiteLabel.setObjectName("suiteLabel")
        self.gridLayout.addWidget(self.suiteLabel, 1, 0, 1, 1)
        self.suiteLineEdit = QtWidgets.QLineEdit(self.layoutWidget5)
        self.suiteLineEdit.setStyleSheet("background-color: rgb(215, 255, 208);")
        self.suiteLineEdit.setObjectName("suiteLineEdit")
        self.gridLayout.addWidget(self.suiteLineEdit, 1, 1, 1, 1)
        self.cityLabel = QtWidgets.QLabel(self.layoutWidget5)
        self.cityLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cityLabel.setObjectName("cityLabel")
        self.gridLayout.addWidget(self.cityLabel, 2, 0, 1, 1)
        self.cityLineEdit = QtWidgets.QLineEdit(self.layoutWidget5)
        self.cityLineEdit.setStyleSheet("background-color: rgb(215, 255, 208);")
        self.cityLineEdit.setObjectName("cityLineEdit")
        self.gridLayout.addWidget(self.cityLineEdit, 2, 1, 1, 1)
        self.stateLabel = QtWidgets.QLabel(self.layoutWidget5)
        self.stateLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stateLabel.setObjectName("stateLabel")
        self.gridLayout.addWidget(self.stateLabel, 3, 0, 1, 1)
        self.stateLineEdit = QtWidgets.QLineEdit(self.layoutWidget5)
        self.stateLineEdit.setStyleSheet("background-color: rgb(215, 255, 208);")
        self.stateLineEdit.setObjectName("stateLineEdit")
        self.gridLayout.addWidget(self.stateLineEdit, 3, 1, 1, 1)
        self.postalLabel = QtWidgets.QLabel(self.layoutWidget5)
        self.postalLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.postalLabel.setObjectName("postalLabel")
        self.gridLayout.addWidget(self.postalLabel, 4, 0, 1, 1)
        self.postalLineEdit = QtWidgets.QLineEdit(self.layoutWidget5)
        self.postalLineEdit.setStyleSheet("background-color: rgb(215, 255, 208);")
        self.postalLineEdit.setObjectName("postalLineEdit")
        self.gridLayout.addWidget(self.postalLineEdit, 4, 1, 1, 1)
        self.layoutWidget6 = QtWidgets.QWidget(self.addressTab)
        self.layoutWidget6.setGeometry(QtCore.QRect(200, 290, 391, 41))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.copyGroupAddressLabel = QtWidgets.QLabel(self.layoutWidget6)
        self.copyGroupAddressLabel.setObjectName("copyGroupAddressLabel")
        self.horizontalLayout_4.addWidget(self.copyGroupAddressLabel)
        self.copyGroupAddressLineEdit = QtWidgets.QLineEdit(self.layoutWidget6)
        self.copyGroupAddressLineEdit.setObjectName("copyGroupAddressLineEdit")
        self.horizontalLayout_4.addWidget(self.copyGroupAddressLineEdit)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/address-book-new-2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contactTabWidget.addTab(self.addressTab, icon2, "")
        self.line = QtWidgets.QFrame(contactsDialog)
        self.line.setGeometry(QtCore.QRect(10, 150, 611, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.savePushButton = QtWidgets.QPushButton(contactsDialog)
        self.savePushButton.setGeometry(QtCore.QRect(525, 590, 99, 27))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/db_add.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.savePushButton.setIcon(icon3)
        self.savePushButton.setObjectName("savePushButton")
        self.cancelPushButton = QtWidgets.QPushButton(contactsDialog)
        self.cancelPushButton.setGeometry(QtCore.QRect(420, 590, 99, 27))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/process-stop-5.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.cancelPushButton.setIcon(icon4)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.label = QtWidgets.QLabel(contactsDialog)
        self.label.setGeometry(QtCore.QRect(10, 590, 161, 21))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/icons/bristo_logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.credLabel.setBuddy(self.credLineEdit)
        self.mrmrsLabel.setBuddy(self.mrmrsLineEdit)
        self.firstnameLabel.setBuddy(self.firstNameLineEdit)
        self.middleNameLabel.setBuddy(self.middleNameLineEdit)
        self.lastNameLabel.setBuddy(self.lastNameLineEdit)
        self.companyLabel.setBuddy(self.companyLineEdit)
        self.officeEmailLabel.setBuddy(self.officeEmailLineEdit)
        self.personalEmailLabel.setBuddy(self.personalEmailLineEdit)
        self.officeWebLabel.setBuddy(self.officeWebLineEdit)
        self.personalWebLabel.setBuddy(self.personalWebLineEdit)
        self.cellPhoneLabel.setBuddy(self.cellPhoneLineEdit)
        self.homePhoneLabel.setBuddy(self.homePhoneLineEdit)
        self.officePhoneLabel.setBuddy(self.officePhoneLineEdit)
        self.officeFaxLabel.setBuddy(self.officeFaxLineEdit)
        self.addressLlabel.setBuddy(self.addressLineEdit)
        self.suiteLabel.setBuddy(self.suiteLineEdit)
        self.cityLabel.setBuddy(self.cityLineEdit)
        self.stateLabel.setBuddy(self.stateLineEdit)
        self.postalLabel.setBuddy(self.postalLineEdit)
        self.copyGroupAddressLabel.setBuddy(self.copyGroupAddressLineEdit)

        self.retranslateUi(contactsDialog)
        self.contactTabWidget.setCurrentIndex(0)
        self.savePushButton.clicked.connect(contactsDialog.accept)
        self.cancelPushButton.clicked.connect(contactsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(contactsDialog)
        contactsDialog.setTabOrder(self.companyLineEdit, self.mrmrsLineEdit)
        contactsDialog.setTabOrder(self.mrmrsLineEdit, self.firstNameLineEdit)
        contactsDialog.setTabOrder(self.firstNameLineEdit, self.middleNameLineEdit)
        contactsDialog.setTabOrder(self.middleNameLineEdit, self.lastNameLineEdit)
        contactsDialog.setTabOrder(self.lastNameLineEdit, self.credLineEdit)
        contactsDialog.setTabOrder(self.credLineEdit, self.cellPhoneLineEdit)
        contactsDialog.setTabOrder(self.cellPhoneLineEdit, self.homePhoneLineEdit)
        contactsDialog.setTabOrder(self.homePhoneLineEdit, self.officePhoneLineEdit)
        contactsDialog.setTabOrder(self.officePhoneLineEdit, self.officeFaxLineEdit)
        contactsDialog.setTabOrder(self.officeFaxLineEdit, self.officeEmailLineEdit)
        contactsDialog.setTabOrder(self.officeEmailLineEdit, self.personalEmailLineEdit)
        contactsDialog.setTabOrder(self.personalEmailLineEdit, self.officeWebLineEdit)
        contactsDialog.setTabOrder(self.officeWebLineEdit, self.personalWebLineEdit)
        contactsDialog.setTabOrder(self.personalWebLineEdit, self.addressLineEdit)
        contactsDialog.setTabOrder(self.addressLineEdit, self.suiteLineEdit)
        contactsDialog.setTabOrder(self.suiteLineEdit, self.cityLineEdit)
        contactsDialog.setTabOrder(self.cityLineEdit, self.stateLineEdit)
        contactsDialog.setTabOrder(self.stateLineEdit, self.postalLineEdit)
        contactsDialog.setTabOrder(self.postalLineEdit, self.savePushButton)
        contactsDialog.setTabOrder(self.savePushButton, self.cancelPushButton)
        contactsDialog.setTabOrder(self.cancelPushButton, self.contactTabWidget)

    def retranslateUi(self, contactsDialog):
        _translate = QtCore.QCoreApplication.translate
        contactsDialog.setWindowTitle(_translate("contactsDialog", "Contacts Dialog"))
        self.credLabel.setText(_translate("contactsDialog", "Title:"))
        self.mrmrsLabel.setText(_translate("contactsDialog", "Mr/Mrs:"))
        self.firstnameLabel.setText(_translate("contactsDialog", "First :"))
        self.middleNameLabel.setText(_translate("contactsDialog", "M:"))
        self.lastNameLabel.setText(_translate("contactsDialog", "Last:"))
        self.companyLabel.setText(_translate("contactsDialog", "Company/Organization:"))
        self.officeEmailLabel.setText(_translate("contactsDialog", "Office Email:"))
        self.personalEmailLabel.setText(_translate("contactsDialog", "Personal Email:"))
        self.officeWebLabel.setText(_translate("contactsDialog", "Office Web:"))
        self.personalWebLabel.setText(_translate("contactsDialog", "Personal Web:"))
        self.cellPhoneLabel.setText(_translate("contactsDialog", "Cell Phone:"))
        self.homePhoneLabel.setText(_translate("contactsDialog", "Home Phone:"))
        self.officePhoneLabel.setText(_translate("contactsDialog", "Office Phone:"))
        self.officeFaxLabel.setText(_translate("contactsDialog", "Office Fax:"))
        self.contactTabWidget.setTabText(self.contactTabWidget.indexOf(self.contactTab), _translate("contactsDialog", "Contact"))
        self.addressLlabel.setText(_translate("contactsDialog", "Address:"))
        self.suiteLabel.setText(_translate("contactsDialog", "Suite/ Floor:"))
        self.cityLabel.setText(_translate("contactsDialog", "City:"))
        self.stateLabel.setText(_translate("contactsDialog", "State/Province:"))
        self.postalLabel.setText(_translate("contactsDialog", "Zip:"))
        self.copyGroupAddressLabel.setText(_translate("contactsDialog", "Enter Group Name to copy:"))
        self.contactTabWidget.setTabText(self.contactTabWidget.indexOf(self.addressTab), _translate("contactsDialog", "Office Address"))
        self.savePushButton.setText(_translate("contactsDialog", "Save"))
        self.cancelPushButton.setText(_translate("contactsDialog", "Cancel"))

from . import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    contactsDialog = QtWidgets.QDialog()
    ui = Ui_contactsDialog()
    ui.setupUi(contactsDialog)
    contactsDialog.show()
    sys.exit(app.exec_())

