# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newgroup.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_newGroupDialog(object):
    def setupUi(self, newGroupDialog):
        newGroupDialog.setObjectName("newGroupDialog")
        newGroupDialog.resize(632, 655)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/edit-user.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        newGroupDialog.setWindowIcon(icon)
        newGroupDialog.setWindowOpacity(1.0)
        newGroupDialog.setStyleSheet("")
        self.credentialsFrame = QtWidgets.QFrame(newGroupDialog)
        self.credentialsFrame.setGeometry(QtCore.QRect(10, 10, 611, 181))
        self.credentialsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.credentialsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.credentialsFrame.setObjectName("credentialsFrame")
        self.layoutWidget = QtWidgets.QWidget(self.credentialsFrame)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 14, 591, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupLabel = QtWidgets.QLabel(self.layoutWidget)
        self.groupLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupLabel.setObjectName("groupLabel")
        self.gridLayout.addWidget(self.groupLabel, 0, 0, 1, 1)
        self.newGroupLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.newGroupLineEdit.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.newGroupLineEdit.setObjectName("newGroupLineEdit")
        self.gridLayout.addWidget(self.newGroupLineEdit, 0, 1, 1, 1)
        self.passwordLabel = QtWidgets.QLabel(self.layoutWidget)
        self.passwordLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.passwordLabel.setObjectName("passwordLabel")
        self.gridLayout.addWidget(self.passwordLabel, 1, 0, 1, 1)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.passwordLineEdit.setStyleSheet("background-color: rgb(153, 204, 255)")
        self.passwordLineEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.gridLayout.addWidget(self.passwordLineEdit, 1, 1, 1, 1)
        self.confirmPasswordLabel = QtWidgets.QLabel(self.layoutWidget)
        self.confirmPasswordLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.confirmPasswordLabel.setObjectName("confirmPasswordLabel")
        self.gridLayout.addWidget(self.confirmPasswordLabel, 2, 0, 1, 1)
        self.confirmPasswordLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.confirmPasswordLineEdit.setStyleSheet("background-color: rgb(153, 204, 255)")
        self.confirmPasswordLineEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.confirmPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmPasswordLineEdit.setObjectName("confirmPasswordLineEdit")
        self.gridLayout.addWidget(self.confirmPasswordLineEdit, 2, 1, 1, 1)
        self.newGroupTabWidget = QtWidgets.QTabWidget(newGroupDialog)
        self.newGroupTabWidget.setGeometry(QtCore.QRect(10, 220, 611, 371))
        self.newGroupTabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.newGroupTabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.newGroupTabWidget.setTabsClosable(False)
        self.newGroupTabWidget.setMovable(True)
        self.newGroupTabWidget.setObjectName("newGroupTabWidget")
        self.groupDescriptionTab = QtWidgets.QWidget()
        self.groupDescriptionTab.setObjectName("groupDescriptionTab")
        self.descriptionFrame = QtWidgets.QFrame(self.groupDescriptionTab)
        self.descriptionFrame.setGeometry(QtCore.QRect(10, 10, 581, 271))
        self.descriptionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.descriptionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.descriptionFrame.setLineWidth(2)
        self.descriptionFrame.setObjectName("descriptionFrame")
        self.descTextEdit = QtWidgets.QTextEdit(self.descriptionFrame)
        self.descTextEdit.setGeometry(QtCore.QRect(13, 17, 551, 241))
        self.descTextEdit.setStyleSheet("background-color: rgb(245,245,245);")
        self.descTextEdit.setObjectName("descTextEdit")
        self.newGroupLabel = QtWidgets.QLabel(self.groupDescriptionTab)
        self.newGroupLabel.setGeometry(QtCore.QRect(380, 290, 211, 31))
        self.newGroupLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.newGroupLabel.setText("")
        self.newGroupLabel.setPixmap(QtGui.QPixmap("bristo_logo.png"))
        self.newGroupLabel.setScaledContents(True)
        self.newGroupLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.newGroupLabel.setObjectName("newGroupLabel")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/edit-group.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newGroupTabWidget.addTab(self.groupDescriptionTab, icon1, "")
        self.groupAddressTab = QtWidgets.QWidget()
        self.groupAddressTab.setObjectName("groupAddressTab")
        self.groupAddressFrame = QtWidgets.QFrame(self.groupAddressTab)
        self.groupAddressFrame.setGeometry(QtCore.QRect(10, 20, 581, 271))
        self.groupAddressFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.groupAddressFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.groupAddressFrame.setLineWidth(2)
        self.groupAddressFrame.setObjectName("groupAddressFrame")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupAddressFrame)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 20, 541, 221))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupAddressLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.groupAddressLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupAddressLabel.setObjectName("groupAddressLabel")
        self.gridLayout_3.addWidget(self.groupAddressLabel, 0, 0, 1, 1)
        self.groupAddressLineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.groupAddressLineEdit.setStyleSheet("background-color: rgb(215, 255, 208);")
        self.groupAddressLineEdit.setObjectName("groupAddressLineEdit")
        self.gridLayout_3.addWidget(self.groupAddressLineEdit, 0, 1, 1, 1)
        self.groupSuiteLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.groupSuiteLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupSuiteLabel.setObjectName("groupSuiteLabel")
        self.gridLayout_3.addWidget(self.groupSuiteLabel, 1, 0, 1, 1)
        self.groupSuiteLineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.groupSuiteLineEdit.setStyleSheet("background-color: rgb(215, 255, 208);")
        self.groupSuiteLineEdit.setObjectName("groupSuiteLineEdit")
        self.gridLayout_3.addWidget(self.groupSuiteLineEdit, 1, 1, 1, 1)
        self.groupCityLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.groupCityLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupCityLabel.setObjectName("groupCityLabel")
        self.gridLayout_3.addWidget(self.groupCityLabel, 2, 0, 1, 1)
        self.groupCityLineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.groupCityLineEdit.setStyleSheet("background-color: rgb(215, 255, 208);")
        self.groupCityLineEdit.setObjectName("groupCityLineEdit")
        self.gridLayout_3.addWidget(self.groupCityLineEdit, 2, 1, 1, 1)
        self.groupStateLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.groupStateLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupStateLabel.setObjectName("groupStateLabel")
        self.gridLayout_3.addWidget(self.groupStateLabel, 3, 0, 1, 1)
        self.groupStateLineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.groupStateLineEdit.setStyleSheet("background-color: rgb(215, 255, 208);")
        self.groupStateLineEdit.setObjectName("groupStateLineEdit")
        self.gridLayout_3.addWidget(self.groupStateLineEdit, 3, 1, 1, 1)
        self.groupPostalLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.groupPostalLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupPostalLabel.setObjectName("groupPostalLabel")
        self.gridLayout_3.addWidget(self.groupPostalLabel, 4, 0, 1, 1)
        self.groupPostalLineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.groupPostalLineEdit.setStyleSheet("background-color: rgb(215, 255, 208);")
        self.groupPostalLineEdit.setObjectName("groupPostalLineEdit")
        self.gridLayout_3.addWidget(self.groupPostalLineEdit, 4, 1, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/address-book-new-2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newGroupTabWidget.addTab(self.groupAddressTab, icon2, "")
        self.groupContactTab = QtWidgets.QWidget()
        self.groupContactTab.setObjectName("groupContactTab")
        self.groupContactFrame = QtWidgets.QFrame(self.groupContactTab)
        self.groupContactFrame.setGeometry(QtCore.QRect(10, 30, 591, 271))
        self.groupContactFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.groupContactFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.groupContactFrame.setObjectName("groupContactFrame")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupContactFrame)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 20, 551, 231))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupOfficeWebLabel = QtWidgets.QLabel(self.layoutWidget_3)
        self.groupOfficeWebLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupOfficeWebLabel.setObjectName("groupOfficeWebLabel")
        self.gridLayout_4.addWidget(self.groupOfficeWebLabel, 2, 0, 1, 1)
        self.groupOfficeFaxLineEdit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.groupOfficeFaxLineEdit.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.groupOfficeFaxLineEdit.setObjectName("groupOfficeFaxLineEdit")
        self.gridLayout_4.addWidget(self.groupOfficeFaxLineEdit, 1, 1, 1, 1)
        self.groupOfficeWebLineEdit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.groupOfficeWebLineEdit.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.groupOfficeWebLineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.groupOfficeWebLineEdit.setObjectName("groupOfficeWebLineEdit")
        self.gridLayout_4.addWidget(self.groupOfficeWebLineEdit, 2, 1, 1, 1)
        self.groupOfficeFaxLabel = QtWidgets.QLabel(self.layoutWidget_3)
        self.groupOfficeFaxLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupOfficeFaxLabel.setObjectName("groupOfficeFaxLabel")
        self.gridLayout_4.addWidget(self.groupOfficeFaxLabel, 1, 0, 1, 1)
        self.groupOfficePhoneLineEdit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.groupOfficePhoneLineEdit.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.groupOfficePhoneLineEdit.setObjectName("groupOfficePhoneLineEdit")
        self.gridLayout_4.addWidget(self.groupOfficePhoneLineEdit, 0, 1, 1, 1)
        self.groupOtherWebLineEdit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.groupOtherWebLineEdit.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.groupOtherWebLineEdit.setObjectName("groupOtherWebLineEdit")
        self.gridLayout_4.addWidget(self.groupOtherWebLineEdit, 3, 1, 1, 1)
        self.groupOtherWebLabel = QtWidgets.QLabel(self.layoutWidget_3)
        self.groupOtherWebLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupOtherWebLabel.setObjectName("groupOtherWebLabel")
        self.gridLayout_4.addWidget(self.groupOtherWebLabel, 3, 0, 1, 1)
        self.groupOfficePhoneLabel = QtWidgets.QLabel(self.layoutWidget_3)
        self.groupOfficePhoneLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupOfficePhoneLabel.setObjectName("groupOfficePhoneLabel")
        self.gridLayout_4.addWidget(self.groupOfficePhoneLabel, 0, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/contact-new-2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newGroupTabWidget.addTab(self.groupContactTab, icon3, "")
        self.line = QtWidgets.QFrame(newGroupDialog)
        self.line.setGeometry(QtCore.QRect(10, 200, 611, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.savePushButton = QtWidgets.QPushButton(newGroupDialog)
        self.savePushButton.setGeometry(QtCore.QRect(520, 610, 99, 27))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/db_add.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.savePushButton.setIcon(icon4)
        self.savePushButton.setObjectName("savePushButton")
        self.cancelPushButton = QtWidgets.QPushButton(newGroupDialog)
        self.cancelPushButton.setGeometry(QtCore.QRect(415, 610, 99, 27))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/process-stop-5.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.cancelPushButton.setIcon(icon5)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.groupLabel.setBuddy(self.newGroupLineEdit)
        self.passwordLabel.setBuddy(self.passwordLineEdit)
        self.confirmPasswordLabel.setBuddy(self.confirmPasswordLineEdit)
        self.groupAddressLabel.setBuddy(self.groupAddressLineEdit)
        self.groupSuiteLabel.setBuddy(self.groupSuiteLineEdit)
        self.groupCityLabel.setBuddy(self.groupCityLineEdit)
        self.groupStateLabel.setBuddy(self.groupStateLineEdit)
        self.groupPostalLabel.setBuddy(self.groupPostalLineEdit)
        self.groupOfficeWebLabel.setBuddy(self.groupOfficeWebLineEdit)
        self.groupOfficeFaxLabel.setBuddy(self.groupOfficeFaxLineEdit)
        self.groupOtherWebLabel.setBuddy(self.groupOtherWebLineEdit)
        self.groupOfficePhoneLabel.setBuddy(self.groupOfficePhoneLineEdit)

        self.retranslateUi(newGroupDialog)
        self.newGroupTabWidget.setCurrentIndex(2)
        self.savePushButton.clicked.connect(newGroupDialog.accept)
        self.cancelPushButton.clicked.connect(newGroupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(newGroupDialog)
        newGroupDialog.setTabOrder(self.cancelPushButton, self.savePushButton)
        newGroupDialog.setTabOrder(self.savePushButton, self.newGroupTabWidget)

    def retranslateUi(self, newGroupDialog):
        _translate = QtCore.QCoreApplication.translate
        newGroupDialog.setWindowTitle(_translate("newGroupDialog", "New Group Dialog"))
        self.groupLabel.setText(_translate("newGroupDialog", "Group:"))
        self.newGroupLineEdit.setPlaceholderText(_translate("newGroupDialog", "Group name should not include spaces."))
        self.passwordLabel.setText(_translate("newGroupDialog", "Password:"))
        self.passwordLineEdit.setPlaceholderText(_translate("newGroupDialog", "Password m/b 9 char, upper, lower, number and one special character."))
        self.confirmPasswordLabel.setText(_translate("newGroupDialog", "Confirm:"))
        self.confirmPasswordLineEdit.setPlaceholderText(_translate("newGroupDialog", "Please re-enter the password."))
        self.newGroupTabWidget.setTabText(self.newGroupTabWidget.indexOf(self.groupDescriptionTab), _translate("newGroupDialog", "Group Description"))
        self.groupAddressLabel.setText(_translate("newGroupDialog", "Address:"))
        self.groupSuiteLabel.setText(_translate("newGroupDialog", "Suite/ Floor:"))
        self.groupCityLabel.setText(_translate("newGroupDialog", "City:"))
        self.groupStateLabel.setText(_translate("newGroupDialog", "State/Province:"))
        self.groupPostalLabel.setText(_translate("newGroupDialog", "Zip:"))
        self.newGroupTabWidget.setTabText(self.newGroupTabWidget.indexOf(self.groupAddressTab), _translate("newGroupDialog", "Address"))
        self.groupOfficeWebLabel.setText(_translate("newGroupDialog", "Office Web:"))
        self.groupOfficeFaxLabel.setText(_translate("newGroupDialog", "Office Fax:"))
        self.groupOtherWebLabel.setText(_translate("newGroupDialog", "Other Web:"))
        self.groupOfficePhoneLabel.setText(_translate("newGroupDialog", "Office Phone:"))
        self.newGroupTabWidget.setTabText(self.newGroupTabWidget.indexOf(self.groupContactTab), _translate("newGroupDialog", "Contact"))
        self.savePushButton.setText(_translate("newGroupDialog", "Save"))
        self.cancelPushButton.setText(_translate("newGroupDialog", "Cancel"))

from . import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    newGroupDialog = QtWidgets.QDialog()
    ui = Ui_newGroupDialog()
    ui.setupUi(newGroupDialog)
    newGroupDialog.show()
    sys.exit(app.exec_())

