# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searchgroup.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_searchGroupDialog(object):
    def setupUi(self, searchGroupDialog):
        searchGroupDialog.setObjectName("searchGroupDialog")
        searchGroupDialog.resize(632, 655)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/edit-user.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        searchGroupDialog.setWindowIcon(icon)
        searchGroupDialog.setWindowOpacity(1.0)
        searchGroupDialog.setStyleSheet("")
        self.credentialsFrame = QtWidgets.QFrame(searchGroupDialog)
        self.credentialsFrame.setGeometry(QtCore.QRect(10, 10, 611, 181))
        self.credentialsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.credentialsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.credentialsFrame.setObjectName("credentialsFrame")
        self.layoutWidget = QtWidgets.QWidget(self.credentialsFrame)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 14, 591, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupLabel = QtWidgets.QLabel(self.layoutWidget)
        self.groupLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupLabel.setObjectName("groupLabel")
        self.gridLayout.addWidget(self.groupLabel, 0, 0, 1, 1)
        self.searchGroupLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.searchGroupLineEdit.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.searchGroupLineEdit.setObjectName("searchGroupLineEdit")
        self.gridLayout.addWidget(self.searchGroupLineEdit, 0, 1, 1, 1)
        self.passwordLabel = QtWidgets.QLabel(self.layoutWidget)
        self.passwordLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.passwordLabel.setObjectName("passwordLabel")
        self.gridLayout.addWidget(self.passwordLabel, 1, 0, 1, 1)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.passwordLineEdit.setStyleSheet("background-color: rgb(153, 204, 255)")
        self.passwordLineEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.gridLayout.addWidget(self.passwordLineEdit, 1, 1, 1, 1)
        self.confirmPasswordLabel = QtWidgets.QLabel(self.layoutWidget)
        self.confirmPasswordLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.confirmPasswordLabel.setObjectName("confirmPasswordLabel")
        self.gridLayout.addWidget(self.confirmPasswordLabel, 2, 0, 1, 1)
        self.confirmPasswordLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.confirmPasswordLineEdit.setStyleSheet("background-color: rgb(153, 204, 255)")
        self.confirmPasswordLineEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.confirmPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmPasswordLineEdit.setObjectName("confirmPasswordLineEdit")
        self.gridLayout.addWidget(self.confirmPasswordLineEdit, 2, 1, 1, 1)
        self.newGroupTabWidget = QtWidgets.QTabWidget(searchGroupDialog)
        self.newGroupTabWidget.setGeometry(QtCore.QRect(10, 220, 611, 401))
        self.newGroupTabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.newGroupTabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.newGroupTabWidget.setTabsClosable(False)
        self.newGroupTabWidget.setMovable(True)
        self.newGroupTabWidget.setObjectName("newGroupTabWidget")
        self.groupDescriptionTab = QtWidgets.QWidget()
        self.groupDescriptionTab.setObjectName("groupDescriptionTab")
        self.descriptionFrame = QtWidgets.QFrame(self.groupDescriptionTab)
        self.descriptionFrame.setGeometry(QtCore.QRect(10, 10, 581, 271))
        self.descriptionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.descriptionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.descriptionFrame.setLineWidth(2)
        self.descriptionFrame.setObjectName("descriptionFrame")
        self.descTextEdit = QtWidgets.QTextEdit(self.descriptionFrame)
        self.descTextEdit.setGeometry(QtCore.QRect(13, 17, 551, 241))
        self.descTextEdit.setStyleSheet("background-color: rgb(245,245,245);")
        self.descTextEdit.setObjectName("descTextEdit")
        self.newGroupLabel = QtWidgets.QLabel(self.groupDescriptionTab)
        self.newGroupLabel.setGeometry(QtCore.QRect(380, 320, 211, 31))
        self.newGroupLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.newGroupLabel.setText("")
        self.newGroupLabel.setPixmap(QtGui.QPixmap("bristo_logo.png"))
        self.newGroupLabel.setScaledContents(True)
        self.newGroupLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.newGroupLabel.setObjectName("newGroupLabel")
        self.picPushButton = QtWidgets.QPushButton(self.groupDescriptionTab)
        self.picPushButton.setGeometry(QtCore.QRect(330, 330, 38, 27))
        self.picPushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/document-open-2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.picPushButton.setIcon(icon1)
        self.picPushButton.setObjectName("picPushButton")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/edit-group.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newGroupTabWidget.addTab(self.groupDescriptionTab, icon2, "")
        self.groupAddressTab = QtWidgets.QWidget()
        self.groupAddressTab.setObjectName("groupAddressTab")
        self.groupAddressFrame_2 = QtWidgets.QFrame(self.groupAddressTab)
        self.groupAddressFrame_2.setGeometry(QtCore.QRect(10, 50, 581, 271))
        self.groupAddressFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.groupAddressFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.groupAddressFrame_2.setLineWidth(2)
        self.groupAddressFrame_2.setObjectName("groupAddressFrame_2")
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupAddressFrame_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 20, 541, 221))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupAddressLabel_2 = QtWidgets.QLabel(self.layoutWidget_4)
        self.groupAddressLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupAddressLabel_2.setObjectName("groupAddressLabel_2")
        self.gridLayout_5.addWidget(self.groupAddressLabel_2, 0, 0, 1, 1)
        self.groupAddressLineEdit = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.groupAddressLineEdit.setStyleSheet("background-color: rgb(215, 255, 208);")
        self.groupAddressLineEdit.setObjectName("groupAddressLineEdit")
        self.gridLayout_5.addWidget(self.groupAddressLineEdit, 0, 1, 1, 1)
        self.groupSuiteLabel_2 = QtWidgets.QLabel(self.layoutWidget_4)
        self.groupSuiteLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupSuiteLabel_2.setObjectName("groupSuiteLabel_2")
        self.gridLayout_5.addWidget(self.groupSuiteLabel_2, 1, 0, 1, 1)
        self.groupSuiteLineEdit = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.groupSuiteLineEdit.setStyleSheet("background-color: rgb(215, 255, 208);")
        self.groupSuiteLineEdit.setObjectName("groupSuiteLineEdit")
        self.gridLayout_5.addWidget(self.groupSuiteLineEdit, 1, 1, 1, 1)
        self.groupCityLabel_2 = QtWidgets.QLabel(self.layoutWidget_4)
        self.groupCityLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupCityLabel_2.setObjectName("groupCityLabel_2")
        self.gridLayout_5.addWidget(self.groupCityLabel_2, 2, 0, 1, 1)
        self.groupCityLineEdit = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.groupCityLineEdit.setStyleSheet("background-color: rgb(215, 255, 208);")
        self.groupCityLineEdit.setObjectName("groupCityLineEdit")
        self.gridLayout_5.addWidget(self.groupCityLineEdit, 2, 1, 1, 1)
        self.groupStateLabel_2 = QtWidgets.QLabel(self.layoutWidget_4)
        self.groupStateLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupStateLabel_2.setObjectName("groupStateLabel_2")
        self.gridLayout_5.addWidget(self.groupStateLabel_2, 3, 0, 1, 1)
        self.groupStateLineEdit = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.groupStateLineEdit.setStyleSheet("background-color: rgb(215, 255, 208);")
        self.groupStateLineEdit.setObjectName("groupStateLineEdit")
        self.gridLayout_5.addWidget(self.groupStateLineEdit, 3, 1, 1, 1)
        self.groupPostalLabel_2 = QtWidgets.QLabel(self.layoutWidget_4)
        self.groupPostalLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupPostalLabel_2.setObjectName("groupPostalLabel_2")
        self.gridLayout_5.addWidget(self.groupPostalLabel_2, 4, 0, 1, 1)
        self.groupPostalLineEdit = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.groupPostalLineEdit.setStyleSheet("background-color: rgb(215, 255, 208);")
        self.groupPostalLineEdit.setObjectName("groupPostalLineEdit")
        self.gridLayout_5.addWidget(self.groupPostalLineEdit, 4, 1, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/address-book-new-2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newGroupTabWidget.addTab(self.groupAddressTab, icon3, "")
        self.groupContactTab = QtWidgets.QWidget()
        self.groupContactTab.setObjectName("groupContactTab")
        self.groupContactFrame_2 = QtWidgets.QFrame(self.groupContactTab)
        self.groupContactFrame_2.setGeometry(QtCore.QRect(10, 50, 591, 271))
        self.groupContactFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.groupContactFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.groupContactFrame_2.setObjectName("groupContactFrame_2")
        self.layoutWidget_5 = QtWidgets.QWidget(self.groupContactFrame_2)
        self.layoutWidget_5.setGeometry(QtCore.QRect(20, 20, 551, 231))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupOfficeWebLabel_2 = QtWidgets.QLabel(self.layoutWidget_5)
        self.groupOfficeWebLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupOfficeWebLabel_2.setObjectName("groupOfficeWebLabel_2")
        self.gridLayout_6.addWidget(self.groupOfficeWebLabel_2, 2, 0, 1, 1)
        self.groupOfficeFaxLineEdit = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.groupOfficeFaxLineEdit.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.groupOfficeFaxLineEdit.setObjectName("groupOfficeFaxLineEdit")
        self.gridLayout_6.addWidget(self.groupOfficeFaxLineEdit, 1, 1, 1, 1)
        self.groupOfficeWebLineEdit = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.groupOfficeWebLineEdit.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.groupOfficeWebLineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.groupOfficeWebLineEdit.setObjectName("groupOfficeWebLineEdit")
        self.gridLayout_6.addWidget(self.groupOfficeWebLineEdit, 2, 1, 1, 1)
        self.groupOfficeFaxLabel_2 = QtWidgets.QLabel(self.layoutWidget_5)
        self.groupOfficeFaxLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupOfficeFaxLabel_2.setObjectName("groupOfficeFaxLabel_2")
        self.gridLayout_6.addWidget(self.groupOfficeFaxLabel_2, 1, 0, 1, 1)
        self.groupOfficePhoneLineEdit = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.groupOfficePhoneLineEdit.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.groupOfficePhoneLineEdit.setObjectName("groupOfficePhoneLineEdit")
        self.gridLayout_6.addWidget(self.groupOfficePhoneLineEdit, 0, 1, 1, 1)
        self.groupOtherWebLineEdit = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.groupOtherWebLineEdit.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.groupOtherWebLineEdit.setObjectName("groupOtherWebLineEdit")
        self.gridLayout_6.addWidget(self.groupOtherWebLineEdit, 3, 1, 1, 1)
        self.groupOtherWebLabel_2 = QtWidgets.QLabel(self.layoutWidget_5)
        self.groupOtherWebLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupOtherWebLabel_2.setObjectName("groupOtherWebLabel_2")
        self.gridLayout_6.addWidget(self.groupOtherWebLabel_2, 3, 0, 1, 1)
        self.groupOfficePhoneLabel_2 = QtWidgets.QLabel(self.layoutWidget_5)
        self.groupOfficePhoneLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupOfficePhoneLabel_2.setObjectName("groupOfficePhoneLabel_2")
        self.gridLayout_6.addWidget(self.groupOfficePhoneLabel_2, 0, 0, 1, 1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/contact-new-2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newGroupTabWidget.addTab(self.groupContactTab, icon4, "")
        self.line = QtWidgets.QFrame(searchGroupDialog)
        self.line.setGeometry(QtCore.QRect(10, 200, 611, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupLabel.setBuddy(self.searchGroupLineEdit)
        self.passwordLabel.setBuddy(self.passwordLineEdit)
        self.confirmPasswordLabel.setBuddy(self.confirmPasswordLineEdit)
        self.groupAddressLabel_2.setBuddy(self.groupAddressLineEdit)
        self.groupSuiteLabel_2.setBuddy(self.groupSuiteLineEdit)
        self.groupCityLabel_2.setBuddy(self.groupCityLineEdit)
        self.groupStateLabel_2.setBuddy(self.groupStateLineEdit)
        self.groupPostalLabel_2.setBuddy(self.groupPostalLineEdit)
        self.groupOfficeWebLabel_2.setBuddy(self.groupOfficeWebLineEdit)
        self.groupOfficeFaxLabel_2.setBuddy(self.groupOfficeFaxLineEdit)
        self.groupOtherWebLabel_2.setBuddy(self.groupOtherWebLineEdit)
        self.groupOfficePhoneLabel_2.setBuddy(self.groupOfficePhoneLineEdit)

        self.retranslateUi(searchGroupDialog)
        self.newGroupTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(searchGroupDialog)

    def retranslateUi(self, searchGroupDialog):
        _translate = QtCore.QCoreApplication.translate
        searchGroupDialog.setWindowTitle(_translate("searchGroupDialog", "Search Group Dialog"))
        self.groupLabel.setText(_translate("searchGroupDialog", "Group:"))
        self.searchGroupLineEdit.setPlaceholderText(_translate("searchGroupDialog", "Search: Groups  and Group Name should not include spaces."))
        self.passwordLabel.setText(_translate("searchGroupDialog", "Password:"))
        self.passwordLineEdit.setPlaceholderText(_translate("searchGroupDialog", "Password m/b 9 char, upper, lower, number and one special character."))
        self.confirmPasswordLabel.setText(_translate("searchGroupDialog", "Confirm:"))
        self.confirmPasswordLineEdit.setPlaceholderText(_translate("searchGroupDialog", "Please re-enter the password."))
        self.picPushButton.setToolTip(_translate("searchGroupDialog", "Add Picture"))
        self.newGroupTabWidget.setTabText(self.newGroupTabWidget.indexOf(self.groupDescriptionTab), _translate("searchGroupDialog", "Group Description"))
        self.groupAddressLabel_2.setText(_translate("searchGroupDialog", "Address:"))
        self.groupSuiteLabel_2.setText(_translate("searchGroupDialog", "Suite/ Floor:"))
        self.groupCityLabel_2.setText(_translate("searchGroupDialog", "City:"))
        self.groupStateLabel_2.setText(_translate("searchGroupDialog", "State/Province:"))
        self.groupPostalLabel_2.setText(_translate("searchGroupDialog", "Zip:"))
        self.newGroupTabWidget.setTabText(self.newGroupTabWidget.indexOf(self.groupAddressTab), _translate("searchGroupDialog", "Address"))
        self.groupOfficeWebLabel_2.setText(_translate("searchGroupDialog", "Office Web:"))
        self.groupOfficeFaxLabel_2.setText(_translate("searchGroupDialog", "Office Fax:"))
        self.groupOtherWebLabel_2.setText(_translate("searchGroupDialog", "Other Web:"))
        self.groupOfficePhoneLabel_2.setText(_translate("searchGroupDialog", "Office Phone:"))
        self.newGroupTabWidget.setTabText(self.newGroupTabWidget.indexOf(self.groupContactTab), _translate("searchGroupDialog", "Contact"))

from . import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    searchGroupDialog = QtWidgets.QDialog()
    ui = Ui_searchGroupDialog()
    ui.setupUi(searchGroupDialog)
    searchGroupDialog.show()
    sys.exit(app.exec_())

