# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_contactsSearchDialog(object):
    def setupUi(self, contactsSearchDialog):
        contactsSearchDialog.setObjectName("contactsSearchDialog")
        contactsSearchDialog.resize(632, 655)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(contactsSearchDialog.sizePolicy().hasHeightForWidth())
        contactsSearchDialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/edit-user.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        contactsSearchDialog.setWindowIcon(icon)
        contactsSearchDialog.setWindowOpacity(1.0)
        contactsSearchDialog.setStyleSheet("")
        contactsSearchDialog.setSizeGripEnabled(False)
        self.nameFrame = QtWidgets.QFrame(contactsSearchDialog)
        self.nameFrame.setGeometry(QtCore.QRect(10, 10, 611, 141))
        self.nameFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nameFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nameFrame.setObjectName("nameFrame")
        self.layoutWidget = QtWidgets.QWidget(self.nameFrame)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 91, 591, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.credLabel = QtWidgets.QLabel(self.layoutWidget)
        self.credLabel.setObjectName("credLabel")
        self.horizontalLayout_3.addWidget(self.credLabel)
        self.credLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.credLineEdit.setStyleSheet("background-color: rgb(211, 213, 244);")
        self.credLineEdit.setObjectName("credLineEdit")
        self.horizontalLayout_3.addWidget(self.credLineEdit)
        self.layoutWidget1 = QtWidgets.QWidget(self.nameFrame)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 51, 591, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mrmrsLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.mrmrsLabel.setMaximumSize(QtCore.QSize(55, 16777215))
        self.mrmrsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mrmrsLabel.setObjectName("mrmrsLabel")
        self.horizontalLayout_2.addWidget(self.mrmrsLabel)
        self.mrmrsLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.mrmrsLineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.mrmrsLineEdit.setStyleSheet("background-color: rgb(211, 213, 244);")
        self.mrmrsLineEdit.setObjectName("mrmrsLineEdit")
        self.horizontalLayout_2.addWidget(self.mrmrsLineEdit)
        self.firstnameLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.firstnameLabel.setMaximumSize(QtCore.QSize(40, 16777215))
        self.firstnameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.firstnameLabel.setObjectName("firstnameLabel")
        self.horizontalLayout_2.addWidget(self.firstnameLabel)
        self.firstNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.firstNameLineEdit.setMaximumSize(QtCore.QSize(160, 16777215))
        self.firstNameLineEdit.setStyleSheet("background-color: rgb(211, 213, 244);")
        self.firstNameLineEdit.setObjectName("firstNameLineEdit")
        self.horizontalLayout_2.addWidget(self.firstNameLineEdit)
        self.middleNameLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.middleNameLabel.setMaximumSize(QtCore.QSize(30, 16777215))
        self.middleNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.middleNameLabel.setObjectName("middleNameLabel")
        self.horizontalLayout_2.addWidget(self.middleNameLabel)
        self.middleNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.middleNameLineEdit.sizePolicy().hasHeightForWidth())
        self.middleNameLineEdit.setSizePolicy(sizePolicy)
        self.middleNameLineEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.middleNameLineEdit.setStyleSheet("background-color: rgb(211, 213, 244);")
        self.middleNameLineEdit.setObjectName("middleNameLineEdit")
        self.horizontalLayout_2.addWidget(self.middleNameLineEdit)
        self.lastNameLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.lastNameLabel.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lastNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lastNameLabel.setObjectName("lastNameLabel")
        self.horizontalLayout_2.addWidget(self.lastNameLabel)
        self.lastNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lastNameLineEdit.setMaximumSize(QtCore.QSize(160, 16777215))
        self.lastNameLineEdit.setStyleSheet("background-color: rgb(211, 213, 244);")
        self.lastNameLineEdit.setObjectName("lastNameLineEdit")
        self.horizontalLayout_2.addWidget(self.lastNameLineEdit)
        self.layoutWidget2 = QtWidgets.QWidget(self.nameFrame)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 11, 591, 41))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.companyLabel = QtWidgets.QLabel(self.layoutWidget2)
        self.companyLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.companyLabel.setObjectName("companyLabel")
        self.horizontalLayout.addWidget(self.companyLabel)
        self.companyLineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.companyLineEdit.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.companyLineEdit.setObjectName("companyLineEdit")
        self.horizontalLayout.addWidget(self.companyLineEdit)
        self.contactTabWidget = QtWidgets.QTabWidget(contactsSearchDialog)
        self.contactTabWidget.setGeometry(QtCore.QRect(10, 170, 611, 441))
        self.contactTabWidget.setAcceptDrops(True)
        self.contactTabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.contactTabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.contactTabWidget.setDocumentMode(False)
        self.contactTabWidget.setTabsClosable(False)
        self.contactTabWidget.setMovable(True)
        self.contactTabWidget.setObjectName("contactTabWidget")
        self.contactTab = QtWidgets.QWidget()
        self.contactTab.setObjectName("contactTab")
        self.line_2 = QtWidgets.QFrame(self.contactTab)
        self.line_2.setGeometry(QtCore.QRect(310, 20, 20, 201))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.contactTab)
        self.line_3.setGeometry(QtCore.QRect(0, 220, 591, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.picFrame = QtWidgets.QFrame(self.contactTab)
        self.picFrame.setGeometry(QtCore.QRect(330, 20, 221, 201))
        self.picFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.picFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.picFrame.setObjectName("picFrame")
        self.picLabel = QtWidgets.QLabel(self.picFrame)
        self.picLabel.setGeometry(QtCore.QRect(10, 10, 201, 181))
        self.picLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.picLabel.setText("")
        self.picLabel.setPixmap(QtGui.QPixmap("default.jpg"))
        self.picLabel.setScaledContents(True)
        self.picLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.picLabel.setObjectName("picLabel")
        self.picPushButton = QtWidgets.QPushButton(self.contactTab)
        self.picPushButton.setGeometry(QtCore.QRect(561, 185, 38, 27))
        self.picPushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/document-open-2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.picPushButton.setIcon(icon1)
        self.picPushButton.setObjectName("picPushButton")
        self.layoutWidget3 = QtWidgets.QWidget(self.contactTab)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 70, 301, 151))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cellPhoneLabel = QtWidgets.QLabel(self.layoutWidget3)
        self.cellPhoneLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cellPhoneLabel.setObjectName("cellPhoneLabel")
        self.gridLayout_2.addWidget(self.cellPhoneLabel, 0, 0, 1, 1)
        self.cellPhoneLineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.cellPhoneLineEdit.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.cellPhoneLineEdit.setObjectName("cellPhoneLineEdit")
        self.gridLayout_2.addWidget(self.cellPhoneLineEdit, 0, 1, 1, 1)
        self.homePhoneLabel = QtWidgets.QLabel(self.layoutWidget3)
        self.homePhoneLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.homePhoneLabel.setObjectName("homePhoneLabel")
        self.gridLayout_2.addWidget(self.homePhoneLabel, 1, 0, 1, 1)
        self.homePhoneLineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.homePhoneLineEdit.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.homePhoneLineEdit.setObjectName("homePhoneLineEdit")
        self.gridLayout_2.addWidget(self.homePhoneLineEdit, 1, 1, 1, 1)
        self.officePhoneLabel = QtWidgets.QLabel(self.layoutWidget3)
        self.officePhoneLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.officePhoneLabel.setObjectName("officePhoneLabel")
        self.gridLayout_2.addWidget(self.officePhoneLabel, 2, 0, 1, 1)
        self.officePhoneLineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.officePhoneLineEdit.sizePolicy().hasHeightForWidth())
        self.officePhoneLineEdit.setSizePolicy(sizePolicy)
        self.officePhoneLineEdit.setStyleSheet("background-color: rgb(211, 213, 244);")
        self.officePhoneLineEdit.setObjectName("officePhoneLineEdit")
        self.gridLayout_2.addWidget(self.officePhoneLineEdit, 2, 1, 1, 1)
        self.officeFaxLabel = QtWidgets.QLabel(self.layoutWidget3)
        self.officeFaxLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.officeFaxLabel.setObjectName("officeFaxLabel")
        self.gridLayout_2.addWidget(self.officeFaxLabel, 3, 0, 1, 1)
        self.officeFaxLineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.officeFaxLineEdit.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.officeFaxLineEdit.setObjectName("officeFaxLineEdit")
        self.gridLayout_2.addWidget(self.officeFaxLineEdit, 3, 1, 1, 1)
        self.layoutWidget4 = QtWidgets.QWidget(self.contactTab)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 237, 591, 171))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.officeEmailLabel = QtWidgets.QLabel(self.layoutWidget4)
        self.officeEmailLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.officeEmailLabel.setObjectName("officeEmailLabel")
        self.gridLayout_3.addWidget(self.officeEmailLabel, 0, 0, 1, 1)
        self.officeEmailLineEdit = QtWidgets.QLineEdit(self.layoutWidget4)
        self.officeEmailLineEdit.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.officeEmailLineEdit.setObjectName("officeEmailLineEdit")
        self.gridLayout_3.addWidget(self.officeEmailLineEdit, 0, 1, 1, 1)
        self.personalEmailLabel = QtWidgets.QLabel(self.layoutWidget4)
        self.personalEmailLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.personalEmailLabel.setObjectName("personalEmailLabel")
        self.gridLayout_3.addWidget(self.personalEmailLabel, 1, 0, 1, 1)
        self.personalEmailLineEdit = QtWidgets.QLineEdit(self.layoutWidget4)
        self.personalEmailLineEdit.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.personalEmailLineEdit.setObjectName("personalEmailLineEdit")
        self.gridLayout_3.addWidget(self.personalEmailLineEdit, 1, 1, 1, 1)
        self.officeWebLabel = QtWidgets.QLabel(self.layoutWidget4)
        self.officeWebLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.officeWebLabel.setObjectName("officeWebLabel")
        self.gridLayout_3.addWidget(self.officeWebLabel, 2, 0, 1, 1)
        self.officeWebLineEdit = QtWidgets.QLineEdit(self.layoutWidget4)
        self.officeWebLineEdit.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.officeWebLineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.officeWebLineEdit.setObjectName("officeWebLineEdit")
        self.gridLayout_3.addWidget(self.officeWebLineEdit, 2, 1, 1, 1)
        self.personalWebLabel = QtWidgets.QLabel(self.layoutWidget4)
        self.personalWebLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.personalWebLabel.setObjectName("personalWebLabel")
        self.gridLayout_3.addWidget(self.personalWebLabel, 3, 0, 1, 1)
        self.personalWebLineEdit = QtWidgets.QLineEdit(self.layoutWidget4)
        self.personalWebLineEdit.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.personalWebLineEdit.setObjectName("personalWebLineEdit")
        self.gridLayout_3.addWidget(self.personalWebLineEdit, 3, 1, 1, 1)
        self.availabilityPushButton = QtWidgets.QPushButton(self.contactTab)
        self.availabilityPushButton.setGeometry(QtCore.QRect(580, 160, 16, 16))
        self.availabilityPushButton.setAutoFillBackground(True)
        self.availabilityPushButton.setStyleSheet("")
        self.availabilityPushButton.setText("")
        self.availabilityPushButton.setCheckable(True)
        self.availabilityPushButton.setObjectName("availabilityPushButton")
        self.groupCtLogoLabel = QtWidgets.QLabel(self.contactTab)
        self.groupCtLogoLabel.setGeometry(QtCore.QRect(110, 20, 201, 41))
        self.groupCtLogoLabel.setText("")
        self.groupCtLogoLabel.setScaledContents(True)
        self.groupCtLogoLabel.setObjectName("groupCtLogoLabel")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/contact-new-2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contactTabWidget.addTab(self.contactTab, icon2, "")
        self.addressTab = QtWidgets.QWidget()
        self.addressTab.setObjectName("addressTab")
        self.frame = QtWidgets.QFrame(self.addressTab)
        self.frame.setGeometry(QtCore.QRect(19, 39, 581, 271))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.layoutWidget5 = QtWidgets.QWidget(self.addressTab)
        self.layoutWidget5.setGeometry(QtCore.QRect(40, 70, 541, 221))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.addressLlabel = QtWidgets.QLabel(self.layoutWidget5)
        self.addressLlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.addressLlabel.setObjectName("addressLlabel")
        self.gridLayout.addWidget(self.addressLlabel, 0, 0, 1, 1)
        self.addressLineEdit = QtWidgets.QLineEdit(self.layoutWidget5)
        self.addressLineEdit.setStyleSheet("background-color: rgb(215, 255, 208);")
        self.addressLineEdit.setObjectName("addressLineEdit")
        self.gridLayout.addWidget(self.addressLineEdit, 0, 1, 1, 1)
        self.suiteLabel = QtWidgets.QLabel(self.layoutWidget5)
        self.suiteLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.suiteLabel.setObjectName("suiteLabel")
        self.gridLayout.addWidget(self.suiteLabel, 1, 0, 1, 1)
        self.suiteLineEdit = QtWidgets.QLineEdit(self.layoutWidget5)
        self.suiteLineEdit.setStyleSheet("background-color: rgb(215, 255, 208);")
        self.suiteLineEdit.setObjectName("suiteLineEdit")
        self.gridLayout.addWidget(self.suiteLineEdit, 1, 1, 1, 1)
        self.cityLabel = QtWidgets.QLabel(self.layoutWidget5)
        self.cityLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cityLabel.setObjectName("cityLabel")
        self.gridLayout.addWidget(self.cityLabel, 2, 0, 1, 1)
        self.cityLineEdit = QtWidgets.QLineEdit(self.layoutWidget5)
        self.cityLineEdit.setStyleSheet("background-color: rgb(215, 255, 208);")
        self.cityLineEdit.setObjectName("cityLineEdit")
        self.gridLayout.addWidget(self.cityLineEdit, 2, 1, 1, 1)
        self.stateLabel = QtWidgets.QLabel(self.layoutWidget5)
        self.stateLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stateLabel.setObjectName("stateLabel")
        self.gridLayout.addWidget(self.stateLabel, 3, 0, 1, 1)
        self.stateLineEdit = QtWidgets.QLineEdit(self.layoutWidget5)
        self.stateLineEdit.setStyleSheet("background-color: rgb(215, 255, 208);")
        self.stateLineEdit.setObjectName("stateLineEdit")
        self.gridLayout.addWidget(self.stateLineEdit, 3, 1, 1, 1)
        self.postalLabel = QtWidgets.QLabel(self.layoutWidget5)
        self.postalLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.postalLabel.setObjectName("postalLabel")
        self.gridLayout.addWidget(self.postalLabel, 4, 0, 1, 1)
        self.postalLineEdit = QtWidgets.QLineEdit(self.layoutWidget5)
        self.postalLineEdit.setStyleSheet("background-color: rgb(215, 255, 208);")
        self.postalLineEdit.setObjectName("postalLineEdit")
        self.gridLayout.addWidget(self.postalLineEdit, 4, 1, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/address-book-new-2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contactTabWidget.addTab(self.addressTab, icon3, "")
        self.mapTab = QtWidgets.QWidget()
        self.mapTab.setObjectName("mapTab")
        self.mapTabFrame = QtWidgets.QFrame(self.mapTab)
        self.mapTabFrame.setGeometry(QtCore.QRect(9, 9, 591, 361))
        self.mapTabFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mapTabFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mapTabFrame.setObjectName("mapTabFrame")
        self.refreshMapPushButton = QtWidgets.QPushButton(self.mapTab)
        self.refreshMapPushButton.setGeometry(QtCore.QRect(530, 380, 61, 27))
        self.refreshMapPushButton.setObjectName("refreshMapPushButton")
        self.browserMapPushButton = QtWidgets.QPushButton(self.mapTab)
        self.browserMapPushButton.setGeometry(QtCore.QRect(460, 380, 61, 27))
        self.browserMapPushButton.setObjectName("browserMapPushButton")
        self.directionsPushButton = QtWidgets.QPushButton(self.mapTab)
        self.directionsPushButton.setGeometry(QtCore.QRect(368, 380, 81, 27))
        self.directionsPushButton.setObjectName("directionsPushButton")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/Bevel-And-Emboss-Media-Map.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contactTabWidget.addTab(self.mapTab, icon4, "")
        self.notesTab = QtWidgets.QWidget()
        self.notesTab.setObjectName("notesTab")
        self.notesFrame = QtWidgets.QFrame(self.notesTab)
        self.notesFrame.setGeometry(QtCore.QRect(9, 9, 591, 371))
        self.notesFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.notesFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.notesFrame.setObjectName("notesFrame")
        self.notesTableWidget = QtWidgets.QTableWidget(self.notesFrame)
        self.notesTableWidget.setGeometry(QtCore.QRect(10, 10, 571, 321))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notesTableWidget.sizePolicy().hasHeightForWidth())
        self.notesTableWidget.setSizePolicy(sizePolicy)
        self.notesTableWidget.setMaximumSize(QtCore.QSize(16777215, 321))
        self.notesTableWidget.setAcceptDrops(True)
        self.notesTableWidget.setMidLineWidth(1)
        self.notesTableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.notesTableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.notesTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.notesTableWidget.setDragEnabled(True)
        self.notesTableWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.notesTableWidget.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.notesTableWidget.setAlternatingRowColors(True)
        self.notesTableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.notesTableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.notesTableWidget.setWordWrap(True)
        self.notesTableWidget.setRowCount(2000)
        self.notesTableWidget.setColumnCount(2)
        self.notesTableWidget.setObjectName("notesTableWidget")
        self.notesTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.notesTableWidget.horizontalHeader().setDefaultSectionSize(140)
        self.notesTableWidget.horizontalHeader().setMinimumSectionSize(56)
        self.notesTableWidget.horizontalHeader().setStretchLastSection(True)
        self.notesTableWidget.verticalHeader().setVisible(False)
        self.notesTableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.notesTableWidget.verticalHeader().setDefaultSectionSize(50)
        self.notesDetailPushButton = QtWidgets.QPushButton(self.notesFrame)
        self.notesDetailPushButton.setGeometry(QtCore.QRect(500, 340, 61, 27))
        self.notesDetailPushButton.setObjectName("notesDetailPushButton")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/document-sign.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contactTabWidget.addTab(self.notesTab, icon5, "")
        self.fileTab = QtWidgets.QWidget()
        self.fileTab.setObjectName("fileTab")
        self.fileFrame = QtWidgets.QFrame(self.fileTab)
        self.fileFrame.setGeometry(QtCore.QRect(9, 9, 591, 371))
        self.fileFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fileFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fileFrame.setObjectName("fileFrame")
        self.fileTableWidget = QtWidgets.QTableWidget(self.fileFrame)
        self.fileTableWidget.setGeometry(QtCore.QRect(10, 10, 571, 321))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileTableWidget.sizePolicy().hasHeightForWidth())
        self.fileTableWidget.setSizePolicy(sizePolicy)
        self.fileTableWidget.setMaximumSize(QtCore.QSize(16777215, 321))
        self.fileTableWidget.setAcceptDrops(True)
        self.fileTableWidget.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.fileTableWidget.setMidLineWidth(1)
        self.fileTableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.fileTableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.fileTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.fileTableWidget.setDragEnabled(True)
        self.fileTableWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.fileTableWidget.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.fileTableWidget.setAlternatingRowColors(True)
        self.fileTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.fileTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.fileTableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.fileTableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.fileTableWidget.setWordWrap(True)
        self.fileTableWidget.setRowCount(2000)
        self.fileTableWidget.setColumnCount(3)
        self.fileTableWidget.setObjectName("fileTableWidget")
        self.fileTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.fileTableWidget.horizontalHeader().setDefaultSectionSize(140)
        self.fileTableWidget.horizontalHeader().setMinimumSectionSize(45)
        self.fileTableWidget.horizontalHeader().setStretchLastSection(True)
        self.fileTableWidget.verticalHeader().setVisible(False)
        self.fileTableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.fileTableWidget.verticalHeader().setDefaultSectionSize(30)
        self.filePushButton = QtWidgets.QPushButton(self.fileFrame)
        self.filePushButton.setGeometry(QtCore.QRect(530, 340, 31, 27))
        self.filePushButton.setText("")
        self.filePushButton.setIcon(icon1)
        self.filePushButton.setObjectName("filePushButton")
        self.contactTabWidget.addTab(self.fileTab, icon1, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.activityTabWidget = QtWidgets.QTabWidget(self.tab)
        self.activityTabWidget.setGeometry(QtCore.QRect(12, 9, 591, 391))
        self.activityTabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.activityTabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.activityTabWidget.setDocumentMode(True)
        self.activityTabWidget.setMovable(True)
        self.activityTabWidget.setObjectName("activityTabWidget")
        self.phoneCallsTab = QtWidgets.QWidget()
        self.phoneCallsTab.setObjectName("phoneCallsTab")
        self.notesFrame_2 = QtWidgets.QFrame(self.phoneCallsTab)
        self.notesFrame_2.setGeometry(QtCore.QRect(-10, -10, 591, 371))
        self.notesFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.notesFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.notesFrame_2.setObjectName("notesFrame_2")
        self.callsTableWidget = QtWidgets.QTableWidget(self.notesFrame_2)
        self.callsTableWidget.setGeometry(QtCore.QRect(20, 20, 561, 311))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.callsTableWidget.sizePolicy().hasHeightForWidth())
        self.callsTableWidget.setSizePolicy(sizePolicy)
        self.callsTableWidget.setMaximumSize(QtCore.QSize(16777215, 321))
        self.callsTableWidget.setAcceptDrops(True)
        self.callsTableWidget.setStyleSheet("background-color: rgb(215, 255, 208);")
        self.callsTableWidget.setMidLineWidth(1)
        self.callsTableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.callsTableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.callsTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.callsTableWidget.setDragEnabled(True)
        self.callsTableWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.callsTableWidget.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.callsTableWidget.setAlternatingRowColors(True)
        self.callsTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.callsTableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.callsTableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.callsTableWidget.setWordWrap(True)
        self.callsTableWidget.setRowCount(2000)
        self.callsTableWidget.setColumnCount(6)
        self.callsTableWidget.setObjectName("callsTableWidget")
        self.callsTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.callsTableWidget.horizontalHeader().setDefaultSectionSize(140)
        self.callsTableWidget.horizontalHeader().setMinimumSectionSize(56)
        self.callsTableWidget.horizontalHeader().setStretchLastSection(True)
        self.callsTableWidget.verticalHeader().setVisible(False)
        self.callsTableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.callsTableWidget.verticalHeader().setDefaultSectionSize(50)
        self.callsDetailPushButton = QtWidgets.QPushButton(self.notesFrame_2)
        self.callsDetailPushButton.setGeometry(QtCore.QRect(500, 340, 61, 27))
        self.callsDetailPushButton.setObjectName("callsDetailPushButton")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/call-start.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.activityTabWidget.addTab(self.phoneCallsTab, icon6, "")
        self.eMailsTab = QtWidgets.QWidget()
        self.eMailsTab.setObjectName("eMailsTab")
        self.emailFrame = QtWidgets.QFrame(self.eMailsTab)
        self.emailFrame.setGeometry(QtCore.QRect(0, 10, 591, 311))
        self.emailFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.emailFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.emailFrame.setObjectName("emailFrame")
        self.emailRefreshPushButton = QtWidgets.QPushButton(self.eMailsTab)
        self.emailRefreshPushButton.setGeometry(QtCore.QRect(500, 330, 61, 27))
        self.emailRefreshPushButton.setObjectName("emailRefreshPushButton")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/mail-generic-2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.activityTabWidget.addTab(self.eMailsTab, icon7, "")
        self.appointmentTab = QtWidgets.QWidget()
        self.appointmentTab.setObjectName("appointmentTab")
        self.apptFrame = QtWidgets.QFrame(self.appointmentTab)
        self.apptFrame.setGeometry(QtCore.QRect(9, 9, 571, 341))
        self.apptFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.apptFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.apptFrame.setObjectName("apptFrame")
        self.apptTableWidget = QtWidgets.QTableWidget(self.apptFrame)
        self.apptTableWidget.setGeometry(QtCore.QRect(10, 10, 551, 291))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apptTableWidget.sizePolicy().hasHeightForWidth())
        self.apptTableWidget.setSizePolicy(sizePolicy)
        self.apptTableWidget.setMaximumSize(QtCore.QSize(16777215, 321))
        self.apptTableWidget.setAcceptDrops(True)
        self.apptTableWidget.setStyleSheet("background-color: rgb(211, 213, 244);")
        self.apptTableWidget.setMidLineWidth(1)
        self.apptTableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.apptTableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.apptTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.apptTableWidget.setDragEnabled(True)
        self.apptTableWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.apptTableWidget.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.apptTableWidget.setAlternatingRowColors(True)
        self.apptTableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.apptTableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.apptTableWidget.setWordWrap(True)
        self.apptTableWidget.setRowCount(2000)
        self.apptTableWidget.setColumnCount(6)
        self.apptTableWidget.setObjectName("apptTableWidget")
        self.apptTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.apptTableWidget.horizontalHeader().setDefaultSectionSize(140)
        self.apptTableWidget.horizontalHeader().setMinimumSectionSize(56)
        self.apptTableWidget.horizontalHeader().setStretchLastSection(True)
        self.apptTableWidget.verticalHeader().setVisible(False)
        self.apptTableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.apptTableWidget.verticalHeader().setDefaultSectionSize(50)
        self.apptDetailPushButton = QtWidgets.QPushButton(self.apptFrame)
        self.apptDetailPushButton.setGeometry(QtCore.QRect(460, 310, 61, 27))
        self.apptDetailPushButton.setObjectName("apptDetailPushButton")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/appointment-new-2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.activityTabWidget.addTab(self.appointmentTab, icon8, "")
        self.messagesTab = QtWidgets.QWidget()
        self.messagesTab.setObjectName("messagesTab")
        self.msgFrame = QtWidgets.QFrame(self.messagesTab)
        self.msgFrame.setGeometry(QtCore.QRect(10, 10, 571, 341))
        self.msgFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.msgFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.msgFrame.setObjectName("msgFrame")
        self.msgTableWidget = QtWidgets.QTableWidget(self.msgFrame)
        self.msgTableWidget.setGeometry(QtCore.QRect(10, 10, 551, 291))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msgTableWidget.sizePolicy().hasHeightForWidth())
        self.msgTableWidget.setSizePolicy(sizePolicy)
        self.msgTableWidget.setMaximumSize(QtCore.QSize(16777215, 321))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.msgTableWidget.setPalette(palette)
        self.msgTableWidget.setAcceptDrops(True)
        self.msgTableWidget.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.msgTableWidget.setMidLineWidth(1)
        self.msgTableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.msgTableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.msgTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.msgTableWidget.setDragEnabled(True)
        self.msgTableWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.msgTableWidget.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.msgTableWidget.setAlternatingRowColors(True)
        self.msgTableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.msgTableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.msgTableWidget.setWordWrap(True)
        self.msgTableWidget.setRowCount(2000)
        self.msgTableWidget.setColumnCount(6)
        self.msgTableWidget.setObjectName("msgTableWidget")
        self.msgTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.msgTableWidget.horizontalHeader().setDefaultSectionSize(140)
        self.msgTableWidget.horizontalHeader().setMinimumSectionSize(56)
        self.msgTableWidget.horizontalHeader().setStretchLastSection(True)
        self.msgTableWidget.verticalHeader().setVisible(False)
        self.msgTableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.msgTableWidget.verticalHeader().setDefaultSectionSize(50)
        self.msgTableWidget.verticalHeader().setStretchLastSection(True)
        self.msgDetailPushButton = QtWidgets.QPushButton(self.msgFrame)
        self.msgDetailPushButton.setGeometry(QtCore.QRect(460, 310, 61, 27))
        self.msgDetailPushButton.setObjectName("msgDetailPushButton")
        self.chkmsgPushButton = QtWidgets.QPushButton(self.msgFrame)
        self.chkmsgPushButton.setGeometry(QtCore.QRect(330, 310, 121, 27))
        self.chkmsgPushButton.setObjectName("chkmsgPushButton")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/message.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.activityTabWidget.addTab(self.messagesTab, icon9, "")
        self.calendarTab = QtWidgets.QWidget()
        self.calendarTab.setObjectName("calendarTab")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.calendarTab)
        self.calendarWidget.setGeometry(QtCore.QRect(-5, 1, 581, 351))
        self.calendarWidget.setAutoFillBackground(True)
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setObjectName("calendarWidget")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/view-calendar-month.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.activityTabWidget.addTab(self.calendarTab, icon10, "")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/edit-group.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contactTabWidget.addTab(self.tab, icon11, "")
        self.group = QtWidgets.QWidget()
        self.group.setObjectName("group")
        self.frame_2 = QtWidgets.QFrame(self.group)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 591, 391))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.line_4 = QtWidgets.QFrame(self.frame_2)
        self.line_4.setGeometry(QtCore.QRect(290, 10, 20, 371))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(309, 9, 271, 371))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame_3)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 10, 251, 351))
        self.plainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.plainTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.groupLogoLabel = QtWidgets.QLabel(self.frame_2)
        self.groupLogoLabel.setGeometry(QtCore.QRect(30, 50, 251, 71))
        self.groupLogoLabel.setText("")
        self.groupLogoLabel.setScaledContents(True)
        self.groupLogoLabel.setObjectName("groupLogoLabel")
        self.line_5 = QtWidgets.QFrame(self.frame_2)
        self.line_5.setGeometry(QtCore.QRect(10, 170, 281, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(10, 190, 281, 141))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.layoutWidget6 = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 10, 261, 121))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget6)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupNameLabel = QtWidgets.QLabel(self.layoutWidget6)
        self.groupNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupNameLabel.setObjectName("groupNameLabel")
        self.gridLayout_4.addWidget(self.groupNameLabel, 0, 0, 1, 1)
        self.groupNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget6)
        self.groupNameLineEdit.setStyleSheet("background-color: rgb(255, 250, 217)")
        self.groupNameLineEdit.setObjectName("groupNameLineEdit")
        self.gridLayout_4.addWidget(self.groupNameLineEdit, 0, 1, 1, 1)
        self.groupNamePwdLabel = QtWidgets.QLabel(self.layoutWidget6)
        self.groupNamePwdLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupNamePwdLabel.setObjectName("groupNamePwdLabel")
        self.gridLayout_4.addWidget(self.groupNamePwdLabel, 1, 0, 1, 1)
        self.groupPwdLineEdit = QtWidgets.QLineEdit(self.layoutWidget6)
        self.groupPwdLineEdit.setStyleSheet("background-color: rgb(211, 213, 244);")
        self.groupPwdLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.groupPwdLineEdit.setObjectName("groupPwdLineEdit")
        self.gridLayout_4.addWidget(self.groupPwdLineEdit, 1, 1, 1, 1)
        self.accessGroupPushButton = QtWidgets.QPushButton(self.frame_2)
        self.accessGroupPushButton.setGeometry(QtCore.QRect(168, 350, 121, 27))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icons/family.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.accessGroupPushButton.setIcon(icon12)
        self.accessGroupPushButton.setObjectName("accessGroupPushButton")
        self.contactTabWidget.addTab(self.group, icon12, "")
        self.line = QtWidgets.QFrame(contactsSearchDialog)
        self.line.setGeometry(QtCore.QRect(10, 150, 611, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(contactsSearchDialog)
        self.label.setGeometry(QtCore.QRect(10, 620, 161, 21))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/icons/bristo_logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.credLabel.setBuddy(self.credLineEdit)
        self.mrmrsLabel.setBuddy(self.mrmrsLineEdit)
        self.firstnameLabel.setBuddy(self.firstNameLineEdit)
        self.middleNameLabel.setBuddy(self.middleNameLineEdit)
        self.lastNameLabel.setBuddy(self.lastNameLineEdit)
        self.companyLabel.setBuddy(self.companyLineEdit)
        self.cellPhoneLabel.setBuddy(self.cellPhoneLineEdit)
        self.homePhoneLabel.setBuddy(self.homePhoneLineEdit)
        self.officePhoneLabel.setBuddy(self.officePhoneLineEdit)
        self.officeFaxLabel.setBuddy(self.officeFaxLineEdit)
        self.officeEmailLabel.setBuddy(self.officeEmailLineEdit)
        self.personalEmailLabel.setBuddy(self.personalEmailLineEdit)
        self.officeWebLabel.setBuddy(self.officeWebLineEdit)
        self.personalWebLabel.setBuddy(self.personalWebLineEdit)
        self.addressLlabel.setBuddy(self.addressLineEdit)
        self.suiteLabel.setBuddy(self.suiteLineEdit)
        self.cityLabel.setBuddy(self.cityLineEdit)
        self.stateLabel.setBuddy(self.stateLineEdit)
        self.postalLabel.setBuddy(self.postalLineEdit)

        self.retranslateUi(contactsSearchDialog)
        self.contactTabWidget.setCurrentIndex(0)
        self.activityTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(contactsSearchDialog)
        contactsSearchDialog.setTabOrder(self.companyLineEdit, self.mrmrsLineEdit)
        contactsSearchDialog.setTabOrder(self.mrmrsLineEdit, self.firstNameLineEdit)
        contactsSearchDialog.setTabOrder(self.firstNameLineEdit, self.middleNameLineEdit)
        contactsSearchDialog.setTabOrder(self.middleNameLineEdit, self.lastNameLineEdit)
        contactsSearchDialog.setTabOrder(self.lastNameLineEdit, self.credLineEdit)
        contactsSearchDialog.setTabOrder(self.credLineEdit, self.cellPhoneLineEdit)
        contactsSearchDialog.setTabOrder(self.cellPhoneLineEdit, self.homePhoneLineEdit)
        contactsSearchDialog.setTabOrder(self.homePhoneLineEdit, self.officePhoneLineEdit)
        contactsSearchDialog.setTabOrder(self.officePhoneLineEdit, self.officeFaxLineEdit)
        contactsSearchDialog.setTabOrder(self.officeFaxLineEdit, self.officeEmailLineEdit)
        contactsSearchDialog.setTabOrder(self.officeEmailLineEdit, self.personalEmailLineEdit)
        contactsSearchDialog.setTabOrder(self.personalEmailLineEdit, self.officeWebLineEdit)
        contactsSearchDialog.setTabOrder(self.officeWebLineEdit, self.personalWebLineEdit)
        contactsSearchDialog.setTabOrder(self.personalWebLineEdit, self.picPushButton)
        contactsSearchDialog.setTabOrder(self.picPushButton, self.addressLineEdit)
        contactsSearchDialog.setTabOrder(self.addressLineEdit, self.suiteLineEdit)
        contactsSearchDialog.setTabOrder(self.suiteLineEdit, self.cityLineEdit)
        contactsSearchDialog.setTabOrder(self.cityLineEdit, self.stateLineEdit)
        contactsSearchDialog.setTabOrder(self.stateLineEdit, self.postalLineEdit)
        contactsSearchDialog.setTabOrder(self.postalLineEdit, self.contactTabWidget)
        contactsSearchDialog.setTabOrder(self.contactTabWidget, self.notesTableWidget)
        contactsSearchDialog.setTabOrder(self.notesTableWidget, self.notesDetailPushButton)
        contactsSearchDialog.setTabOrder(self.notesDetailPushButton, self.fileTableWidget)
        contactsSearchDialog.setTabOrder(self.fileTableWidget, self.filePushButton)

    def retranslateUi(self, contactsSearchDialog):
        _translate = QtCore.QCoreApplication.translate
        contactsSearchDialog.setWindowTitle(_translate("contactsSearchDialog", "Contacts Dialog"))
        self.credLabel.setText(_translate("contactsSearchDialog", "Title:"))
        self.mrmrsLabel.setText(_translate("contactsSearchDialog", "Mr/Mrs:"))
        self.firstnameLabel.setText(_translate("contactsSearchDialog", "First :"))
        self.firstNameLineEdit.setPlaceholderText(_translate("contactsSearchDialog", "Search: First Name"))
        self.middleNameLabel.setText(_translate("contactsSearchDialog", "M:"))
        self.lastNameLabel.setText(_translate("contactsSearchDialog", "Last:"))
        self.lastNameLineEdit.setPlaceholderText(_translate("contactsSearchDialog", "Search: Last Name"))
        self.companyLabel.setText(_translate("contactsSearchDialog", "Company/Organization:"))
        self.companyLineEdit.setPlaceholderText(_translate("contactsSearchDialog", "Search: Company Name"))
        self.picPushButton.setToolTip(_translate("contactsSearchDialog", "Add Picture"))
        self.cellPhoneLabel.setText(_translate("contactsSearchDialog", "Cell Phone:"))
        self.homePhoneLabel.setText(_translate("contactsSearchDialog", "Home Phone:"))
        self.officePhoneLabel.setText(_translate("contactsSearchDialog", "Office Phone:"))
        self.officeFaxLabel.setText(_translate("contactsSearchDialog", "Office Fax:"))
        self.officeEmailLabel.setText(_translate("contactsSearchDialog", "Office Email:"))
        self.personalEmailLabel.setText(_translate("contactsSearchDialog", "Personal Email:"))
        self.officeWebLabel.setText(_translate("contactsSearchDialog", "Office Web:"))
        self.personalWebLabel.setText(_translate("contactsSearchDialog", "Personal Web:"))
        self.contactTabWidget.setTabText(self.contactTabWidget.indexOf(self.contactTab), _translate("contactsSearchDialog", "Contact"))
        self.addressLlabel.setText(_translate("contactsSearchDialog", "Address:"))
        self.suiteLabel.setText(_translate("contactsSearchDialog", "Suite/ Floor:"))
        self.cityLabel.setText(_translate("contactsSearchDialog", "City:"))
        self.stateLabel.setText(_translate("contactsSearchDialog", "State/Province:"))
        self.postalLabel.setText(_translate("contactsSearchDialog", "Zip:"))
        self.contactTabWidget.setTabText(self.contactTabWidget.indexOf(self.addressTab), _translate("contactsSearchDialog", "Address"))
        self.refreshMapPushButton.setText(_translate("contactsSearchDialog", "Refresh"))
        self.browserMapPushButton.setText(_translate("contactsSearchDialog", "Browser"))
        self.directionsPushButton.setText(_translate("contactsSearchDialog", "Directions"))
        self.contactTabWidget.setTabText(self.contactTabWidget.indexOf(self.mapTab), _translate("contactsSearchDialog", "Map"))
        self.notesTableWidget.setSortingEnabled(True)
        self.notesDetailPushButton.setText(_translate("contactsSearchDialog", "Resize"))
        self.contactTabWidget.setTabText(self.contactTabWidget.indexOf(self.notesTab), _translate("contactsSearchDialog", "Notes"))
        self.fileTableWidget.setSortingEnabled(True)
        self.filePushButton.setToolTip(_translate("contactsSearchDialog", "Add New File"))
        self.contactTabWidget.setTabText(self.contactTabWidget.indexOf(self.fileTab), _translate("contactsSearchDialog", "Files"))
        self.callsTableWidget.setSortingEnabled(True)
        self.callsDetailPushButton.setText(_translate("contactsSearchDialog", "Resize"))
        self.activityTabWidget.setTabText(self.activityTabWidget.indexOf(self.phoneCallsTab), _translate("contactsSearchDialog", "Phone Calls"))
        self.emailRefreshPushButton.setText(_translate("contactsSearchDialog", "Refresh"))
        self.activityTabWidget.setTabText(self.activityTabWidget.indexOf(self.eMailsTab), _translate("contactsSearchDialog", "eMails"))
        self.apptTableWidget.setSortingEnabled(True)
        self.apptDetailPushButton.setText(_translate("contactsSearchDialog", "Resize"))
        self.activityTabWidget.setTabText(self.activityTabWidget.indexOf(self.appointmentTab), _translate("contactsSearchDialog", "Appointments"))
        self.msgTableWidget.setSortingEnabled(True)
        self.msgDetailPushButton.setText(_translate("contactsSearchDialog", "Resize"))
        self.chkmsgPushButton.setText(_translate("contactsSearchDialog", "Check Messages"))
        self.activityTabWidget.setTabText(self.activityTabWidget.indexOf(self.messagesTab), _translate("contactsSearchDialog", "Messages"))
        self.activityTabWidget.setTabText(self.activityTabWidget.indexOf(self.calendarTab), _translate("contactsSearchDialog", "Calendar"))
        self.contactTabWidget.setTabText(self.contactTabWidget.indexOf(self.tab), _translate("contactsSearchDialog", "Activity"))
        self.groupNameLabel.setText(_translate("contactsSearchDialog", "Group Name:"))
        self.groupNamePwdLabel.setText(_translate("contactsSearchDialog", "Password:"))
        self.accessGroupPushButton.setText(_translate("contactsSearchDialog", "Group Login"))
        self.contactTabWidget.setTabText(self.contactTabWidget.indexOf(self.group), _translate("contactsSearchDialog", "Group"))

from . import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    contactsSearchDialog = QtWidgets.QDialog()
    ui = Ui_contactsSearchDialog()
    ui.setupUi(contactsSearchDialog)
    contactsSearchDialog.show()
    sys.exit(app.exec_())

