
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-17T17:47:44+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2853b8924ef3287b66fcaaf4ea9e97b47462c95f",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
