- hosts: all
  vars:
    nodepool_log_dir: '{{ ansible_user_dir }}/work/logs/nodepool'
  tasks:
    - name: 'Copy files from {{ nodepool_log_dir }}'
      synchronize:
        src: '{{ nodepool_log_dir }}'
        dest: '{{ zuul.executor.log_root }}/{{ inventory_hostname }}'
        mode: pull
