[tool.poetry]
name = "othello-ai"
packages = [
    {include = "othelloai"}
]
version = "0.1.1"
description = "Othello game engine"
authors = ["Jason R. Carrete <jasoncarrete5@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/jcarrete5/othello-ai"
keywords = ["othello", "ai"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pylint = "^2.4"
pytest = "^5.2.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
