
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-27T18:51:24-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "19b10c47988df504872a4fe07c421b0555b3127e",
 "version": "0.29.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
