[tool.poetry]
name = "rimteam-editor"
version = "0.1.26"
description = ""
authors = ["RIM team"]

[tool.poetry.dependencies]
python = "^3.7"
gitpython = "^3.0"
requests = "^2.22"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.scripts]
reditor = "rimteam_editor.__main__:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
