
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-17T17:02:23-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6aa8a97d1cf8612d58581ed9bfbef001b58f0ac1",
 "version": "1.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
