#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['quart_compress']

package_data = \
{'': ['*']}

install_requires = \
['quart']

setup(name='quart-compress2',
      version='1.1.0',
      description='Quart-Compress.',
      author='Florian Dahlitz',
      author_email='f2dahlitz@freenet.de',
      url='https://github.com/DahlitzFlorian/quart-compress',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.7',
     )
