[tool.poetry]
name = "desdeo_emo"
version = "0.1.1"
description = "The python version reference vector guided evolutionary algorithm."
authors = ["Bhupinder Saini"]
license = "MPL-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.16"
pandas = "^0.25"
optproblems = "^1.2"
pygmo = "^2.10"
scipy = "^1.2"
diversipy = "^0.8.0"
pyDOE = "^0.3.8"
# tqdm = "^4.31"
jupyter = "^1.0"
scikit-learn = "^0.21.2"
# matplotlib = "^3.1"
# deap = "^1.3"
# gplearn = "^0.4.1"
# graphviz = "^0.11.1"
# xlrd = "^1.2"
# numpydoc = "^0.9.1"
# plotly = "^4.1"
desdeo_problem = "^0.8.0"
plotly = "^4.1"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
black = {version = "^18.3-alpha.0",allows-prereleases = true}
sphinx = "^2.0"
recommonmark = "^0.5.0"
sphinx_rtd_theme = "^0.4.3"
pylint = "^2.3"
mypy = "^0.701.0"
# altair = "^3.0"
# vega = "^2.1"
# vega_datasets = "^0.7.0"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

