
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-24T14:14:09-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2076d18bfae092d441c2f13fc9d9359ed8047d15",
 "version": "0.8.2.post0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
