server:
  grpc:
    channel_address: '[::]:50051'
    max_thread_pool_workers: 50
    max_concurrent_rpcs: 50
    enable_compression: False
    optimization_target: 'blend'        # 'latency', 'blend', or 'throughput'
    fetch_max_nbytes: 500_000_000  # Bytes
  admin:
    restrict_push: False
    username: '--none--'                  # auth to make changes if restrict_push -> True
    password: '--none--'                  # auth to make changes if restrict_push -> True
client:
  grpc:
    enable_compression: False
    optimization_target: 'blend'          # 'latency', 'blend', or 'throughput'
    push_max_nbytes: 600_000_000   # Bytes
