- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - check-requirements
    check:
      jobs:
        - monasca-tempest-python-mysql
        - monasca-tempest-python-postgresql:
            voting: false
        - monasca-tempest-java-mysql
        - monasca-tempest-java-postgresql:
            voting: false
        - monasca-tempest-python-cassandra
        - monasca-tempest-java-cassandra
        - legacy-monasca-persister-maven-build
        - openstack-tox-cover
    gate:
      jobs:
        - monasca-tempest-python-mysql
        - monasca-tempest-java-mysql
        - monasca-tempest-python-cassandra
        - monasca-tempest-java-cassandra
        - legacy-monasca-persister-maven-build
        - openstack-tox-cover
    post:
      jobs:
        - legacy-monasca-persister-localrepo-upload
